import { useMemo, useState } from 'react'
import PayrollGrid from './PayrollGrid'
import PayrollLegend from './PayrollLegend'
import { buildColumns } from '../lib/payrollView'
import { formatValue } from '../lib/payrollMoney'

/** Keeps the approved #158 grid and its keyboard/clipboard behavior; only adapts the monthly draft boundary. */
export default function MonthlyGridPanel({ rows, config, totals, drafts, canEdit, active, onEdit, onUndo, onRedo, canUndo, canRedo, onSort, sort, onOpenWorker, widths, onWidthsChange, onEditingChange, onNotice }) {
  const [selected, setSelected] = useState(null)
  const columns = useMemo(() => buildColumns(config), [config])
  const controller = { edit: changes => { if (canEdit) onEdit(changes) }, valueOf: (id, key) => { const row = rows.find(r => r.id === id); const draft = row && drafts[row.employee_id]; return draft ? draft.values[key] ?? null : row?.inputs?.[key] ?? null } }
  const column = columns.find(c => c.prop === selected?.prop); const row = rows.find(r => r.id === selected?.id); const cell = row && column && !column.identity ? row.cells[column.prop] : null
  function paste(plan) { if (plan.errors.length) { onNotice(`لم يُلصق شيء: ${plan.errors.slice(0, 5).map(e => e.message).join('؛ ')}`); return }; if (canEdit) onEdit(plan.changes) }
  function clear(selection, order) { if (!canEdit) return; const changes = rows.slice(selection.row, selection.row + selection.rows).flatMap(r => order.slice(selection.col, selection.col + selection.cols).filter(c => c.editable).map(c => ({ id: r.id, key: c.prop, value: null }))); if (changes.length) onEdit(changes); else onNotice('بيانات العامل والخلايا المحسوبة محمية ولا تُمسح.') }
  return <div hidden={!active} className="space-y-3"><div className="flex flex-wrap gap-2 items-center" role="toolbar" aria-label="أدوات العرض التفصيلي"><button type="button" className="hr-btn" disabled={!canEdit || !canUndo} onClick={onUndo}>تراجع — Ctrl+Z</button><button type="button" className="hr-btn" disabled={!canEdit || !canRedo} onClick={onRedo}>إعادة — Ctrl+Y</button><div className="min-w-[240px] flex-1 rounded-[10px] border border-primary/12 bg-white px-3 py-2 text-[12px]" aria-live="polite"><b>{column?.title || 'الشريط الحسابي'}</b>{column?.computed && <span className="mx-3 font-mono text-primary-dark">ƒ = {column.definition.formula_display}</span>}{column?.identity && <span className="mx-3 text-text-light">هوية من النظام؛ افتح الملف المحاسبي لعرض السياق.</span>}{cell && <span className="mx-3" dir="ltr">{cell.v === null ? cell.m || 'لم يحدد' : formatValue(column.type, cell.v)}</span>}{!column && <span className="mx-3 text-text-light">اختر خلية لعرض معادلتها وقيمتها.</span>}</div></div><PayrollLegend columns={columns} canEdit={canEdit} /><PayrollGrid snapshot={{ rows }} columns={columns} totals={totals} sort={sort} canEdit={canEdit} controller={controller} active={active} columnWidths={widths} onWidthsChange={onWidthsChange} identityActionLabel="فتح الملف المحاسبي" onEditingChange={onEditingChange} onSort={onSort} onEditMeta={onOpenWorker} onFocusCell={setSelected} onUndo={() => canEdit && onUndo()} onRedo={() => canEdit && onRedo()} onClear={clear} onPaste={paste} onInvalidEdit={e => onNotice(`${e.title}: ${e.message}`)} announce={onNotice} /><p className="text-[11px] text-text-light">مسودات التحرير واللصق والتراجع لا تُحفظ تلقائيًا؛ استخدم «حفظ التغييرات». الخادم يعيد التحقق والحساب. إجماليات المسودات معاينة ضمن المجموعة المطابقة الأصلية للمرشحات.</p></div>
}
