-- Phase 6 preflight. READ ONLY. Run in phpMyAdmin before 01_apply.sql.
-- Explicit production target: alrowad_uni_rust.

SET @srp6_db := (SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name='alrowad_uni_rust');
SET @srp6_core := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN (
  'semester_offering_requests','course_offerings','course_offering_closure_requests','course_offering_closure_reviews',
  'student_course_registrations','registration_statuses','student_registration_requests','students','academic_years','semesters','users',
  'academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions',
  'student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events',
  'permissions','roles','role_permissions','user_roles','user_access_scopes','organizational_units'
));
SET @srp6_phase_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
  (table_name='semester_offering_requests' AND column_name IN ('semester_offering_request_id','course_offering_id','program_course_id','is_selected','minimum_enrollment','status','materialized_at')) OR
  (table_name='course_offerings' AND column_name IN ('course_offering_id','academic_year_id','semester_id','academic_program_id','status')) OR
  (table_name='student_course_registrations' AND column_name IN ('student_course_registration_id','student_id','course_offering_id','registration_status_id')) OR
  (table_name='course_offering_closure_requests' AND column_name IN ('course_offering_closure_request_id','course_offering_id','status','current_slot')) OR
  (table_name='academic_calendar_event_versions' AND column_name IN ('starts_at','ends_at','student_registration_ends_at','advisor_approval_ends_at','publication_status','is_enforcement'))
));
SET @srp6_signed := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND (
  (table_name='semester_offering_requests' AND column_name IN ('semester_offering_request_id','course_offering_id','program_course_id')) OR
  (table_name='course_offerings' AND column_name IN ('course_offering_id','academic_year_id','semester_id','academic_program_id')) OR
  (table_name='student_course_registrations' AND column_name IN ('student_course_registration_id','student_id','course_offering_id','registration_status_id')) OR
  (table_name='course_offering_closure_requests' AND column_name IN ('course_offering_closure_request_id','course_offering_id'))
));
SET @srp6_source_types := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code='course_registration');
SET @srp6_source_active := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code='course_registration' AND is_active=1);
SET @srp6_replacement_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` r JOIN `alrowad_uni_rust`.`academic_calendar_event_types` s ON s.event_type_code='course_registration' WHERE r.event_type_code='course_registration_replacement' AND (r.name_ar<>'استبدال المقررات الملغاة' OR r.name_en<>'Cancelled course replacement' OR r.event_type_kind<>s.event_type_kind OR r.default_is_enforcement<>s.default_is_enforcement OR r.is_active<>s.is_active));
SET @srp6_cancelled_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`registration_statuses` WHERE status_code='cancelled' AND (status_name<>'ملغى لعدم اكتمال الحد الأدنى' OR is_active<>1));
SET @srp6_permissions := (SELECT COUNT(DISTINCT permission_code) FROM `alrowad_uni_rust`.`permissions` WHERE is_active=1 AND permission_code IN ('course_offerings.semester_governance.view','course_offerings.semester_governance.manage','course_offerings.semester_governance.review_scientific','course_offerings.closure.view','course_offerings.closure.request','course_offerings.closure.review_scientific','course_offerings.closure.review_administrative','registration_requests.view','registration_requests.review'));
SET @srp6_pres := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`organizational_units` WHERE unit_code='PRES' AND is_active=1);
SET @srp6_targets := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN (
  'course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events'
));
SET @srp6_owned_targets := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN (
  'course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events'
) AND engine='InnoDB' AND table_comment LIKE 'Owned by semester-registration-minimum-cancellation-replacement-phase6%');
SET @srp6_required_target_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
  (table_name='course_offering_minimum_enrollment_reviews' AND column_name IN ('course_offering_minimum_enrollment_review_id','semester_offering_request_id','course_offering_id','academic_year_id','semester_id','minimum_enrollment_snapshot','enrolled_count_snapshot','finalization_deadline_at','finalized_at','status','dean_recommendation','dean_user_id','dean_notes','dean_recommended_at','scientific_decision','scientific_user_id','scientific_notes','scientific_decided_at','course_offering_closure_request_id','continued_at','cancelled_at','superseded_at','affected_registration_count','created_at','updated_at')) OR
  (table_name='course_offering_minimum_enrollment_events' AND column_name IN ('course_offering_minimum_enrollment_event_id','course_offering_minimum_enrollment_review_id','event_type','actor_user_id','notes','created_at')) OR
  (table_name='student_registration_replacement_requests' AND column_name IN ('student_registration_replacement_request_id','academic_calendar_event_id','student_id','academic_year_id','semester_id','status','submission_version','current_slot','student_notes','advisor_user_id','advisor_notes','first_submitted_at','last_submitted_at','reviewed_at','approved_at','expired_at','superseded_at','materialized_at','registered_hours_before_approval','replacement_hours_at_approval','projected_hours_at_approval','max_allowed_hours_at_approval','remaining_hours_after_approval','created_at','updated_at')) OR
  (table_name='student_registration_replacement_items' AND column_name IN ('student_registration_replacement_item_id','student_registration_replacement_request_id','source_minimum_enrollment_review_id','source_student_course_registration_id','replacement_course_offering_id','materialized_student_course_registration_id','source_consumed_slot','created_at','updated_at')) OR
  (table_name='student_registration_replacement_events' AND column_name IN ('student_registration_replacement_event_id','student_registration_replacement_request_id','event_type','actor_user_id','from_status','to_status','submission_version','notes','created_at'))
));
SET @srp6_expected_target_columns := (25*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews')) + (6*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events')) + (25*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests')) + (9*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items')) + (9*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events'));
SET @srp6_target_pk := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name IN ('course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events') AND constraint_type='PRIMARY KEY');
SET @srp6_target_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_type='CHECK' AND constraint_name IN ('chk_comer_snapshots','chk_comer_status','chk_comer_dean','chk_comer_dean_status','chk_comer_scientific','chk_comer_terminal','chk_comee_type','chk_srrpr_status','chk_srrpr_version','chk_srrpr_current','chk_srrpr_submission','chk_srrpr_return','chk_srrpr_terminal','chk_srrpr_snapshot','chk_srrpi_consumed','chk_srrpe_type'));
SET @srp6_expected_target_checks := (6*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews')) + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events') + (7*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests')) + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items') + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events');
SET @srp6_target_fks := (SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_comer_semester_request','fk_comer_offering','fk_comer_year','fk_comer_semester','fk_comer_dean','fk_comer_scientific','fk_comer_closure','fk_comee_review','fk_comee_actor','fk_srrpr_event','fk_srrpr_student','fk_srrpr_year','fk_srrpr_semester','fk_srrpr_advisor','fk_srrpi_request','fk_srrpi_review','fk_srrpi_source','fk_srrpi_target','fk_srrpi_materialized','fk_srrpe_request','fk_srrpe_actor') AND update_rule='RESTRICT' AND delete_rule='RESTRICT');
SET @srp6_expected_target_fks := (7*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews')) + (2*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events')) + (5*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests')) + (5*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items')) + (2*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events'));
SET @srp6_target_uniques := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 GROUP BY table_name,index_name) i WHERE (table_name='course_offering_minimum_enrollment_reviews' AND ((index_name='uq_comer_request' AND cols='semester_offering_request_id') OR (index_name='uq_comer_offering' AND cols='course_offering_id') OR (index_name='uq_comer_closure' AND cols='course_offering_closure_request_id'))) OR (table_name='student_registration_replacement_requests' AND index_name='uq_srrpr_current' AND cols='student_id,academic_year_id,semester_id,current_slot') OR (table_name='student_registration_replacement_items' AND ((index_name='uq_srrpi_source_in_request' AND cols='student_registration_replacement_request_id,source_student_course_registration_id') OR (index_name='uq_srrpi_target_in_request' AND cols='student_registration_replacement_request_id,replacement_course_offering_id') OR (index_name='uq_srrpi_source_consumed' AND cols='source_student_course_registration_id,source_consumed_slot'))));
SET @srp6_expected_target_uniques := (3*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews')) + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests') + (3*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items'));
SET @srp6_target_compatible := (@srp6_targets=0 OR (@srp6_owned_targets=@srp6_targets AND @srp6_required_target_columns=@srp6_expected_target_columns AND @srp6_target_pk=@srp6_targets AND @srp6_target_checks=@srp6_expected_target_checks AND @srp6_target_fks=@srp6_expected_target_fks AND @srp6_target_uniques=@srp6_expected_target_uniques));
SET @srp6_ready := (@srp6_db=1 AND @srp6_core=23 AND @srp6_phase_columns=26 AND @srp6_signed=13 AND @srp6_source_types=1 AND @srp6_source_active=1 AND @srp6_permissions=9 AND @srp6_pres=1 AND @srp6_replacement_conflicts=0 AND @srp6_cancelled_conflicts=0 AND @srp6_target_compatible=1);

SELECT 'DATABASE_AND_PHASES' report_section, IF(@srp6_db=1 AND @srp6_core=23 AND @srp6_phase_columns=26 AND @srp6_signed=13,'PASS','FAIL') result, CONCAT('core=',@srp6_core,'/23; columns=',@srp6_phase_columns,'/26; signed_keys=',@srp6_signed,'/13') detail;
SELECT 'SOURCE_EVENT_METADATA' report_section, IF(@srp6_source_types=1 AND @srp6_source_active=1,'PASS','FAIL') result, event_type_kind,default_is_enforcement,is_active FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code='course_registration';
SELECT 'REFERENCE_CONFLICTS' report_section, IF(@srp6_replacement_conflicts=0 AND @srp6_cancelled_conflicts=0,'PASS','FAIL') result, CONCAT('replacement=',@srp6_replacement_conflicts,'; cancelled=',@srp6_cancelled_conflicts) detail;
SELECT 'RBAC_AND_SCOPE' report_section,IF(@srp6_permissions=9 AND @srp6_pres=1,'PASS','FAIL') result,CONCAT('existing_permissions=',@srp6_permissions,'/9; PRES=',@srp6_pres,'/1') detail;
SELECT 'PHASE6_OBJECTS' report_section, IF(@srp6_target_compatible=1,'PASS','FAIL') result, CONCAT('tables=',@srp6_targets,'/5; owned=',@srp6_owned_targets,'; required_columns=',@srp6_required_target_columns,'/',@srp6_expected_target_columns,'; pk=',@srp6_target_pk,'/',@srp6_targets,'; checks=',@srp6_target_checks,'/',@srp6_expected_target_checks,'; fks=',@srp6_target_fks,'/',@srp6_expected_target_fks,'; uniques=',@srp6_target_uniques,'/',@srp6_expected_target_uniques) detail;
SELECT 'OVERALL' report_section, IF(@srp6_ready,'READY','BLOCKED') result;
