-- Guarded, rerunnable MariaDB 10.11 apply. Run only after READY. No backfill.
USE `alrowad_uni_rust`;
SET @srp6_before := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events'));
SET @srp6_core := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('semester_offering_requests','course_offerings','course_offering_closure_requests','course_offering_closure_reviews','student_course_registrations','registration_statuses','student_registration_requests','students','academic_years','semesters','users','academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions','student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events','permissions','roles','role_permissions','user_roles','user_access_scopes','organizational_units'));
SET @srp6_source := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code='course_registration' AND is_active=1);
SET @srp6_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` r JOIN `alrowad_uni_rust`.`academic_calendar_event_types` s ON s.event_type_code='course_registration' WHERE r.event_type_code='course_registration_replacement' AND (r.name_ar<>'استبدال المقررات الملغاة' OR r.name_en<>'Cancelled course replacement' OR r.event_type_kind<>s.event_type_kind OR r.default_is_enforcement<>s.default_is_enforcement OR r.is_active<>s.is_active));
SET @srp6_cancelled_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`registration_statuses` WHERE status_code='cancelled' AND (status_name<>'ملغى لعدم اكتمال الحد الأدنى' OR is_active<>1));
SET @srp6_permissions := (SELECT COUNT(DISTINCT permission_code) FROM `alrowad_uni_rust`.`permissions` WHERE is_active=1 AND permission_code IN ('course_offerings.semester_governance.view','course_offerings.semester_governance.manage','course_offerings.semester_governance.review_scientific','course_offerings.closure.view','course_offerings.closure.request','course_offerings.closure.review_scientific','course_offerings.closure.review_administrative','registration_requests.view','registration_requests.review'));
SET @srp6_pres := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`organizational_units` WHERE unit_code='PRES' AND is_active=1);
SET @srp6_existing_owned := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events') AND engine='InnoDB' AND table_comment LIKE 'Owned by semester-registration-minimum-cancellation-replacement-phase6%');
SET @srp6_existing_required_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='course_offering_minimum_enrollment_reviews' AND column_name IN ('course_offering_minimum_enrollment_review_id','semester_offering_request_id','course_offering_id','academic_year_id','semester_id','minimum_enrollment_snapshot','enrolled_count_snapshot','finalization_deadline_at','finalized_at','status','dean_recommendation','dean_user_id','dean_notes','dean_recommended_at','scientific_decision','scientific_user_id','scientific_notes','scientific_decided_at','course_offering_closure_request_id','continued_at','cancelled_at','superseded_at','affected_registration_count','created_at','updated_at')) OR (table_name='course_offering_minimum_enrollment_events' AND column_name IN ('course_offering_minimum_enrollment_event_id','course_offering_minimum_enrollment_review_id','event_type','actor_user_id','notes','created_at')) OR (table_name='student_registration_replacement_requests' AND column_name IN ('student_registration_replacement_request_id','academic_calendar_event_id','student_id','academic_year_id','semester_id','status','submission_version','current_slot','student_notes','advisor_user_id','advisor_notes','first_submitted_at','last_submitted_at','reviewed_at','approved_at','expired_at','superseded_at','materialized_at','registered_hours_before_approval','replacement_hours_at_approval','projected_hours_at_approval','max_allowed_hours_at_approval','remaining_hours_after_approval','created_at','updated_at')) OR (table_name='student_registration_replacement_items' AND column_name IN ('student_registration_replacement_item_id','student_registration_replacement_request_id','source_minimum_enrollment_review_id','source_student_course_registration_id','replacement_course_offering_id','materialized_student_course_registration_id','source_consumed_slot','created_at','updated_at')) OR (table_name='student_registration_replacement_events' AND column_name IN ('student_registration_replacement_event_id','student_registration_replacement_request_id','event_type','actor_user_id','from_status','to_status','submission_version','notes','created_at'))));
SET @srp6_existing_expected_columns := 25*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews') + 6*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events') + 25*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests') + 9*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items') + 9*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events');
SET @srp6_existing_pk := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name IN ('course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events') AND constraint_type='PRIMARY KEY');
SET @srp6_existing_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_type='CHECK' AND constraint_name IN ('chk_comer_snapshots','chk_comer_status','chk_comer_dean','chk_comer_dean_status','chk_comer_scientific','chk_comer_terminal','chk_comee_type','chk_srrpr_status','chk_srrpr_version','chk_srrpr_current','chk_srrpr_submission','chk_srrpr_return','chk_srrpr_terminal','chk_srrpr_snapshot','chk_srrpi_consumed','chk_srrpe_type'));
SET @srp6_existing_expected_checks := 6*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews') + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events') + 7*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests') + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items') + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events');
SET @srp6_existing_fks := (SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_comer_semester_request','fk_comer_offering','fk_comer_year','fk_comer_semester','fk_comer_dean','fk_comer_scientific','fk_comer_closure','fk_comee_review','fk_comee_actor','fk_srrpr_event','fk_srrpr_student','fk_srrpr_year','fk_srrpr_semester','fk_srrpr_advisor','fk_srrpi_request','fk_srrpi_review','fk_srrpi_source','fk_srrpi_target','fk_srrpi_materialized','fk_srrpe_request','fk_srrpe_actor') AND update_rule='RESTRICT' AND delete_rule='RESTRICT');
SET @srp6_existing_expected_fks := 7*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews') + 2*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_events') + 5*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests') + 5*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items') + 2*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_events');
SET @srp6_existing_uniques := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 GROUP BY table_name,index_name) i WHERE (table_name='course_offering_minimum_enrollment_reviews' AND ((index_name='uq_comer_request' AND cols='semester_offering_request_id') OR (index_name='uq_comer_offering' AND cols='course_offering_id') OR (index_name='uq_comer_closure' AND cols='course_offering_closure_request_id'))) OR (table_name='student_registration_replacement_requests' AND index_name='uq_srrpr_current' AND cols='student_id,academic_year_id,semester_id,current_slot') OR (table_name='student_registration_replacement_items' AND ((index_name='uq_srrpi_source_in_request' AND cols='student_registration_replacement_request_id,source_student_course_registration_id') OR (index_name='uq_srrpi_target_in_request' AND cols='student_registration_replacement_request_id,replacement_course_offering_id') OR (index_name='uq_srrpi_source_consumed' AND cols='source_student_course_registration_id,source_consumed_slot'))));
SET @srp6_existing_expected_uniques := 3*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_minimum_enrollment_reviews') + (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_requests') + 3*(SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_replacement_items');
SET @srp6_existing_compatible := (@srp6_before=0 OR (@srp6_existing_owned=@srp6_before AND @srp6_existing_required_columns=@srp6_existing_expected_columns AND @srp6_existing_pk=@srp6_before AND @srp6_existing_checks=@srp6_existing_expected_checks AND @srp6_existing_fks=@srp6_existing_expected_fks AND @srp6_existing_uniques=@srp6_existing_expected_uniques));
SET @srp6_ready := (@srp6_core=23 AND @srp6_source=1 AND @srp6_permissions=9 AND @srp6_pres=1 AND @srp6_conflicts=0 AND @srp6_cancelled_conflicts=0 AND @srp6_existing_compatible=1);

SET @srp6_sql := IF(@srp6_ready,
'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`course_offering_minimum_enrollment_reviews` (
 `course_offering_minimum_enrollment_review_id` INT NOT NULL AUTO_INCREMENT, `semester_offering_request_id` INT NOT NULL, `course_offering_id` INT NOT NULL, `academic_year_id` INT NOT NULL, `semester_id` INT NOT NULL,
 `minimum_enrollment_snapshot` INT NOT NULL, `enrolled_count_snapshot` INT NOT NULL, `finalization_deadline_at` DATETIME NOT NULL, `finalized_at` DATETIME NOT NULL,
 `status` VARCHAR(32) NOT NULL, `dean_recommendation` VARCHAR(16) NULL, `dean_user_id` INT NULL, `dean_notes` TEXT NULL, `dean_recommended_at` DATETIME NULL,
 `scientific_decision` VARCHAR(16) NULL, `scientific_user_id` INT NULL, `scientific_notes` TEXT NULL, `scientific_decided_at` DATETIME NULL,
 `course_offering_closure_request_id` INT NULL, `continued_at` DATETIME NULL, `cancelled_at` DATETIME NULL, `superseded_at` DATETIME NULL, `affected_registration_count` INT NULL,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`course_offering_minimum_enrollment_review_id`), UNIQUE KEY `uq_comer_request` (`semester_offering_request_id`), UNIQUE KEY `uq_comer_offering` (`course_offering_id`), UNIQUE KEY `uq_comer_closure` (`course_offering_closure_request_id`),
 KEY `idx_comer_term_status` (`academic_year_id`,`semester_id`,`status`), KEY `idx_comer_dean` (`dean_user_id`), KEY `idx_comer_scientific` (`scientific_user_id`),
 CONSTRAINT `chk_comer_snapshots` CHECK (`minimum_enrollment_snapshot`>0 AND `enrolled_count_snapshot`>=0 AND (`affected_registration_count` IS NULL OR `affected_registration_count`>=0)),
 CONSTRAINT `chk_comer_status` CHECK (`status` IN (''satisfied'',''under_minimum'',''dean_recommended'',''continued_exceptionally'',''closure_pending'',''cancelled'',''superseded'')),
 CONSTRAINT `chk_comer_dean` CHECK ((`dean_recommendation` IS NULL AND `dean_user_id` IS NULL AND `dean_notes` IS NULL AND `dean_recommended_at` IS NULL) OR (`dean_recommendation` IN (''continue'',''cancel'') AND `dean_user_id` IS NOT NULL AND NULLIF(TRIM(`dean_notes`),'''') IS NOT NULL AND `dean_recommended_at` IS NOT NULL)),
 CONSTRAINT `chk_comer_dean_status` CHECK (`status`<>''dean_recommended'' OR `dean_recommendation` IS NOT NULL),
 CONSTRAINT `chk_comer_scientific` CHECK ((`scientific_decision` IS NULL AND `scientific_user_id` IS NULL AND `scientific_notes` IS NULL AND `scientific_decided_at` IS NULL) OR (`scientific_decision` IN (''continue'',''cancel'') AND `scientific_user_id` IS NOT NULL AND NULLIF(TRIM(`scientific_notes`),'''') IS NOT NULL AND `scientific_decided_at` IS NOT NULL)),
 CONSTRAINT `chk_comer_terminal` CHECK ((`status`<>''continued_exceptionally'' OR (`scientific_decision`=''continue'' AND `continued_at` IS NOT NULL)) AND (`status`<>''closure_pending'' OR (`scientific_decision`=''cancel'' AND `course_offering_closure_request_id` IS NOT NULL)) AND (`status`<>''cancelled'' OR (`scientific_decision`=''cancel'' AND `course_offering_closure_request_id` IS NOT NULL AND `cancelled_at` IS NOT NULL AND `affected_registration_count` IS NOT NULL)) AND (`status`<>''superseded'' OR `superseded_at` IS NOT NULL)),
 CONSTRAINT `fk_comer_semester_request` FOREIGN KEY (`semester_offering_request_id`) REFERENCES `alrowad_uni_rust`.`semester_offering_requests` (`semester_offering_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_offering` FOREIGN KEY (`course_offering_id`) REFERENCES `alrowad_uni_rust`.`course_offerings` (`course_offering_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_year` FOREIGN KEY (`academic_year_id`) REFERENCES `alrowad_uni_rust`.`academic_years` (`academic_year_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_semester` FOREIGN KEY (`semester_id`) REFERENCES `alrowad_uni_rust`.`semesters` (`semester_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_dean` FOREIGN KEY (`dean_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_scientific` FOREIGN KEY (`scientific_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comer_closure` FOREIGN KEY (`course_offering_closure_request_id`) REFERENCES `alrowad_uni_rust`.`course_offering_closure_requests` (`course_offering_closure_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-minimum-cancellation-replacement-phase6; immutable minimum review''',
'SELECT ''APPLY_GUARD'' report_section,''BLOCKED'' result'); PREPARE srp6_stmt FROM @srp6_sql; EXECUTE srp6_stmt; DEALLOCATE PREPARE srp6_stmt;

SET @srp6_sql := IF(@srp6_ready,
'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`course_offering_minimum_enrollment_events` (
 `course_offering_minimum_enrollment_event_id` INT NOT NULL AUTO_INCREMENT, `course_offering_minimum_enrollment_review_id` INT NOT NULL, `event_type` VARCHAR(64) NOT NULL, `actor_user_id` INT NULL, `notes` TEXT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`course_offering_minimum_enrollment_event_id`), KEY `idx_comee_history` (`course_offering_minimum_enrollment_review_id`,`created_at`), KEY `idx_comee_actor` (`actor_user_id`),
 CONSTRAINT `chk_comee_type` CHECK (`event_type` IN (''finalized_satisfied'',''finalized_under_minimum'',''dean_recommended_continue'',''dean_recommended_cancel'',''dean_recommendation_updated'',''scientific_continued_exceptionally'',''closure_linked'',''cancellation_materialized'',''superseded_external_closure'')),
 CONSTRAINT `fk_comee_review` FOREIGN KEY (`course_offering_minimum_enrollment_review_id`) REFERENCES `alrowad_uni_rust`.`course_offering_minimum_enrollment_reviews` (`course_offering_minimum_enrollment_review_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_comee_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-minimum-cancellation-replacement-phase6; append-only minimum history''',
'SELECT ''MINIMUM_EVENTS'' report_section,''SKIPPED'' result'); PREPARE srp6_stmt FROM @srp6_sql; EXECUTE srp6_stmt; DEALLOCATE PREPARE srp6_stmt;

SET @srp6_sql := IF(@srp6_ready,
'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`student_registration_replacement_requests` (
 `student_registration_replacement_request_id` INT NOT NULL AUTO_INCREMENT, `academic_calendar_event_id` INT NOT NULL, `student_id` INT NOT NULL, `academic_year_id` INT NOT NULL, `semester_id` INT NOT NULL,
 `status` VARCHAR(32) NOT NULL DEFAULT ''draft'', `submission_version` INT NOT NULL DEFAULT 0, `current_slot` TINYINT NULL DEFAULT 1, `student_notes` TEXT NULL, `advisor_user_id` INT NULL, `advisor_notes` TEXT NULL,
 `first_submitted_at` DATETIME NULL, `last_submitted_at` DATETIME NULL, `reviewed_at` DATETIME NULL, `approved_at` DATETIME NULL, `expired_at` DATETIME NULL, `superseded_at` DATETIME NULL, `materialized_at` DATETIME NULL,
 `registered_hours_before_approval` INT NULL, `replacement_hours_at_approval` INT NULL, `projected_hours_at_approval` INT NULL, `max_allowed_hours_at_approval` INT NULL, `remaining_hours_after_approval` INT NULL,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_replacement_request_id`), UNIQUE KEY `uq_srrpr_current` (`student_id`,`academic_year_id`,`semester_id`,`current_slot`), KEY `idx_srrpr_queue` (`status`,`last_submitted_at`,`student_registration_replacement_request_id`), KEY `idx_srrpr_event` (`academic_calendar_event_id`), KEY `idx_srrpr_advisor` (`advisor_user_id`),
 CONSTRAINT `chk_srrpr_status` CHECK (`status` IN (''draft'',''submitted'',''returned'',''approved'',''expired'',''superseded'')), CONSTRAINT `chk_srrpr_version` CHECK (`submission_version`>=0),
 CONSTRAINT `chk_srrpr_current` CHECK ((`status` IN (''draft'',''submitted'',''returned'') AND `current_slot`=1) OR (`status` IN (''approved'',''expired'',''superseded'') AND `current_slot` IS NULL)),
 CONSTRAINT `chk_srrpr_submission` CHECK (`status` NOT IN (''submitted'',''returned'',''approved'') OR (`submission_version`>0 AND `first_submitted_at` IS NOT NULL AND `last_submitted_at` IS NOT NULL)),
 CONSTRAINT `chk_srrpr_return` CHECK (`status`<>''returned'' OR (`advisor_user_id` IS NOT NULL AND `reviewed_at` IS NOT NULL AND NULLIF(TRIM(`advisor_notes`),'''') IS NOT NULL)),
 CONSTRAINT `chk_srrpr_terminal` CHECK ((`status`<>''approved'' OR (`advisor_user_id` IS NOT NULL AND `reviewed_at` IS NOT NULL AND `approved_at` IS NOT NULL AND `materialized_at` IS NOT NULL)) AND (`status`<>''expired'' OR `expired_at` IS NOT NULL) AND (`status`<>''superseded'' OR `superseded_at` IS NOT NULL)),
 CONSTRAINT `chk_srrpr_snapshot` CHECK ((`status`=''approved'' AND `registered_hours_before_approval` IS NOT NULL AND `replacement_hours_at_approval` IS NOT NULL AND `projected_hours_at_approval` IS NOT NULL AND `max_allowed_hours_at_approval` IS NOT NULL AND `remaining_hours_after_approval` IS NOT NULL) OR (`status`<>''approved'' AND `registered_hours_before_approval` IS NULL AND `replacement_hours_at_approval` IS NULL AND `projected_hours_at_approval` IS NULL AND `max_allowed_hours_at_approval` IS NULL AND `remaining_hours_after_approval` IS NULL)),
 CONSTRAINT `fk_srrpr_event` FOREIGN KEY (`academic_calendar_event_id`) REFERENCES `alrowad_uni_rust`.`academic_calendar_events` (`academic_calendar_event_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpr_student` FOREIGN KEY (`student_id`) REFERENCES `alrowad_uni_rust`.`students` (`student_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpr_year` FOREIGN KEY (`academic_year_id`) REFERENCES `alrowad_uni_rust`.`academic_years` (`academic_year_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpr_semester` FOREIGN KEY (`semester_id`) REFERENCES `alrowad_uni_rust`.`semesters` (`semester_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpr_advisor` FOREIGN KEY (`advisor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-minimum-cancellation-replacement-phase6; replacement request''',
'SELECT ''REPLACEMENT_REQUESTS'' report_section,''SKIPPED'' result'); PREPARE srp6_stmt FROM @srp6_sql; EXECUTE srp6_stmt; DEALLOCATE PREPARE srp6_stmt;

SET @srp6_sql := IF(@srp6_ready,
'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`student_registration_replacement_items` (
 `student_registration_replacement_item_id` INT NOT NULL AUTO_INCREMENT, `student_registration_replacement_request_id` INT NOT NULL, `source_minimum_enrollment_review_id` INT NOT NULL, `source_student_course_registration_id` INT NOT NULL, `replacement_course_offering_id` INT NOT NULL, `materialized_student_course_registration_id` INT NULL, `source_consumed_slot` TINYINT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_replacement_item_id`), UNIQUE KEY `uq_srrpi_source_in_request` (`student_registration_replacement_request_id`,`source_student_course_registration_id`), UNIQUE KEY `uq_srrpi_target_in_request` (`student_registration_replacement_request_id`,`replacement_course_offering_id`), UNIQUE KEY `uq_srrpi_source_consumed` (`source_student_course_registration_id`,`source_consumed_slot`), KEY `idx_srrpi_review` (`source_minimum_enrollment_review_id`), KEY `idx_srrpi_materialized` (`materialized_student_course_registration_id`),
 CONSTRAINT `chk_srrpi_consumed` CHECK ((`source_consumed_slot` IS NULL AND `materialized_student_course_registration_id` IS NULL) OR (`source_consumed_slot`=1 AND `materialized_student_course_registration_id` IS NOT NULL)),
 CONSTRAINT `fk_srrpi_request` FOREIGN KEY (`student_registration_replacement_request_id`) REFERENCES `alrowad_uni_rust`.`student_registration_replacement_requests` (`student_registration_replacement_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpi_review` FOREIGN KEY (`source_minimum_enrollment_review_id`) REFERENCES `alrowad_uni_rust`.`course_offering_minimum_enrollment_reviews` (`course_offering_minimum_enrollment_review_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpi_source` FOREIGN KEY (`source_student_course_registration_id`) REFERENCES `alrowad_uni_rust`.`student_course_registrations` (`student_course_registration_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpi_target` FOREIGN KEY (`replacement_course_offering_id`) REFERENCES `alrowad_uni_rust`.`course_offerings` (`course_offering_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpi_materialized` FOREIGN KEY (`materialized_student_course_registration_id`) REFERENCES `alrowad_uni_rust`.`student_course_registrations` (`student_course_registration_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-minimum-cancellation-replacement-phase6; historical source references and one-time consumption''',
'SELECT ''REPLACEMENT_ITEMS'' report_section,''SKIPPED'' result'); PREPARE srp6_stmt FROM @srp6_sql; EXECUTE srp6_stmt; DEALLOCATE PREPARE srp6_stmt;

SET @srp6_sql := IF(@srp6_ready,
'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`student_registration_replacement_events` (
 `student_registration_replacement_event_id` INT NOT NULL AUTO_INCREMENT, `student_registration_replacement_request_id` INT NOT NULL, `event_type` VARCHAR(48) NOT NULL, `actor_user_id` INT NULL, `from_status` VARCHAR(32) NULL, `to_status` VARCHAR(32) NULL, `submission_version` INT NULL, `notes` TEXT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_replacement_event_id`), KEY `idx_srrpe_history` (`student_registration_replacement_request_id`,`created_at`), KEY `idx_srrpe_actor` (`actor_user_id`),
 CONSTRAINT `chk_srrpe_type` CHECK (`event_type` IN (''draft_created'',''item_added'',''item_updated'',''item_removed'',''submitted'',''resubmitted'',''returned'',''approved'',''materialized'',''expired'',''superseded'')),
 CONSTRAINT `fk_srrpe_request` FOREIGN KEY (`student_registration_replacement_request_id`) REFERENCES `alrowad_uni_rust`.`student_registration_replacement_requests` (`student_registration_replacement_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srrpe_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-minimum-cancellation-replacement-phase6; append-only replacement history''',
'SELECT ''REPLACEMENT_EVENTS'' report_section,''SKIPPED'' result'); PREPARE srp6_stmt FROM @srp6_sql; EXECUTE srp6_stmt; DEALLOCATE PREPARE srp6_stmt;

START TRANSACTION;
INSERT INTO `alrowad_uni_rust`.`registration_statuses` (`status_code`,`status_name`,`is_active`,`created_at`,`updated_at`)
SELECT 'cancelled','ملغى لعدم اكتمال الحد الأدنى',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM DUAL
WHERE @srp6_ready AND NOT EXISTS (SELECT 1 FROM `alrowad_uni_rust`.`registration_statuses` WHERE status_code='cancelled');
INSERT INTO `alrowad_uni_rust`.`academic_calendar_event_types` (`event_type_code`,`name_ar`,`name_en`,`event_type_kind`,`default_is_enforcement`,`is_active`,`created_at`,`updated_at`)
SELECT 'course_registration_replacement','استبدال المقررات الملغاة','Cancelled course replacement',s.event_type_kind,s.default_is_enforcement,s.is_active,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
FROM `alrowad_uni_rust`.`academic_calendar_event_types` s
WHERE @srp6_ready AND s.event_type_code='course_registration' AND NOT EXISTS (SELECT 1 FROM `alrowad_uni_rust`.`academic_calendar_event_types` r WHERE r.event_type_code='course_registration_replacement');
COMMIT;
SET @srp6_after := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events'));
SELECT 'OVERALL' report_section,IF(NOT @srp6_ready,'BLOCKED',IF(@srp6_after<>5,'BLOCKED',IF(@srp6_before=5,'ALREADY_APPLIED',IF(@srp6_before=0,'APPLIED','RESUMED')))) result;
