-- Phase 4 read-only preflight. Run in phpMyAdmin against alrowad_uni_rust.
SET @phase3_tables := (SELECT COUNT(*)=2 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events') AND engine='InnoDB');
SET @phase3_columns := (SELECT COUNT(*)=22 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_theoretical_deferrals' AND column_name IN ('supplementary_exam_theoretical_deferral_id','supplementary_exam_offering_id','student_course_registration_id','status','current_slot','declared_by_user_id','declared_at','cancelled_by_user_id','cancelled_at','cancellation_reason','superseded_at','supersede_reason','created_at','updated_at')) OR (table_name='supplementary_exam_theoretical_deferral_events' AND column_name IN ('supplementary_exam_theoretical_deferral_event_id','supplementary_exam_theoretical_deferral_id','event_type','from_status','to_status','actor_user_id','notes','created_at'))));
SET @phase123_tables := (SELECT COUNT(*)=11 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_periods','supplementary_exam_period_events','supplementary_exam_offerings','supplementary_exam_offering_sources','supplementary_exam_offering_events','supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events','students','student_course_registrations','users','role_permissions'));
SET @phase3_rbac := (SELECT COUNT(DISTINCT CONCAT(r.role_code,':',p.permission_code))=5 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id AND r.is_active=1 JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id AND p.is_active=1 WHERE (p.permission_code='supplementary_exams.deferrals.self' AND r.role_code='student') OR (p.permission_code='supplementary_exams.eligibility.view' AND r.role_code IN ('dean','registration_officer','exam_officer','vice_president_scientific')));
SET @phase3_ready := @phase3_tables AND @phase3_columns AND @phase123_tables AND @phase3_rbac;
SET @reg_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registrations');
SET @reg_contract := (SELECT COUNT(*)=16 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_id','student_course_registration_id','status','current_slot','eligibility_reason','registration_channel','registered_by_user_id','registered_at','cancelled_by_user_id','cancelled_at','cancellation_reason','eligibility_checked_at','created_at','updated_at'));
SET @event_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registration_events');
SET @event_contract := (SELECT COUNT(*)=8 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registration_events' AND column_name IN ('supplementary_exam_registration_event_id','supplementary_exam_registration_id','event_type','from_status','to_status','actor_user_id','notes','created_at'));
SET @target_schema_safe := (@reg_exists=0 OR @reg_contract) AND (@event_exists=0 OR @event_contract);
SET @rbac_safe := (SELECT COUNT(*)=5 FROM `alrowad_uni_rust`.`roles` WHERE role_code IN ('student','registration_officer','exam_officer','dean','vice_president_scientific') AND is_active=1) AND (SELECT COUNT(*)=1 FROM `alrowad_uni_rust`.`system_modules` WHERE module_code='exams' AND is_active=1);
SET @overall := IF(@phase3_ready AND @target_schema_safe AND @rbac_safe,'READY','BLOCKED');
SET @blocker_code := IF(NOT @phase3_ready,'PHASE3_NOT_DEPLOYED',IF(NOT @target_schema_safe,'TARGET_SCHEMA_CONFLICT',IF(NOT @rbac_safe,'RBAC_CONFLICT',NULL)));
SELECT 'OVERALL' AS report_section,@overall AS result,@blocker_code AS blocker_code,@phase3_ready AS phase3_ready,@target_schema_safe AS target_schema_safe,@rbac_safe AS rbac_safe;
