-- Independently guarded, resumable Phase 4 apply.
SET @phase3_ready := (SELECT COUNT(*)=2 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events')) AND (SELECT COUNT(*)=22 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_theoretical_deferrals' AND column_name IN ('supplementary_exam_theoretical_deferral_id','supplementary_exam_offering_id','student_course_registration_id','status','current_slot','declared_by_user_id','declared_at','cancelled_by_user_id','cancelled_at','cancellation_reason','superseded_at','supersede_reason','created_at','updated_at')) OR (table_name='supplementary_exam_theoretical_deferral_events' AND column_name IN ('supplementary_exam_theoretical_deferral_event_id','supplementary_exam_theoretical_deferral_id','event_type','from_status','to_status','actor_user_id','notes','created_at'))));
SET @reg_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registrations');
SET @reg_compatible := @reg_exists=1 AND (SELECT COUNT(*)=16 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_id','student_course_registration_id','status','current_slot','eligibility_reason','registration_channel','registered_by_user_id','registered_at','cancelled_by_user_id','cancelled_at','cancellation_reason','eligibility_checked_at','created_at','updated_at'));
SET @event_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registration_events');
SET @event_compatible := @event_exists=1 AND (SELECT COUNT(*)=8 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registration_events');
SET @safe := @phase3_ready AND (@reg_exists=0 OR @reg_compatible) AND (@event_exists=0 OR @event_compatible);
SET @sql := IF(@safe AND @reg_exists=0,"CREATE TABLE `alrowad_uni_rust`.`supplementary_exam_registrations` (`supplementary_exam_registration_id` INT NOT NULL AUTO_INCREMENT,`supplementary_exam_offering_id` INT NOT NULL,`student_id` INT NOT NULL,`student_course_registration_id` INT NOT NULL,`status` VARCHAR(16) NOT NULL,`current_slot` TINYINT NULL,`eligibility_reason` VARCHAR(40) NOT NULL,`registration_channel` VARCHAR(24) NOT NULL,`registered_by_user_id` INT NOT NULL,`registered_at` DATETIME NOT NULL,`cancelled_by_user_id` INT NULL,`cancelled_at` DATETIME NULL,`cancellation_reason` TEXT NULL,`eligibility_checked_at` DATETIME NOT NULL,`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`supplementary_exam_registration_id`),UNIQUE KEY `uq_ser_source` (`supplementary_exam_offering_id`,`student_course_registration_id`),UNIQUE KEY `uq_ser_current` (`supplementary_exam_offering_id`,`student_id`,`current_slot`),KEY `ix_ser_student_current` (`student_id`,`current_slot`),KEY `ix_ser_offering_status` (`supplementary_exam_offering_id`,`status`),KEY `ix_ser_registered_by` (`registered_by_user_id`),KEY `ix_ser_cancelled_by` (`cancelled_by_user_id`),CONSTRAINT `fk_ser_offering` FOREIGN KEY (`supplementary_exam_offering_id`) REFERENCES `alrowad_uni_rust`.`supplementary_exam_offerings` (`supplementary_exam_offering_id`),CONSTRAINT `fk_ser_student` FOREIGN KEY (`student_id`) REFERENCES `alrowad_uni_rust`.`students` (`student_id`),CONSTRAINT `fk_ser_source` FOREIGN KEY (`student_course_registration_id`) REFERENCES `alrowad_uni_rust`.`student_course_registrations` (`student_course_registration_id`),CONSTRAINT `fk_ser_registered_by` FOREIGN KEY (`registered_by_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`),CONSTRAINT `fk_ser_cancelled_by` FOREIGN KEY (`cancelled_by_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`)) ENGINE=InnoDB COMMENT='[phase4-supplementary-exam-registration] official list'","SELECT 'REGISTRATIONS_ADOPTED_OR_BLOCKED'");PREPARE s FROM @sql;EXECUTE s;DEALLOCATE PREPARE s;
SET @reg_now := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_registrations');
SET @sql := IF(@safe AND @reg_now=1 AND @event_exists=0,"CREATE TABLE `alrowad_uni_rust`.`supplementary_exam_registration_events` (`supplementary_exam_registration_event_id` INT NOT NULL AUTO_INCREMENT,`supplementary_exam_registration_id` INT NOT NULL,`event_type` VARCHAR(24) NOT NULL,`from_status` VARCHAR(16) NULL,`to_status` VARCHAR(16) NOT NULL,`actor_user_id` INT NOT NULL,`notes` TEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`supplementary_exam_registration_event_id`),KEY `ix_sere_history` (`supplementary_exam_registration_id`,`created_at`),KEY `ix_sere_actor` (`actor_user_id`),CONSTRAINT `fk_sere_registration` FOREIGN KEY (`supplementary_exam_registration_id`) REFERENCES `alrowad_uni_rust`.`supplementary_exam_registrations` (`supplementary_exam_registration_id`),CONSTRAINT `fk_sere_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`)) ENGINE=InnoDB COMMENT='[phase4-supplementary-exam-registration] immutable events'","SELECT 'EVENTS_ADOPTED_OR_BLOCKED'");PREPARE s FROM @sql;EXECUTE s;DEALLOCATE PREPARE s;
START TRANSACTION;
INSERT INTO `alrowad_uni_rust`.`permissions` (module_id,permission_code,permission_name,description,is_active,created_at,updated_at) SELECT m.module_id,x.code,x.name,'[phase4-supplementary-exam-registration]',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM `alrowad_uni_rust`.`system_modules` m JOIN (SELECT 'supplementary_exams.registrations.view' code,'View supplementary registrations' name UNION ALL SELECT 'supplementary_exams.registrations.self','Self supplementary registration' UNION ALL SELECT 'supplementary_exams.registrations.manage','Manage supplementary registrations' UNION ALL SELECT 'supplementary_exams.registrations.window','Manage supplementary registration window') x WHERE @safe AND m.module_code='exams' AND m.is_active=1 AND NOT EXISTS(SELECT 1 FROM `alrowad_uni_rust`.`permissions` p WHERE p.permission_code=x.code);
INSERT INTO `alrowad_uni_rust`.`role_permissions` (role_id,permission_id,granted_at) SELECT r.role_id,p.permission_id,CURRENT_TIMESTAMP FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`permissions` p ON (p.permission_code='supplementary_exams.registrations.self' AND r.role_code='student') OR (p.permission_code='supplementary_exams.registrations.view' AND r.role_code IN ('registration_officer','exam_officer','dean','vice_president_scientific')) OR (p.permission_code IN ('supplementary_exams.registrations.manage','supplementary_exams.registrations.window') AND r.role_code='registration_officer') WHERE @safe AND r.is_active=1 AND NOT EXISTS(SELECT 1 FROM `alrowad_uni_rust`.`role_permissions` rp WHERE rp.role_id=r.role_id AND rp.permission_id=p.permission_id);COMMIT;
SELECT 'APPLY_RESULT' AS report_section,IF(@safe,'APPLIED_OR_ADOPTED','BLOCKED') AS result,IF(NOT @phase3_ready,'PHASE3_NOT_DEPLOYED',IF(NOT @safe,'TARGET_SCHEMA_CONFLICT',NULL)) AS blocker_code;
