-- Read-only contract, RBAC, provenance, invariant, and summer-limit verification.
SET @phase3_ready := (SELECT COUNT(*)=2 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events'));
SET @tables_ready := (SELECT COUNT(*)=2 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_registrations','supplementary_exam_registration_events') AND engine='InnoDB');
SET @columns_ready := (SELECT COUNT(*)=24 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_id','student_course_registration_id','status','current_slot','eligibility_reason','registration_channel','registered_by_user_id','registered_at','cancelled_by_user_id','cancelled_at','cancellation_reason','eligibility_checked_at','created_at','updated_at')) OR (table_name='supplementary_exam_registration_events' AND column_name IN ('supplementary_exam_registration_event_id','supplementary_exam_registration_id','event_type','from_status','to_status','actor_user_id','notes','created_at'))));
SET @rbac_exact := (SELECT COUNT(DISTINCT CONCAT(r.role_code,':',p.permission_code))=7 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE (p.permission_code='supplementary_exams.registrations.self' AND r.role_code='student') OR (p.permission_code='supplementary_exams.registrations.view' AND r.role_code IN ('registration_officer','exam_officer','dean','vice_president_scientific')) OR (p.permission_code IN ('supplementary_exams.registrations.manage','supplementary_exams.registrations.window') AND r.role_code='registration_officer'));
SET @forbidden := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE p.permission_code IN ('supplementary_exams.registrations.self','supplementary_exams.registrations.manage','supplementary_exams.registrations.window') AND NOT ((p.permission_code='supplementary_exams.registrations.self' AND r.role_code='student') OR (p.permission_code IN ('supplementary_exams.registrations.manage','supplementary_exams.registrations.window') AND r.role_code='registration_officer')));
SET @invalid := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`supplementary_exam_registrations` r LEFT JOIN `alrowad_uni_rust`.`student_course_registrations` scr ON scr.student_course_registration_id=r.student_course_registration_id LEFT JOIN `alrowad_uni_rust`.`supplementary_exam_offering_sources` src ON src.supplementary_exam_offering_id=r.supplementary_exam_offering_id AND src.course_offering_id=scr.course_offering_id WHERE r.status NOT IN ('registered','cancelled') OR (r.status='registered' AND (r.current_slot IS NULL OR r.current_slot<>1 OR r.cancelled_by_user_id IS NOT NULL OR r.cancelled_at IS NOT NULL)) OR (r.status='cancelled' AND (r.current_slot IS NOT NULL OR r.cancelled_by_user_id IS NULL OR r.cancelled_at IS NULL)) OR r.eligibility_reason NOT IN ('failed_theoretical','voluntarily_deferred_theoretical') OR r.registration_channel NOT IN ('student_self','student_affairs') OR scr.student_course_registration_id IS NULL OR scr.student_id<>r.student_id OR src.supplementary_exam_offering_source_id IS NULL);
SET @orphan_events := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`supplementary_exam_registration_events` e LEFT JOIN `alrowad_uni_rust`.`supplementary_exam_registrations` r ON r.supplementary_exam_registration_id=e.supplementary_exam_registration_id LEFT JOIN `alrowad_uni_rust`.`users` u ON u.user_id=e.actor_user_id WHERE r.supplementary_exam_registration_id IS NULL OR u.user_id IS NULL);
SET @summer_violations := (SELECT COUNT(*) FROM (SELECT r.student_id FROM `alrowad_uni_rust`.`supplementary_exam_registrations` r JOIN `alrowad_uni_rust`.`supplementary_exam_offerings` o ON o.supplementary_exam_offering_id=r.supplementary_exam_offering_id JOIN `alrowad_uni_rust`.`supplementary_exam_periods` p ON p.supplementary_exam_period_id=o.supplementary_exam_period_id JOIN `alrowad_uni_rust`.`semesters` s ON s.semester_id=p.semester_id WHERE s.semester_order=3 AND r.status='registered' AND r.current_slot=1 GROUP BY p.supplementary_exam_period_id,r.student_id HAVING COUNT(*)>3) excessive);
SET @ok := @phase3_ready AND @tables_ready AND @columns_ready AND @rbac_exact AND @forbidden=0 AND @invalid=0 AND @orphan_events=0 AND @summer_violations=0;
SELECT 'OVERALL' AS report_section,IF(@ok,'PASS','FAIL') AS result,IF(NOT @phase3_ready,'PHASE3_NOT_DEPLOYED',IF(NOT @tables_ready OR NOT @columns_ready,'PHASE4_SCHEMA_INVALID',IF(NOT @rbac_exact OR @forbidden>0,'RBAC_INVALID',IF(@summer_violations>0,'SUMMER_LIMIT_VIOLATION','DATA_INVALID')))) AS blocker_code,@invalid AS invalid_rows,@orphan_events AS orphan_events,@summer_violations AS summer_violations;
