-- Semester Registration Phase 5 preflight. READ ONLY. Run in phpMyAdmin.
USE `alrowad_uni_rust`;

SET @srm5_db := (SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name='alrowad_uni_rust');
SET @srm5_core_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND table_name IN (
 'student_registration_requests','student_registration_request_items','student_registration_request_events',
 'student_course_registrations','registration_statuses','student_registration_withdrawal_requests','student_registration_withdrawal_events',
 'students','course_offerings','courses','academic_years','semesters','users',
 'academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions',
 'course_offering_schedule_slots','academic_requirement_groups','program_courses','permissions','roles','role_permissions','user_roles','user_access_scopes'
));
SET @srm5_phase2_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
 (table_name='academic_calendar_event_versions' AND column_name IN ('student_registration_ends_at','advisor_approval_ends_at')) OR
 (table_name='student_registration_requests' AND column_name='expired_at')
));
SET @srm5_phase4_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND column_name IN ('course_offering_schedule_slot_id','course_offering_id','component_type','day_of_week','start_time','end_time'));
SET @srm5_signed_keys := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND (
 (table_name='student_registration_requests' AND column_name='student_registration_request_id') OR
 (table_name='students' AND column_name='student_id') OR (table_name='academic_years' AND column_name='academic_year_id') OR
 (table_name='semesters' AND column_name='semester_id') OR (table_name='course_offerings' AND column_name='course_offering_id') OR
 (table_name='student_course_registrations' AND column_name='student_course_registration_id') OR (table_name='users' AND column_name='user_id')
));
SET @srm5_permissions := (SELECT COUNT(DISTINCT permission_code) FROM `alrowad_uni_rust`.`permissions` WHERE permission_code IN ('registration_requests.view','registration_requests.review') AND is_active=1);
SET @srm5_advisor_mapping := (SELECT COUNT(DISTINCT p.permission_code) FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`role_permissions` rp ON rp.role_id=r.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE r.role_code='academic_advisor' AND r.is_active=1 AND p.is_active=1 AND p.permission_code IN ('registration_requests.view','registration_requests.review'));

SET @srm5_target_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events'));
SET @srm5_target_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
 (table_name='student_registration_modification_requests' AND column_name IN ('student_registration_modification_request_id','initial_registration_request_id','student_id','academic_year_id','semester_id','status','submission_version','current_slot','student_notes','advisor_user_id','advisor_notes','first_submitted_at','last_submitted_at','reviewed_at','approved_at','expired_at','superseded_at','materialized_at','registered_hours_before_approval','removed_hours_at_approval','added_hours_at_approval','projected_hours_at_approval','max_allowed_hours_at_approval','remaining_hours_after_approval','created_at','updated_at')) OR
 (table_name='student_registration_modification_items' AND column_name IN ('student_registration_modification_item_id','student_registration_modification_request_id','operation','course_offering_id','source_student_course_registration_id','materialized_student_course_registration_id','created_at','updated_at')) OR
 (table_name='student_registration_modification_events' AND column_name IN ('student_registration_modification_event_id','student_registration_modification_request_id','event_type','actor_user_id','from_status','to_status','submission_version','notes','created_at'))
));
SET @srm5_target_total_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events'));
SET @srm5_target_engines := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND engine='InnoDB');
SET @srm5_target_owned := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND table_comment LIKE 'Owned by semester-registration-modifications-phase5%');
SET @srm5_target_signed := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND ((table_name='student_registration_modification_requests' AND column_name IN ('student_registration_modification_request_id','initial_registration_request_id','student_id','academic_year_id','semester_id','advisor_user_id')) OR (table_name='student_registration_modification_items' AND column_name IN ('student_registration_modification_item_id','student_registration_modification_request_id','course_offering_id','source_student_course_registration_id','materialized_student_course_registration_id')) OR (table_name='student_registration_modification_events' AND column_name IN ('student_registration_modification_event_id','student_registration_modification_request_id','actor_user_id'))));
SET @srm5_target_unique := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND index_name<>'PRIMARY' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items') GROUP BY table_name,index_name) i WHERE (table_name='student_registration_modification_requests' AND index_name='uq_srmod_current_slot' AND cols='student_id,academic_year_id,semester_id,current_slot') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_offering' AND cols='student_registration_modification_request_id,course_offering_id') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_source' AND cols='student_registration_modification_request_id,source_student_course_registration_id'));
SET @srm5_target_fks := (SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_srmod_initial','fk_srmod_student','fk_srmod_year','fk_srmod_semester','fk_srmod_advisor','fk_srmodi_request','fk_srmodi_offering','fk_srmodi_source_registration','fk_srmodi_materialized_registration','fk_srmode_request','fk_srmode_actor') AND update_rule='RESTRICT' AND delete_rule='RESTRICT');
SET @srm5_target_fk_links := (SELECT COUNT(*) FROM information_schema.key_column_usage WHERE constraint_schema='alrowad_uni_rust' AND ((table_name='student_registration_modification_requests' AND column_name='initial_registration_request_id' AND referenced_table_name='student_registration_requests' AND referenced_column_name='student_registration_request_id') OR (table_name='student_registration_modification_requests' AND column_name='student_id' AND referenced_table_name='students' AND referenced_column_name='student_id') OR (table_name='student_registration_modification_requests' AND column_name='academic_year_id' AND referenced_table_name='academic_years' AND referenced_column_name='academic_year_id') OR (table_name='student_registration_modification_requests' AND column_name='semester_id' AND referenced_table_name='semesters' AND referenced_column_name='semester_id') OR (table_name='student_registration_modification_requests' AND column_name='advisor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id') OR (table_name='student_registration_modification_items' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_items' AND column_name='course_offering_id' AND referenced_table_name='course_offerings' AND referenced_column_name='course_offering_id') OR (table_name='student_registration_modification_items' AND column_name='source_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_items' AND column_name='materialized_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_events' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_events' AND column_name='actor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id')));
SET @srm5_target_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('chk_srmod_status','chk_srmod_version','chk_srmod_current','chk_srmod_submission','chk_srmod_return','chk_srmod_terminal','chk_srmod_materialized','chk_srmod_snapshot','chk_srmodi_operation','chk_srmodi_source','chk_srmode_type','chk_srmode_version') AND constraint_type='CHECK');
SET @srm5_target_compatible := (@srm5_target_tables=3 AND @srm5_target_columns=43 AND @srm5_target_total_columns=43 AND @srm5_target_engines=3 AND @srm5_target_owned=3 AND @srm5_target_signed=14 AND @srm5_target_unique=3 AND @srm5_target_fks=11 AND @srm5_target_fk_links=11 AND @srm5_target_checks=12);
SET @srm5_ready := (@srm5_db=1 AND @srm5_core_tables=24 AND @srm5_phase2_columns=3 AND @srm5_phase4_columns=6 AND @srm5_signed_keys=7 AND @srm5_permissions=2 AND @srm5_advisor_mapping=2 AND (@srm5_target_tables=0 OR @srm5_target_compatible));

SELECT 'DATABASE_AND_CORE' report_section,IF(@srm5_db=1 AND @srm5_core_tables=24,'PASS','FAIL') result,CONCAT('core_tables=',@srm5_core_tables,'/24') detail;
SELECT 'PHASE2_AND_PHASE4' report_section,IF(@srm5_phase2_columns=3 AND @srm5_phase4_columns=6,'PASS','FAIL') result,CONCAT('deadline_columns=',@srm5_phase2_columns,'/3; timetable_columns=',@srm5_phase4_columns,'/6') detail;
SELECT 'KEY_AND_ADVISOR_RBAC' report_section,IF(@srm5_signed_keys=7 AND @srm5_permissions=2 AND @srm5_advisor_mapping=2,'PASS','FAIL') result,CONCAT('signed_keys=',@srm5_signed_keys,'/7; permissions=',@srm5_permissions,'/2; advisor_mappings=',@srm5_advisor_mapping,'/2') detail;
SELECT 'PHASE5_OBJECTS' report_section,IF(@srm5_target_tables=0,'ABSENT',IF(@srm5_target_compatible,'COMPATIBLE','CONFLICTING')) result,CONCAT('tables=',@srm5_target_tables,'/3; columns=',@srm5_target_columns,'/43; signed=',@srm5_target_signed,'/14; unique=',@srm5_target_unique,'/3; fks=',@srm5_target_fks,'/11; fk_links=',@srm5_target_fk_links,'/11; checks=',@srm5_target_checks,'/12') detail;
SELECT 'INFORMATIONAL' report_section,'INFO' result,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_requests` WHERE status='approved') approved_initial_requests,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_course_registrations` scr JOIN `alrowad_uni_rust`.`registration_statuses` rs ON rs.registration_status_id=scr.registration_status_id WHERE rs.status_code='registered') current_registrations,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_withdrawal_requests` WHERE current_slot=1) current_withdrawals;
SELECT 'OVERALL' report_section,IF(@srm5_ready,'READY','BLOCKED') result;
