-- Guarded, rerunnable MariaDB 10.11 apply. No production rows are backfilled.
USE `alrowad_uni_rust`;

SET @srm5_apply_core := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_requests','student_registration_request_items','student_registration_request_events','student_course_registrations','registration_statuses','student_registration_withdrawal_requests','student_registration_withdrawal_events','students','course_offerings','courses','academic_years','semesters','users','academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions','course_offering_schedule_slots','academic_requirement_groups','program_courses','permissions','roles','role_permissions','user_roles','user_access_scopes'));
SET @srm5_apply_phase2 := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='academic_calendar_event_versions' AND column_name IN ('student_registration_ends_at','advisor_approval_ends_at')) OR (table_name='student_registration_requests' AND column_name='expired_at')));
SET @srm5_apply_permissions := (SELECT COUNT(DISTINCT permission_code) FROM `alrowad_uni_rust`.`permissions` WHERE permission_code IN ('registration_requests.view','registration_requests.review') AND is_active=1);
SET @srm5_apply_targets := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events'));
SET @srm5_apply_request_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_requests');
SET @srm5_apply_item_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_items');
SET @srm5_apply_event_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_events');
SET @srm5_apply_expected_columns := (26*@srm5_apply_request_exists + 8*@srm5_apply_item_exists + 9*@srm5_apply_event_exists);
SET @srm5_apply_expected_signed := (6*@srm5_apply_request_exists + 5*@srm5_apply_item_exists + 3*@srm5_apply_event_exists);
SET @srm5_apply_expected_unique := (1*@srm5_apply_request_exists + 2*@srm5_apply_item_exists);
SET @srm5_apply_expected_fks := (5*@srm5_apply_request_exists + 4*@srm5_apply_item_exists + 2*@srm5_apply_event_exists);
SET @srm5_apply_expected_checks := (8*@srm5_apply_request_exists + 2*@srm5_apply_item_exists + 2*@srm5_apply_event_exists);
SET @srm5_apply_expected_indexes := (5*@srm5_apply_request_exists + 1*@srm5_apply_item_exists + 3*@srm5_apply_event_exists);
SET @srm5_apply_target_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events'));
SET @srm5_apply_required_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='student_registration_modification_requests' AND column_name IN ('student_registration_modification_request_id','initial_registration_request_id','student_id','academic_year_id','semester_id','status','submission_version','current_slot','student_notes','advisor_user_id','advisor_notes','first_submitted_at','last_submitted_at','reviewed_at','approved_at','expired_at','superseded_at','materialized_at','registered_hours_before_approval','removed_hours_at_approval','added_hours_at_approval','projected_hours_at_approval','max_allowed_hours_at_approval','remaining_hours_after_approval','created_at','updated_at')) OR (table_name='student_registration_modification_items' AND column_name IN ('student_registration_modification_item_id','student_registration_modification_request_id','operation','course_offering_id','source_student_course_registration_id','materialized_student_course_registration_id','created_at','updated_at')) OR (table_name='student_registration_modification_events' AND column_name IN ('student_registration_modification_event_id','student_registration_modification_request_id','event_type','actor_user_id','from_status','to_status','submission_version','notes','created_at'))));
SET @srm5_apply_owned := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND engine='InnoDB' AND table_comment LIKE 'Owned by semester-registration-modifications-phase5%');
SET @srm5_apply_signed := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND ((table_name='student_registration_modification_requests' AND column_name IN ('student_registration_modification_request_id','initial_registration_request_id','student_id','academic_year_id','semester_id','advisor_user_id')) OR (table_name='student_registration_modification_items' AND column_name IN ('student_registration_modification_item_id','student_registration_modification_request_id','course_offering_id','source_student_course_registration_id','materialized_student_course_registration_id')) OR (table_name='student_registration_modification_events' AND column_name IN ('student_registration_modification_event_id','student_registration_modification_request_id','actor_user_id'))));
SET @srm5_apply_pk := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND constraint_type='PRIMARY KEY');
SET @srm5_apply_unique := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND index_name<>'PRIMARY' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items') GROUP BY table_name,index_name) i WHERE (table_name='student_registration_modification_requests' AND index_name='uq_srmod_current_slot' AND cols='student_id,academic_year_id,semester_id,current_slot') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_offering' AND cols='student_registration_modification_request_id,course_offering_id') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_source' AND cols='student_registration_modification_request_id,source_student_course_registration_id'));
SET @srm5_apply_fks := (SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_srmod_initial','fk_srmod_student','fk_srmod_year','fk_srmod_semester','fk_srmod_advisor','fk_srmodi_request','fk_srmodi_offering','fk_srmodi_source_registration','fk_srmodi_materialized_registration','fk_srmode_request','fk_srmode_actor') AND update_rule='RESTRICT' AND delete_rule='RESTRICT');
SET @srm5_apply_fk_links := (SELECT COUNT(*) FROM information_schema.key_column_usage WHERE constraint_schema='alrowad_uni_rust' AND ((table_name='student_registration_modification_requests' AND column_name='initial_registration_request_id' AND referenced_table_name='student_registration_requests' AND referenced_column_name='student_registration_request_id') OR (table_name='student_registration_modification_requests' AND column_name='student_id' AND referenced_table_name='students' AND referenced_column_name='student_id') OR (table_name='student_registration_modification_requests' AND column_name='academic_year_id' AND referenced_table_name='academic_years' AND referenced_column_name='academic_year_id') OR (table_name='student_registration_modification_requests' AND column_name='semester_id' AND referenced_table_name='semesters' AND referenced_column_name='semester_id') OR (table_name='student_registration_modification_requests' AND column_name='advisor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id') OR (table_name='student_registration_modification_items' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_items' AND column_name='course_offering_id' AND referenced_table_name='course_offerings' AND referenced_column_name='course_offering_id') OR (table_name='student_registration_modification_items' AND column_name='source_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_items' AND column_name='materialized_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_events' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_events' AND column_name='actor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id')));
SET @srm5_apply_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('chk_srmod_status','chk_srmod_version','chk_srmod_current','chk_srmod_submission','chk_srmod_return','chk_srmod_terminal','chk_srmod_materialized','chk_srmod_snapshot','chk_srmodi_operation','chk_srmodi_source','chk_srmode_type','chk_srmode_version') AND constraint_type='CHECK');
SET @srm5_apply_indexes := (SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND (index_name,seq_in_index,column_name) IN (('idx_srmod_queue',1,'status'),('idx_srmod_queue',2,'last_submitted_at'),('idx_srmod_queue',3,'student_registration_modification_request_id'),('idx_srmod_initial',1,'initial_registration_request_id'),('idx_srmod_advisor',1,'advisor_user_id'),('idx_srmodi_materialized',1,'materialized_student_course_registration_id'),('idx_srmode_request_history',1,'student_registration_modification_request_id'),('idx_srmode_request_history',2,'created_at'),('idx_srmode_actor',1,'actor_user_id')));
SET @srm5_apply_existing_compatible := (@srm5_apply_target_columns=@srm5_apply_expected_columns AND @srm5_apply_required_columns=@srm5_apply_expected_columns AND @srm5_apply_owned=@srm5_apply_targets AND @srm5_apply_signed=@srm5_apply_expected_signed AND @srm5_apply_pk=@srm5_apply_targets AND @srm5_apply_unique=@srm5_apply_expected_unique AND @srm5_apply_fks=@srm5_apply_expected_fks AND @srm5_apply_fk_links=@srm5_apply_expected_fks AND @srm5_apply_checks=@srm5_apply_expected_checks AND @srm5_apply_indexes=@srm5_apply_expected_indexes);
SET @srm5_apply_ready := (@srm5_apply_core=24 AND @srm5_apply_phase2=3 AND @srm5_apply_permissions=2 AND @srm5_apply_existing_compatible);

SET @srm5_sql := IF(@srm5_apply_ready AND @srm5_apply_request_exists=0,
'CREATE TABLE `alrowad_uni_rust`.`student_registration_modification_requests` (
 `student_registration_modification_request_id` INT NOT NULL AUTO_INCREMENT,
 `initial_registration_request_id` INT NOT NULL, `student_id` INT NOT NULL, `academic_year_id` INT NOT NULL, `semester_id` INT NOT NULL,
 `status` VARCHAR(40) NOT NULL DEFAULT ''draft'', `submission_version` INT NOT NULL DEFAULT 0, `current_slot` TINYINT NULL DEFAULT 1,
 `student_notes` TEXT NULL, `advisor_user_id` INT NULL, `advisor_notes` TEXT NULL,
 `first_submitted_at` DATETIME NULL, `last_submitted_at` DATETIME NULL, `reviewed_at` DATETIME NULL, `approved_at` DATETIME NULL,
 `expired_at` DATETIME NULL, `superseded_at` DATETIME NULL, `materialized_at` DATETIME NULL,
 `registered_hours_before_approval` INT NULL, `removed_hours_at_approval` INT NULL, `added_hours_at_approval` INT NULL,
 `projected_hours_at_approval` INT NULL, `max_allowed_hours_at_approval` INT NULL, `remaining_hours_after_approval` INT NULL,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_modification_request_id`),
 UNIQUE KEY `uq_srmod_current_slot` (`student_id`,`academic_year_id`,`semester_id`,`current_slot`),
 KEY `idx_srmod_queue` (`status`,`last_submitted_at`,`student_registration_modification_request_id`), KEY `idx_srmod_initial` (`initial_registration_request_id`), KEY `idx_srmod_advisor` (`advisor_user_id`),
 CONSTRAINT `chk_srmod_status` CHECK (`status` IN (''draft'',''submitted'',''returned'',''approved'',''expired'',''superseded'')),
 CONSTRAINT `chk_srmod_version` CHECK (`submission_version` >= 0), CONSTRAINT `chk_srmod_current` CHECK ((`status` IN (''draft'',''submitted'',''returned'') AND `current_slot`=1) OR (`status` IN (''approved'',''expired'',''superseded'') AND `current_slot` IS NULL)),
 CONSTRAINT `chk_srmod_submission` CHECK (`status` NOT IN (''submitted'',''returned'',''approved'') OR (`submission_version` > 0 AND `first_submitted_at` IS NOT NULL AND `last_submitted_at` IS NOT NULL)),
 CONSTRAINT `chk_srmod_return` CHECK (`status`<>''returned'' OR (`advisor_user_id` IS NOT NULL AND `reviewed_at` IS NOT NULL AND NULLIF(TRIM(`advisor_notes`),'''') IS NOT NULL)),
 CONSTRAINT `chk_srmod_terminal` CHECK ((`status`<>''approved'' OR (`advisor_user_id` IS NOT NULL AND `approved_at` IS NOT NULL AND `materialized_at` IS NOT NULL)) AND (`status`<>''expired'' OR `expired_at` IS NOT NULL) AND (`status`<>''superseded'' OR `superseded_at` IS NOT NULL)),
 CONSTRAINT `chk_srmod_materialized` CHECK ((`status`=''approved'' AND `materialized_at` IS NOT NULL) OR (`status`<>''approved'' AND `materialized_at` IS NULL)),
 CONSTRAINT `chk_srmod_snapshot` CHECK ((`status`=''approved'' AND `registered_hours_before_approval` IS NOT NULL AND `removed_hours_at_approval` IS NOT NULL AND `added_hours_at_approval` IS NOT NULL AND `projected_hours_at_approval` IS NOT NULL AND `max_allowed_hours_at_approval` IS NOT NULL AND `remaining_hours_after_approval` IS NOT NULL) OR (`status`<>''approved'' AND `registered_hours_before_approval` IS NULL AND `removed_hours_at_approval` IS NULL AND `added_hours_at_approval` IS NULL AND `projected_hours_at_approval` IS NULL AND `max_allowed_hours_at_approval` IS NULL AND `remaining_hours_after_approval` IS NULL)),
 CONSTRAINT `fk_srmod_initial` FOREIGN KEY (`initial_registration_request_id`) REFERENCES `alrowad_uni_rust`.`student_registration_requests` (`student_registration_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmod_student` FOREIGN KEY (`student_id`) REFERENCES `alrowad_uni_rust`.`students` (`student_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmod_year` FOREIGN KEY (`academic_year_id`) REFERENCES `alrowad_uni_rust`.`academic_years` (`academic_year_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmod_semester` FOREIGN KEY (`semester_id`) REFERENCES `alrowad_uni_rust`.`semesters` (`semester_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmod_advisor` FOREIGN KEY (`advisor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-modifications-phase5; approved registration delta workflow''',
'SELECT ''PHASE5_REQUEST_TABLE'' report_section,''SKIPPED'' result');
PREPARE srm5_stmt FROM @srm5_sql; EXECUTE srm5_stmt; DEALLOCATE PREPARE srm5_stmt;
SET @srm5_apply_request_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_requests');

SET @srm5_sql := IF(@srm5_apply_ready AND @srm5_apply_request_exists=1 AND @srm5_apply_item_exists=0,
'CREATE TABLE `alrowad_uni_rust`.`student_registration_modification_items` (
 `student_registration_modification_item_id` INT NOT NULL AUTO_INCREMENT, `student_registration_modification_request_id` INT NOT NULL,
 `operation` VARCHAR(16) NOT NULL, `course_offering_id` INT NOT NULL, `source_student_course_registration_id` INT NULL, `materialized_student_course_registration_id` INT NULL,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_modification_item_id`),
 UNIQUE KEY `uq_srmodi_offering` (`student_registration_modification_request_id`,`course_offering_id`),
 UNIQUE KEY `uq_srmodi_source` (`student_registration_modification_request_id`,`source_student_course_registration_id`),
 KEY `idx_srmodi_materialized` (`materialized_student_course_registration_id`),
 CONSTRAINT `chk_srmodi_operation` CHECK (`operation` IN (''keep'',''remove'',''add'')),
 CONSTRAINT `chk_srmodi_source` CHECK ((`operation` IN (''keep'',''remove'') AND `source_student_course_registration_id` IS NOT NULL AND `materialized_student_course_registration_id` IS NULL) OR (`operation`=''add'' AND `source_student_course_registration_id` IS NULL)),
 CONSTRAINT `fk_srmodi_request` FOREIGN KEY (`student_registration_modification_request_id`) REFERENCES `alrowad_uni_rust`.`student_registration_modification_requests` (`student_registration_modification_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmodi_offering` FOREIGN KEY (`course_offering_id`) REFERENCES `alrowad_uni_rust`.`course_offerings` (`course_offering_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmodi_source_registration` FOREIGN KEY (`source_student_course_registration_id`) REFERENCES `alrowad_uni_rust`.`student_course_registrations` (`student_course_registration_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmodi_materialized_registration` FOREIGN KEY (`materialized_student_course_registration_id`) REFERENCES `alrowad_uni_rust`.`student_course_registrations` (`student_course_registration_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-modifications-phase5; immutable baseline and delta items''',
'SELECT ''PHASE5_ITEM_TABLE'' report_section,''SKIPPED'' result');
PREPARE srm5_stmt FROM @srm5_sql; EXECUTE srm5_stmt; DEALLOCATE PREPARE srm5_stmt;
SET @srm5_apply_item_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_items');

SET @srm5_sql := IF(@srm5_apply_ready AND @srm5_apply_request_exists=1 AND @srm5_apply_event_exists=0,
'CREATE TABLE `alrowad_uni_rust`.`student_registration_modification_events` (
 `student_registration_modification_event_id` INT NOT NULL AUTO_INCREMENT, `student_registration_modification_request_id` INT NOT NULL,
 `event_type` VARCHAR(48) NOT NULL, `actor_user_id` INT NULL, `from_status` VARCHAR(40) NULL, `to_status` VARCHAR(40) NULL, `submission_version` INT NULL, `notes` TEXT NULL,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_registration_modification_event_id`), KEY `idx_srmode_request_history` (`student_registration_modification_request_id`,`created_at`), KEY `idx_srmode_actor` (`actor_user_id`),
 CONSTRAINT `chk_srmode_type` CHECK (`event_type` IN (''draft_created'',''baseline_snapshotted'',''item_marked_remove'',''item_restored_keep'',''item_added'',''item_removed'',''submitted'',''resubmitted'',''returned'',''approved'',''materialized'',''expired_deadline'',''superseded_baseline_changed'')),
 CONSTRAINT `chk_srmode_version` CHECK (`submission_version` IS NULL OR `submission_version` >= 0),
 CONSTRAINT `fk_srmode_request` FOREIGN KEY (`student_registration_modification_request_id`) REFERENCES `alrowad_uni_rust`.`student_registration_modification_requests` (`student_registration_modification_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT `fk_srmode_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-registration-modifications-phase5; append-only workflow history''',
'SELECT ''PHASE5_EVENT_TABLE'' report_section,''SKIPPED'' result');
PREPARE srm5_stmt FROM @srm5_sql; EXECUTE srm5_stmt; DEALLOCATE PREPARE srm5_stmt;
SET @srm5_apply_event_exists := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='student_registration_modification_events');
SET @srm5_apply_targets_after := (@srm5_apply_request_exists+@srm5_apply_item_exists+@srm5_apply_event_exists);

SELECT 'APPLY_GUARD' report_section,IF(@srm5_apply_ready,'PASS','FAIL') result,CONCAT('core=',@srm5_apply_core,'/24; phase2=',@srm5_apply_phase2,'/3; permissions=',@srm5_apply_permissions,'/2; target_tables_before=',@srm5_apply_targets,'; compatible_existing=',@srm5_apply_existing_compatible,'; target_tables_after=',@srm5_apply_targets_after) detail;
SELECT 'OVERALL' report_section,IF(NOT @srm5_apply_ready,'BLOCKED',IF(@srm5_apply_targets_after<>3,'BLOCKED',IF(@srm5_apply_targets=3,'ALREADY_APPLIED',IF(@srm5_apply_targets=0,'APPLIED','RESUMED')))) result;
