-- Semester Registration Phase 5 verification. READ ONLY.
USE `alrowad_uni_rust`;

SET @srm5v_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND engine='InnoDB');
SET @srm5v_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events'));
SET @srm5v_signed := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND ((table_name='student_registration_modification_requests' AND column_name IN ('student_registration_modification_request_id','initial_registration_request_id','student_id','academic_year_id','semester_id','advisor_user_id')) OR (table_name='student_registration_modification_items' AND column_name IN ('student_registration_modification_item_id','student_registration_modification_request_id','course_offering_id','source_student_course_registration_id','materialized_student_course_registration_id')) OR (table_name='student_registration_modification_events' AND column_name IN ('student_registration_modification_event_id','student_registration_modification_request_id','actor_user_id'))));
SET @srm5v_pk := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND constraint_type='PRIMARY KEY');
SET @srm5v_unique := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND index_name<>'PRIMARY' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items') GROUP BY table_name,index_name) i WHERE (table_name='student_registration_modification_requests' AND index_name='uq_srmod_current_slot' AND cols='student_id,academic_year_id,semester_id,current_slot') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_offering' AND cols='student_registration_modification_request_id,course_offering_id') OR (table_name='student_registration_modification_items' AND index_name='uq_srmodi_source' AND cols='student_registration_modification_request_id,source_student_course_registration_id'));
SET @srm5v_fks := (SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_srmod_initial','fk_srmod_student','fk_srmod_year','fk_srmod_semester','fk_srmod_advisor','fk_srmodi_request','fk_srmodi_offering','fk_srmodi_source_registration','fk_srmodi_materialized_registration','fk_srmode_request','fk_srmode_actor') AND update_rule='RESTRICT' AND delete_rule='RESTRICT');
SET @srm5v_fk_links := (SELECT COUNT(*) FROM information_schema.key_column_usage WHERE constraint_schema='alrowad_uni_rust' AND ((table_name='student_registration_modification_requests' AND column_name='initial_registration_request_id' AND referenced_table_name='student_registration_requests' AND referenced_column_name='student_registration_request_id') OR (table_name='student_registration_modification_requests' AND column_name='student_id' AND referenced_table_name='students' AND referenced_column_name='student_id') OR (table_name='student_registration_modification_requests' AND column_name='academic_year_id' AND referenced_table_name='academic_years' AND referenced_column_name='academic_year_id') OR (table_name='student_registration_modification_requests' AND column_name='semester_id' AND referenced_table_name='semesters' AND referenced_column_name='semester_id') OR (table_name='student_registration_modification_requests' AND column_name='advisor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id') OR (table_name='student_registration_modification_items' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_items' AND column_name='course_offering_id' AND referenced_table_name='course_offerings' AND referenced_column_name='course_offering_id') OR (table_name='student_registration_modification_items' AND column_name='source_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_items' AND column_name='materialized_student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id') OR (table_name='student_registration_modification_events' AND column_name='student_registration_modification_request_id' AND referenced_table_name='student_registration_modification_requests' AND referenced_column_name='student_registration_modification_request_id') OR (table_name='student_registration_modification_events' AND column_name='actor_user_id' AND referenced_table_name='users' AND referenced_column_name='user_id')));
SET @srm5v_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('chk_srmod_status','chk_srmod_version','chk_srmod_current','chk_srmod_submission','chk_srmod_return','chk_srmod_terminal','chk_srmod_materialized','chk_srmod_snapshot','chk_srmodi_operation','chk_srmodi_source','chk_srmode_type','chk_srmode_version') AND constraint_type='CHECK');
SET @srm5v_indexes := (SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND (index_name,seq_in_index,column_name) IN (('idx_srmod_queue',1,'status'),('idx_srmod_queue',2,'last_submitted_at'),('idx_srmod_queue',3,'student_registration_modification_request_id'),('idx_srmod_initial',1,'initial_registration_request_id'),('idx_srmod_advisor',1,'advisor_user_id'),('idx_srmodi_materialized',1,'materialized_student_course_registration_id'),('idx_srmode_request_history',1,'student_registration_modification_request_id'),('idx_srmode_request_history',2,'created_at'),('idx_srmode_actor',1,'actor_user_id')));
SET @srm5v_owned := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_modification_requests','student_registration_modification_items','student_registration_modification_events') AND table_comment LIKE 'Owned by semester-registration-modifications-phase5%');
SET @srm5v_rbac := (SELECT COUNT(DISTINCT p.permission_code) FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`role_permissions` rp ON rp.role_id=r.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE r.role_code='academic_advisor' AND r.is_active=1 AND p.is_active=1 AND p.permission_code IN ('registration_requests.view','registration_requests.review'));
SET @srm5v_prereq := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('student_registration_requests','student_registration_request_items','student_registration_request_events','student_course_registrations','student_registration_withdrawal_requests','course_offering_schedule_slots'));
SET @srm5v_ok := (@srm5v_tables=3 AND @srm5v_columns=43 AND @srm5v_signed=14 AND @srm5v_pk=3 AND @srm5v_unique=3 AND @srm5v_fks=11 AND @srm5v_fk_links=11 AND @srm5v_checks=12 AND @srm5v_indexes=9 AND @srm5v_owned=3 AND @srm5v_rbac=2 AND @srm5v_prereq=6);

SELECT 'TABLES_AND_COLUMNS' report_section,IF(@srm5v_tables=3 AND @srm5v_columns=43,'PASS','FAIL') result,CONCAT('tables=',@srm5v_tables,'/3; columns=',@srm5v_columns,'/43') detail;
SELECT 'KEYS_AND_CONSTRAINTS' report_section,IF(@srm5v_signed=14 AND @srm5v_pk=3 AND @srm5v_unique=3 AND @srm5v_fks=11 AND @srm5v_fk_links=11 AND @srm5v_checks=12 AND @srm5v_indexes=9,'PASS','FAIL') result,CONCAT('signed=',@srm5v_signed,'/14; pk=',@srm5v_pk,'/3; unique=',@srm5v_unique,'/3; fks=',@srm5v_fks,'/11; fk_links=',@srm5v_fk_links,'/11; checks=',@srm5v_checks,'/12; focused_index_columns=',@srm5v_indexes,'/9') detail;
SELECT 'OWNERSHIP_AND_RBAC' report_section,IF(@srm5v_owned=3 AND @srm5v_rbac=2,'PASS','FAIL') result,CONCAT('owned=',@srm5v_owned,'/3; advisor_mappings=',@srm5v_rbac,'/2') detail;
SELECT 'DATA' report_section,'INFO' result,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_modification_requests`) requests,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_modification_items`) items,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_modification_events`) events;
SELECT 'OVERALL' report_section,IF(@srm5v_ok,'PASS','FAIL') result;
