import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useBlocker, useNavigate, useSearchParams } from 'react-router-dom'
import { FaCoins, FaEye, FaPlus, FaUserTie } from 'react-icons/fa'
import DataTable from '../../../components/table/DataTable'
import FilterBar from '../../../components/table/FilterBar'
import { Dialog, Notice, headerButton, primaryButton, secondaryButton } from '../../vice-presidency/components/GovernanceUi'
import { ACCESS, PERMISSIONS, canAccess, clearIdentity, getIdentity } from '../../auth/auth'
import { ADMINISTRATIVE_ACCESS } from '../../vice-presidency/utils/administrativeAccess'
import { HR, SECTIONS, canHr, hrDate, hrError, label, payrollAccess, payrollFilePath, requestEditable, workerFilePath } from '../lib/hrOffice'
import { hrRead, hrWrite } from '../lib/hrApi'
import { CandidateEditor, Editor, Input, Lookup, NeedEditor, RelationshipEditor, Select } from '../components/HrForms'
import { HrStatus, HrTabs, PayrollLinkStatus } from '../components/HrOfficeUi'
import { needItemColumns, officeColumns, personName, positionName } from '../components/HrOfficeTables'

const name = personName
const grid = 'grid grid-cols-2 gap-4 max-[560px]:grid-cols-1'
function Facts({ entries }) { return <dl className={grid}>{entries.map(([title, value]) => <div key={title} className="rounded-[10px] bg-primary/5 p-3"><dt className="text-[11.5px] text-text-light">{title}</dt><dd className="mt-1 break-words text-[13px] font-bold">{value ?? 'غير محدد'}</dd></div>)}</dl> }
function Relation({ row, options }) { return <Facts entries={[
  ['الهيئة', label(row.body)], ['العلاقة', label(row.relationship_type)], ['نمط العمل', label(row.work_mode)], ['البداية', hrDate(row.starts_on)], ['النهاية المسجلة', row.ends_on ? hrDate(row.ends_on) : 'مستمر'], ['الصفة', row.job_title], ['الكلية / الوحدة', options.colleges.find(c => c.college_id === row.college_id)?.college_name || options.units.find(u => u.organizational_unit_id === row.organizational_unit_id)?.unit_name], ['المصدر', row.source ? label(row.source) : 'مقترح — غير نافذ'], ['التحويل نافذ من', row.superseded_from ? hrDate(row.superseded_from) : '—'], ['الملاحظات', row.notes || '—'],
]} /> }
function Events({ events = [] }) { return <details className="border-t pt-3"><summary className="cursor-pointer font-bold">سجل القرارات والتغييرات</summary><ol className="mt-3 space-y-2">{events.length ? events.map(e => <li key={e.id} className="rounded-[10px] border p-3 text-[12px]"><span>{e.action} — {e.created_at} — المنفذ #{e.actor_user_id}</span><details><summary>تفاصيل السجل</summary><pre className="overflow-x-auto whitespace-pre-wrap break-words" dir="rtl">{JSON.stringify(typeof e.details === 'string' ? JSON.parse(e.details) : e.details, null, 2)}</pre></details></li>) : <li>لا توجد أحداث مسجلة.</li>}</ol></details> }

export default function HrOfficePage() {
  const identity = JSON.stringify(getIdentity())
  return canHr('view') ? <OfficeWorkspace key={identity} identity={identity} /> : <Notice tone="error">لا تملك صلاحية مكتب الموارد البشرية.</Notice>
}

function OfficeWorkspace({ identity }) {
  const navigate = useNavigate(); const authorityLost = useRef(false)
  const [params, setParams] = useSearchParams(); const section = SECTIONS.some(([id]) => id === params.get('section')) ? params.get('section') : 'workers'
  const page = Number(params.get('page')) || 1; const q = params.get('q') || ''; const body = params.get('body') || ''; const college = params.get('college_id') || ''
  const [options, setOptions] = useState(null); const [listing, setListing] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reload, setReload] = useState(0)
  const [linkedPayroll, setLinkedPayroll] = useState(null)
  const [selection, setSelection] = useState(null); const [detail, setDetail] = useState(null); const [detailLoading, setDetailLoading] = useState(false); const [editing, setEditing] = useState(null); const [guard, setGuard] = useState({ dirty: false, busy: false, uncertain: false }); const [acting, setActing] = useState(false); const [mutationBlocked, setMutationBlocked] = useState(false)
  const listSequence = useRef(0); const detailSequence = useRef(0); const optionsSequence = useRef(0); const onGuard = setGuard
  const requestKey = JSON.stringify([section, q, body, college, page, reload, identity])
  const matching = listing?.key === requestKey
  const rows = matching ? listing.rows : []; const meta = matching ? listing.meta : {}; const loading = Boolean((!options && !error) || (options?.schema_ready && !matching))
  const dirty = guard.dirty || guard.uncertain; const pending = guard.busy || acting
  const blocker = useBlocker(({ currentLocation, nextLocation }) => !authorityLost.current && (dirty || pending) && currentLocation.pathname !== nextLocation.pathname)
  const clearSensitive = useCallback(e => {
    authorityLost.current = true; ++listSequence.current; ++detailSequence.current; ++optionsSequence.current
    setOptions(null); setListing(null); setDetail(null); setSelection(null); setEditing(null); setLinkedPayroll(null); setGuard({ dirty: false, busy: false, uncertain: false }); setMutationBlocked(true); setError(hrError(e))
    if (e.status === 401) { clearIdentity(); navigate('/login', { replace: true }) }
  }, [navigate, setOptions, setListing, setDetail, setSelection, setEditing, setLinkedPayroll, setGuard, setMutationBlocked, setError])
  useEffect(() => { if (!dirty && !pending) return undefined; const listener = e => { e.preventDefault(); e.returnValue = '' }; window.addEventListener('beforeunload', listener); return () => window.removeEventListener('beforeunload', listener) }, [dirty, pending])
  useEffect(() => {
    const abort = new AbortController(); const seq = ++optionsSequence.current; let active = true
    hrRead('options', {}, abort.signal).then(json => { if (active && seq === optionsSequence.current) { authorityLost.current = false; setOptions(json.data) } }).catch(e => { if (active && seq === optionsSequence.current && e.name !== 'AbortError') { if ([401, 403].includes(e.status)) clearSensitive(e); else setError(hrError(e)) } })
    return () => { active = false; abort.abort() }
  }, [identity, reload, clearSensitive])
  useEffect(() => {
    const abort = new AbortController(); const seq = ++listSequence.current; let active = true
    if (!options?.schema_ready) return () => abort.abort()
    hrRead(section, { q, body, college_id: college, page }, abort.signal).then(json => { if (active && seq === listSequence.current) { setListing({ key: requestKey, rows: json.data.rows, meta: json.data.meta }); setError('') } }).catch(e => { if (active && seq === listSequence.current && e.name !== 'AbortError') { if ([401, 403].includes(e.status)) clearSensitive(e); else { setListing({ key: requestKey, rows: [], meta: {} }); setError(hrError(e)) } } })
    return () => { active = false; abort.abort() }
  }, [section, q, body, college, page, requestKey, options, clearSensitive])
  const cap = key => !!options?.capabilities?.[HR[key]] && canHr(key)
  const payrollRead = !!options?.capabilities?.[PERMISSIONS.ownerPayrollView] && canAccess(payrollAccess(PERMISSIONS.ownerPayrollView))
  const related = canAccess(ACCESS.administrativeVicePresident) ? [
    ['faculty', 'إدارة المدرسين', ADMINISTRATIVE_ACCESS.facultyView], ['deans', 'عمداء الكليات', ADMINISTRATIVE_ACCESS.deansView],
    ['teaching-assignments', 'تكليفات التدريس', { allRoles: ['vice_president_administrative'], assignedPermissions: [PERMISSIONS.teachingAssignmentsView], actualUniversityScope: true }],
  ].filter(([, , access]) => canAccess(access)) : []
  const refresh = () => setReload(x => x + 1)
  const change = (key, value) => { if (pending) return; if (dirty && !window.confirm('تجاهل المسودة والانتقال؟')) return; setEditing(null); setSelection(null); setDetail(null); setParams(p => { const n = new URLSearchParams(p); if (value) n.set(key, value); else n.delete(key); if (key !== 'page') n.delete('page'); return n }) }
  const close = () => { if (pending || (dirty && !window.confirm('تجاهل المسودة وإغلاق الملف؟'))) return; ++detailSequence.current; setEditing(null); setSelection(null); setDetail(null); setMutationBlocked(false) }
  const show = async (kind, row, explicitReview = false) => {
    if (pending) return; const seq = ++detailSequence.current; setSelection({ kind, row }); setDetail(null); setDetailLoading(true); setError('')
    if (kind === 'needs' || kind === 'relationships') { setDetail(row); setDetailLoading(false); return }
    try { const json = await hrRead(`${kind === 'classification' ? 'workers' : kind}/${row.id}`); if (seq === detailSequence.current) { setDetail(json.data); if (explicitReview) setMutationBlocked(false) } }
    catch (e) { if (seq === detailSequence.current) { if ([401, 403].includes(e.status)) clearSensitive(e); else setError(hrError(e)) } } finally { if (seq === detailSequence.current) setDetailLoading(false) }
  }
  async function action(path, payload) {
    if (pending || mutationBlocked) return; setActing(true); setError('')
    try { await hrWrite(path, payload); setNotice('تم حفظ القرار.'); setSelection(null); setDetail(null); refresh() } catch (e) { if ([401, 403].includes(e.status)) clearSensitive(e); setError(hrError(e)); if (!e.status || e.status === 409 || e.status >= 500) setMutationBlocked(true) } finally { setActing(false) }
  }
  const saved = result => { const link = editing?.type === 'payrollLink'; setLinkedPayroll(link ? result : null); setEditing(null); setSelection(null); setDetail(null); setNotice(link ? 'تم ربط العامل بملف الرواتب الموجود دون تغيير التصنيف أو المبالغ.' : 'تم الحفظ.'); refresh() }
  const cols = officeColumns(section, options)
  cols.push({ key: 'actions', header: 'الإجراءات', render: row => <button type="button" className="inline-flex items-center gap-2 whitespace-nowrap rounded-[9px] border border-primary/20 px-3 py-2 text-[12px] font-bold text-primary hover:bg-primary/5 focus-visible:outline-2 focus-visible:outline-primary" onClick={() => show(section, row)}><FaEye aria-hidden="true" />عرض التفاصيل</button> })
  const r = detail?.request; const worker = detail?.employee; const candidate = detail?.candidate
  return <div dir="rtl" className="space-y-5 text-text-dark">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[12px] text-text-light">الشؤون الإدارية / مكتب الموارد البشرية — 711</p><h1 className="text-[24px] font-extrabold">مكتب الموارد البشرية</h1><p className="mt-1 text-[13px] text-text-light">احتياج ← مرشح ← مقابلات ← اعتماد ← علاقة وظيفية</p></div>{cap('recruit') && ['needs', 'candidates'].includes(section) && <button type="button" className={headerButton} onClick={() => setEditing({ type: section })}><FaPlus />{section === 'needs' ? 'إضافة احتياج' : 'إضافة مرشح'}</button>}</div>
    <HrTabs active={section} onChange={id => change('section', id)} />
    {payrollRead && <div className="flex flex-wrap justify-end"><Link to="/vp/administrative/payroll" className={`${secondaryButton} inline-flex items-center gap-2`}><FaCoins aria-hidden="true" />المحاسبة — الرواتب</Link></div>}
    <div className="flex flex-wrap gap-3 text-[12px] text-primary">{related.map(([path, title]) => <Link key={path} to={`/vp/administrative/${path}`}>{title}</Link>)}</div>
    <details className="rounded-[12px] border border-primary/15 bg-white p-4 text-[12.5px]"><summary className="cursor-pointer font-bold">إرشادات المكتب</summary><ol className="mt-3 space-y-2"><li>أدخل احتياجًا إضافيًا ومتطلبات مستقلة لكل منصب، ثم اربط المرشح بالبند الصحيح.</li><li>سجل المقابلات. لا ينشأ ملف موظف أو حساب أو راتب من مجرد الترشيح.</li><li>حدد العلاقة والنمط والتواريخ صراحة وأرسلها للاعتماد. الطلب المنتظر لا يستبدل علاقة نافذة.</li><li>استكمال العامل القديم توثيق مستقل بلا اعتماد تاريخي مختلق. الربط المالي يحتاج صلاحياته والتحقق من هوية السجلين.</li></ol></details>
    {notice && <Notice tone="success" onDismiss={() => { setNotice(''); setLinkedPayroll(null) }} action={linkedPayroll?.payroll_employee_id && payrollRead ? <Link className={secondaryButton} to={payrollFilePath(linkedPayroll.payroll_employee_id)}>فتح ملف الرواتب</Link> : null}>{notice}</Notice>}{error && <Notice tone="error" action={<button type="button" className={secondaryButton} onClick={refresh}>إعادة تحميل</button>}>{error}</Notice>}
    {options && !options.schema_ready && <Notice tone="warning">مخطط الموارد البشرية غير جاهز. لا نستنتج من ذلك أن العاملين بلا عقود؛ الخدمات السابقة مستقلة.</Notice>}
    <section id="hr-office-panel" role="tabpanel" aria-labelledby={`hr-tab-${section}`} tabIndex={0} className="space-y-4 focus-visible:outline-2 focus-visible:outline-primary">
    <h2 className="sr-only">{SECTIONS.find(([id]) => id === section)?.[1]}</h2>
    <FilterBar search={{ value: q, onChange: v => change('q', v), placeholder: 'البحث بالاسم أو الرقم أو عنوان الاحتياج…' }} filters={[{ key: 'body', value: body, onChange: v => change('body', v), placeholder: 'كل الهيئات', options: ['educational', 'administrative'].map(k => ({ value: k, label: label(k) })) }, { key: 'college', value: college, onChange: v => change('college_id', v), placeholder: 'كل الكليات', options: (options?.colleges || []).map(c => ({ value: String(c.college_id), label: c.college_name })) }]} hasActiveFilters={!!(q || body || college)} onClear={() => { if (!pending && !dirty) setParams({ section }) }} />
    <p className="text-[12px] text-text-light">{meta.total ?? '—'} سجل ضمن نطاقك — الأعداد الحالية ليست اتجاهًا تاريخيًا.</p>
    <DataTable columns={cols} rows={rows} rowKey={row => row.id} loading={loading} emptyIcon={FaUserTie} emptyTitle="لا توجد سجلات متاحة" page={page} totalPages={meta.last_page || 1} onPageChange={v => change('page', String(v))} />
    </section>
    {selection && !editing && <Dialog title={selection.kind === 'requests' ? 'طلب اعتماد العلاقة الوظيفية' : 'الملف'} onClose={close}><div className="p-6 space-y-4">{detailLoading ? <p role="status">جارٍ تحميل الملف…</p> : detail && <>
      {selection.kind === 'needs' && <><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{detail.title}</h2><HrStatus value={detail.status} /></div><Facts entries={[["الهيئة", label(detail.body)]]} /><DataTable columns={needItemColumns(options)} rows={detail.items} rowKey={item => item.id} emptyTitle="لا توجد بنود مسجلة" />{detail.items.map(i => <details key={i.id} className="rounded-[12px] border border-primary/15 p-3"><summary className="cursor-pointer text-[12.5px] font-bold">متطلبات {positionName(i, options)}</summary><div className="mt-3"><Facts entries={['education', 'specialization', 'skills', 'experience', 'notes'].map((k, at) => [['التعليم', 'الاختصاص', 'المهارات', 'الخبرة', 'الملاحظات'][at], i[k] || 'غير محدد'])} /></div></details>)}{cap('recruit') && <button type="button" className={primaryButton} onClick={() => setEditing({ type: 'needs', row: detail })}>تعديل الاحتياج</button>}</>}
      {candidate && <><h2 className="font-bold">{name(candidate)} — {label(candidate.status)}</h2><Facts entries={[["الاحتياج", detail.need.title], ['المنصب المطلوب', detail.item.job_title], ['التعليم', candidate.education], ['الاختصاص', candidate.specialization], ['المهارات', candidate.skills], ['الخبرة', candidate.experience], ['البريد', candidate.email], ['الهاتف', candidate.phone_number]]} /><h3 className="font-bold">المقابلات</h3>{detail.interviews.map(i => <div key={i.id} className="rounded-[12px] border p-3"><p>{i.scheduled_at} — {label(i.status)} — {i.participants.map(p => `${p.first_name} ${p.last_name}`).join('، ')}</p><p>{i.evaluation || 'لم يحدد تقييم'} / {i.result || 'لم تحدد نتيجة'}</p>{cap('recruit') && !['accepted', 'declined'].includes(candidate.status) && <button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'interview', row: i, context: detail })}>تعديل المقابلة</button>}</div>)}{!detail.interviews.length && <p>لا توجد مقابلات مسجلة.</p>}<div className="flex flex-wrap gap-2">{cap('recruit') && !['accepted', 'declined'].includes(candidate.status) && <><button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'candidates', row: candidate })}>تعديل البيانات</button><button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'interview', context: detail })}>إضافة مقابلة</button><button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'decline', context: detail })}>اعتذار مع السبب</button></>}{cap('prepare') && !['accepted', 'declined'].includes(candidate.status) && <button type="button" className={primaryButton} onClick={() => setEditing({ type: 'relationship', candidate: detail })}>إعداد القبول المقترح</button>}</div></>}
      {worker && !r && <><h2 className="font-bold">{name(worker)} — {worker.employee_number}</h2><Facts entries={[["الهيئة الحالية", worker.current_body ? label(worker.current_body) : detail.relationships.length ? 'لا علاقة نافذة حاليًا' : 'غير محدد'], ['ملف الهيئة التعليمية', detail.faculty ? `#${detail.faculty.faculty_member_id} — ${detail.faculty.academic_rank || 'رتبة غير محددة'}` : 'لا يوجد ملف'], ['المناصب المسجلة', detail.positions.map(p => `${options.positions.find(x => x.position_id === p.position_id)?.position_title || p.position_id}: ${p.start_date} — ${p.end_date || 'قيد مفتوح'}`).join('؛ ') || 'لا توجد قيود'], ['الانتماءات', detail.affiliations.map(a => `${options.units.find(u => u.organizational_unit_id === a.organizational_unit_id)?.unit_name || a.organizational_unit_id}: ${a.start_date} — ${a.end_date || 'مفتوح'}`).join('؛ ') || 'لا توجد قيود']]} /><h3 className="font-bold">العلاقات المسجلة</h3>{detail.relationships.map(rel => <Relation key={rel.id} row={rel} options={options} />)}{!detail.relationships.length && <Notice>العلاقة غير موثقة. عدم الاستكمال لا يعطّل الحساب أو التدريس أو الرواتب.</Notice>}<div className="flex flex-wrap gap-2">{cap('classify') && !detail.relationships.length && <button type="button" className={primaryButton} onClick={() => setEditing({ type: 'relationship', worker: detail, classification: true })}>استكمال التصنيف</button>}{cap('prepare') && <button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'relationship', worker: detail })}>إصدار / تجديد / تحويل</button>}</div><Link className="font-bold text-primary text-[12.5px]" to={workerFilePath(worker.employee_id)}>فتح صفحة العامل — السجل وPDF</Link><PayrollLinkStatus detail={detail} canView={payrollRead} canLink={cap('payrollLink')} onLink={() => setEditing({ type: 'payrollLink', context: detail })} /></>}
      {r && <><h2 className="font-bold">{label(r.kind)} — {label(r.status)}</h2><Notice>الطلب المنتظر لا يستبدل العلاقة الحالية. النسخة المرسلة: {r.submission_version}</Notice><Relation row={r.proposal} options={options} /><p>سبب الطلب: {r.reason}</p><p>ملاحظة المراجعة: {r.review_note || '—'}</p>{detail.candidate_context && <><p>المرشح: {name(detail.candidate_context.candidate)} — التعليم: {detail.candidate_context.candidate.education || 'غير محدد'}</p>{detail.candidate_context.interviews.map(i => <p key={i.id}>المقابلة {i.scheduled_at}: {i.evaluation || '—'} / {i.result || '—'}</p>)}</>}{detail.employee && <p>الموظف: {name(detail.employee)} — {detail.employee.employee_number}</p>}<div className="flex flex-wrap gap-2">{cap('prepare') && requestEditable(r) && <><button type="button" className={secondaryButton} onClick={() => setEditing({ type: 'relationship', request: r, candidate: detail.candidate_context, worker: detail.employee ? { employee: detail.employee, relationships: [] } : null })}>تصحيح الطلب</button><button type="button" className={primaryButton} disabled={acting || mutationBlocked} onClick={() => action(`requests/${r.id}/submit`, { revision: r.revision })}>{r.status === 'returned' ? 'إعادة التقديم' : 'إرسال للاعتماد'}</button></>}{cap('prepare') && ['draft', 'returned', 'submitted'].includes(r.status) && !r.materialized_at && <button type="button" className={secondaryButton} disabled={acting || mutationBlocked} onClick={() => setEditing({ type: 'cancelRequest', context: detail })}>إلغاء الطلب مع حفظ التاريخ</button>}{(r.employee_id || detail.candidate_context?.candidate?.employee_id) && <Link className={secondaryButton} to={workerFilePath(r.employee_id || detail.candidate_context.candidate.employee_id)}>فتح ملف العامل</Link>}{cap('review') && r.status === 'submitted' && <>{['approve', 'return', 'reject'].map((decision, i) => <button type="button" key={decision} disabled={acting || mutationBlocked} className={i ? secondaryButton : primaryButton} onClick={() => setEditing({ type: 'decision', context: detail, decision })}>{['اعتماد', 'إرجاع للتعديل', 'رفض'][i]}</button>)}</>}</div></>}
      {selection.kind === 'relationships' && <><Relation row={detail} options={options} /><button type="button" className={secondaryButton} onClick={() => show('workers', { id: detail.employee_id })}>فتح الموظف</button></>}
      {detail.events && <Events events={detail.events} />}{mutationBlocked && <Notice tone="warning" action={<button type="button" className={secondaryButton} onClick={() => show(selection.kind, selection.row, true)}>عرض الحالة الحالية</button>}>لم نكرر الطلب. راجع النتيجة الحالية قبل إجراء آخر.</Notice>}
    </>}</div></Dialog>}
    {editing && options && <HrEditor editing={editing} options={options} onClose={() => setEditing(null)} onSaved={saved} onGuard={onGuard} onAccessLost={clearSensitive} />}
    {blocker.state === 'blocked' && <Dialog title="تغييرات غير محفوظة" onClose={() => blocker.reset()} footer={<><button type="button" className={secondaryButton} onClick={() => blocker.reset()}>البقاء ومتابعة العمل</button><button type="button" className={primaryButton} disabled={pending} onClick={() => blocker.proceed()}>تجاهل المسودة والانتقال</button></>}><p className="p-6">{pending ? 'انتظر انتهاء العملية؛ لا يمكن مغادرة الصفحة أثناء الحفظ.' : 'هل تريد تجاهل المسودة والانتقال إلى الوجهة المختارة؟'}</p></Dialog>}
  </div>
}

function HrEditor({ editing, options, ...rest }) {
  const e = editing; const c = e.context
  if (e.type === 'cancelRequest') return <Editor {...rest} title="إلغاء الطلب مع حفظ التاريخ" initial={{ reason: '', confirmed: false }} write={f => hrWrite(`requests/${c.request.id}/cancel`, { ...f, revision: c.request.revision })}>{(f, set) => <><Notice>الطلب وعناصره ومراجعاته السابقة تبقى محفوظة. لا تلغى علاقة معتمدة بهذا الإجراء.</Notice><Input title="سبب الإلغاء" value={f.reason} set={v => set(s => ({ ...s, reason: v }))} required /><label className="flex gap-2"><input type="checkbox" checked={f.confirmed} required onChange={ev => set(s => ({ ...s, confirmed: ev.target.checked }))} />أؤكد إلغاء هذا الطلب مع حفظ تاريخه.</label></>}</Editor>
  if (e.type === 'needs') return <NeedEditor {...rest} options={options} row={e.row} />
  if (e.type === 'candidates') return <CandidateEditor {...rest} row={e.row} />
  if (e.type === 'relationship') return <RelationshipEditor {...rest} {...e} options={options} />
  if (e.type === 'interview') return <Editor {...rest} title="المقابلة" initial={{ scheduled_at: e.row?.scheduled_at?.replace(' ', 'T').slice(0, 16) || '', status: e.row?.status || 'scheduled', notes: e.row?.notes || '', evaluation: e.row?.evaluation || '', result: e.row?.result || '', participants: e.row?.participants.map(p => ({ id: p.employee_id, name: name(p) })) || [] }} write={f => hrWrite(`candidates/${c.candidate.id}/interviews${e.row ? `/${e.row.id}` : ''}`, { scheduled_at: f.scheduled_at, status: f.status, notes: f.notes, evaluation: f.evaluation, result: f.result, participant_ids: f.participants.map(p => p.id), candidate_revision: c.candidate.revision, ...(e.row ? { revision: e.row.revision } : {}) }, e.row ? 'PATCH' : 'POST')}>
    {(f, set) => <><Input title="الموعد" type="datetime-local" value={f.scheduled_at} set={v => set(s => ({ ...s, scheduled_at: v }))} required /><Select title="الحالة" value={f.status} set={v => set(s => ({ ...s, status: v }))} choices={['scheduled', 'completed', 'cancelled'].map(k => [k, label(k)])} /><Lookup title="أضف قائمًا بالمقابلة" path="workers" set={(id, row) => { if (row) set(s => ({ ...s, participants: [...s.participants.filter(p => p.id !== Number(id)), { id: Number(id), name: `${row.employee_number} — ${name(row)}` }] })) }} describe={r => `${r.employee_number} — ${name(r)}`} /><ul>{f.participants.map(p => <li key={p.id}>{p.name} <button type="button" className={secondaryButton} onClick={() => set(s => ({ ...s, participants: s.participants.filter(x => x.id !== p.id) }))}>إزالة</button></li>)}</ul>{['notes', 'evaluation', 'result'].map((k, i) => <Input key={k} title={['الملاحظات', 'التقييم', 'النتيجة'][i]} value={f[k]} set={v => set(s => ({ ...s, [k]: v }))} />)}</>}
  </Editor>
  if (e.type === 'payrollLink') return <Editor {...rest} title="ربط مالي صريح" initial={{ payroll: null, confirmed: false, reason: '' }} write={f => hrWrite(`workers/${c.employee.employee_id}/payroll-link`, { payroll_employee_id: f.payroll?.id, payroll_revision: f.payroll?.revision, revision: c.employee.hr_revision, confirmed: f.confirmed, reason: f.reason })}>
    {(f, set) => <><Notice>تحقق من الرقم والهوية، لا من الاسم وحده. الربط لا يغيّر التصنيف المالي أو المبالغ ولا يدمج ملفين.</Notice><Lookup title="ملف الرواتب" path="payroll-lookup" value={f.payroll?.id} set={(_, row) => set(s => ({ ...s, payroll: row }))} describe={p => `${p.employee_number} — ${p.full_name} — ${p.job_title}`} /><p>الموظف: {name(c.employee)} — {c.employee.employee_number}</p>{f.payroll && <p>الملف المالي: {f.payroll.full_name} — {f.payroll.employee_number}</p>}<Input title="سبب الربط" value={f.reason} set={v => set(s => ({ ...s, reason: v }))} required /><label className="flex gap-2"><input type="checkbox" checked={f.confirmed} onChange={ev => set(s => ({ ...s, confirmed: ev.target.checked }))} required />تحققت من أن السجلين للشخص نفسه.</label></>}
  </Editor>
  if (e.type === 'decline' || e.type === 'decision') return <Editor {...rest} title={e.type === 'decline' ? 'الاعتذار عن قبول المرشح' : 'تأكيد قرار النائب الإداري'} initial={{ note: '', confirmed: false }} write={f => {
    if (!f.confirmed) return Promise.reject({ status: 422, message: 'أكد القرار أولًا.' })
    return e.type === 'decline' ? hrWrite(`candidates/${c.candidate.id}/decline`, { revision: c.candidate.revision, reason: f.note }) : hrWrite(`requests/${c.request.id}/decide`, { revision: c.request.revision, decision: e.decision, note: f.note })
  }}>
    {(f, set) => <><Notice>{e.decision === 'approve' ? 'الاعتماد يصدر العلاقة ذريًا وفق التواريخ المحددة، دون حساب أو راتب تلقائي.' : 'السبب يبقى محفوظًا في سجل الطلب.'}</Notice><Input title="السبب / الملاحظة" value={f.note} set={v => set(s => ({ ...s, note: v }))} required={e.decision !== 'approve'} /><label className="flex gap-2"><input type="checkbox" checked={f.confirmed} onChange={ev => set(s => ({ ...s, confirmed: ev.target.checked }))} required />راجعت البيانات وأؤكد هذا القرار.</label></>}
  </Editor>
  return null
}
