import { useEffect, useState } from 'react'
import { apiRequest } from '../../../services/apiClient'

export default function ProfessorSupplementaryExams() {
  const [offerings,setOfferings]=useState([]),[selected,setSelected]=useState(null),[sheet,setSheet]=useState(null)
  const [marks,setMarks]=useState({}),[message,setMessage]=useState('')
  const loadOfferings=async()=>setOfferings((await apiRequest('/v1/professor/supplementary-exams')).data||[])
  const load=async(o)=>{setSelected(o);const data=(await apiRequest(`/v1/professor/supplementary-exams/${o.supplementary_exam_offering_id}/grades`)).data;setSheet(data);setMarks(Object.fromEntries((data.roster||[]).map(r=>[r.supplementary_exam_registration_id,r.supplementary_theoretical_mark??''])))}
  useEffect(()=>{loadOfferings().catch(e=>setMessage(e.message))},[])
  const editable=['waiting','draft','returned'].includes(sheet?.workflow_status)
  const save=async()=>{try{const data=(await apiRequest(`/v1/professor/supplementary-exams/${selected.supplementary_exam_offering_id}/grades`,{method:'PUT',body:JSON.stringify({marks:Object.entries(marks).map(([id,theoretical_mark])=>({supplementary_exam_registration_id:Number(id),theoretical_mark:Number(theoretical_mark)}))})})).data;setSheet(data);setMessage('تم حفظ المسودة النظرية.')}catch(e){setMessage(e.message)}}
  const submit=async()=>{try{const action=sheet.workflow_status==='returned'?'resubmit':'submit';setSheet((await apiRequest(`/v1/professor/supplementary-exams/${selected.supplementary_exam_offering_id}/${action}`,{method:'POST'})).data);setMessage('تم إرسال الدفعة كاملة للمراجعة.')}catch(e){setMessage(e.message)}}
  return <main className="p-6" dir="rtl"><h1 className="text-xl font-black">الامتحانات التكميلية</h1><p className="text-sm text-gray-500 mb-5">إدخال العلامة النظرية التكميلية فقط — النتيجة الرسمية والسجل الأكاديمي لا يتغيران في هذه المرحلة.</p>{message&&<p className="my-3 font-bold text-primary">{message}</p>}<div className="grid md:grid-cols-[280px_1fr] gap-4"><aside className="bg-white border rounded-xl p-3">{offerings.map(o=><button className="block w-full text-right border-b p-3" key={o.supplementary_exam_offering_id} onClick={()=>load(o)}>{o.course?.course_code} — {o.course?.course_name}</button>)}</aside><section className="bg-white border rounded-xl p-4">{!sheet?<p>اختر مقررًا مكلفًا لك.</p>:<><div className="flex justify-between mb-4"><b>{sheet.offering.course?.course_name}</b><span>الحالة: {sheet.workflow_status} — الإصدار {sheet.submission?.submission_version||1}</span></div>{sheet.submission?.review_reason&&<p className="bg-amber-50 p-3 mb-3">ملاحظات الإرجاع: {sheet.submission.review_reason}</p>}<div className="overflow-auto"><table className="w-full"><thead><tr><th>الطالب</th><th>العملي الأصلي (للقراءة)</th><th>النظري التكميلي</th><th>المجموع المتوقع</th><th>النتيجة المتوقعة</th></tr></thead><tbody>{sheet.roster.map(r=><tr className="border-t" key={r.supplementary_exam_registration_id}><td>{r.student?.student_number}</td><td className="text-center">{r.preserved_practical_mark??'—'}</td><td><input aria-label="العلامة النظرية التكميلية" className="border rounded p-2 w-24" type="number" disabled={!editable} value={marks[r.supplementary_exam_registration_id]??''} onChange={e=>setMarks({...marks,[r.supplementary_exam_registration_id]:e.target.value})}/></td><td>{r.preview?.final_mark??'—'}</td><td>{r.preview?.result_status_code??'معاينة بعد الحفظ'}</td></tr>)}</tbody></table></div><div className="mt-4 flex gap-2"><button disabled={!editable} className="bg-gray-700 text-white rounded px-4 py-2 disabled:opacity-40" onClick={save}>حفظ المسودة</button><button disabled={!editable} className="bg-primary text-white rounded px-4 py-2 disabled:opacity-40" onClick={submit}>{sheet.workflow_status==='returned'?'إعادة الإرسال':'إرسال الدفعة'}</button></div></>}</section></div></main>
}
