-- P0-1 MANUAL PREFLIGHT: read-only; no persistent object or data is changed.
SELECT VERSION() server_version,DATABASE() database_name;
SELECT u.organizational_unit_id,u.unit_code,u.unit_name,t.unit_type_id,t.type_code,p.unit_code parent_code,u.is_active FROM organizational_units u JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id WHERE u.unit_code IN ('PRES','1','2','3','4','5','6','7','8','9','11','12','13','21','22','23','31','32','41','42','51','52','71','72','73','81','82','91','92','711','712','713','714','715','721','722','723','731','732','733','734','735','736','811','812','813','821','822','823','911','912','913','914','921','922','923','924','925','VP_ADMIN','REG_OFFICE','EXAM_OFFICE') ORDER BY u.unit_code;
SELECT unit_type_id,type_code,type_name,is_active FROM organizational_unit_types WHERE type_code IN ('presidency','vice_presidency','administration','directorate','office','center','club','college','institute','lab','unit') ORDER BY type_code;
SELECT table_name,column_name,constraint_name FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name='organizational_units' AND referenced_column_name='organizational_unit_id' ORDER BY table_name,column_name;
SELECT table_name,column_name,constraint_name,'BLOCKER_UNKNOWN_REFERENCE' finding FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name='organizational_units' AND referenced_column_name='organizational_unit_id' AND table_name NOT IN ('boards','colleges','departments','employees','employee_positions','employee_unit_assignments','organizational_units') ORDER BY table_name,column_name;
SELECT IF(NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name='organizational_units' AND referenced_column_name='organizational_unit_id' AND table_name NOT IN ('boards','colleges','departments','employees','employee_positions','employee_unit_assignments','organizational_units')),1,0) can_apply,'known organizational-unit references' gate;
SELECT e.employee_id,e.employee_number,e.email,u.unit_code FROM employees e JOIN organizational_units u ON u.organizational_unit_id=e.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','7','REG_OFFICE','EXAM_OFFICE','732','735') ORDER BY u.unit_code,e.employee_id;
SELECT 'boards' source,COUNT(*) refs FROM boards x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'colleges',COUNT(*) FROM colleges x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'departments',COUNT(*) FROM departments x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'employees',COUNT(*) FROM employees x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'employee_positions',COUNT(*) FROM employee_positions x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'employee_unit_assignments',COUNT(*) FROM employee_unit_assignments x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT 'child_units',COUNT(*) FROM organizational_units x JOIN organizational_units u ON u.organizational_unit_id=x.parent_unit_id WHERE u.unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE');
SELECT r.role_code,r.is_active FROM roles r WHERE r.role_code IN ('exam_officer','registration_officer','doctor_instructor','student') ORDER BY r.role_code;
SELECT expected.username,IF(u.user_id IS NULL,'BLOCKER_MISSING_TEST_USER','READY_TO_LINK') finding,u.user_id,u.employee_id FROM (SELECT 'registrar' username UNION ALL SELECT 'exam.board') expected LEFT JOIN users u ON u.username=expected.username;
SELECT p.permission_code,p.is_active FROM permissions p WHERE p.permission_code IN ('students.view','students.manage','admissions.view','admissions.manage','academic_structure.view','courses.view','registration.view','registration.manage','exams.view','exams.manage','grades.view','grades.manage','attendance.view','attendance.manage','system_settings.view') ORDER BY p.permission_code;
SELECT e.role_code missing_role FROM (SELECT 'exam_officer' role_code UNION ALL SELECT 'registration_officer' UNION ALL SELECT 'doctor_instructor' UNION ALL SELECT 'student') e LEFT JOIN roles r ON r.role_code=e.role_code AND r.is_active=1 WHERE r.role_id IS NULL;
SELECT e.permission_code missing_permission FROM (SELECT 'students.view' permission_code UNION ALL SELECT 'students.manage' UNION ALL SELECT 'admissions.view' UNION ALL SELECT 'admissions.manage' UNION ALL SELECT 'academic_structure.view' UNION ALL SELECT 'courses.view' UNION ALL SELECT 'registration.view' UNION ALL SELECT 'registration.manage' UNION ALL SELECT 'exams.view' UNION ALL SELECT 'exams.manage' UNION ALL SELECT 'grades.view' UNION ALL SELECT 'grades.manage' UNION ALL SELECT 'attendance.view' UNION ALL SELECT 'attendance.manage' UNION ALL SELECT 'system_settings.view') e LEFT JOIN permissions p ON p.permission_code=e.permission_code AND p.is_active=1 WHERE p.permission_id IS NULL;
SELECT table_name,column_name,column_type,is_nullable,column_key FROM information_schema.columns WHERE table_schema=DATABASE() AND ((table_name='user_access_scopes') OR (table_name IN ('users','colleges','departments','academic_programs','course_offerings') AND column_name IN ('user_id','student_id','employee_id','college_id','department_id','academic_program_id','course_offering_id'))) ORDER BY table_name,ordinal_position;
SELECT table_name,index_name,column_name,non_unique FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name IN ('users','user_access_scopes') ORDER BY table_name,index_name,seq_in_index;
SELECT student_id,GROUP_CONCAT(user_id ORDER BY user_id) user_ids FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1;
SELECT employee_id,GROUP_CONCAT(user_id ORDER BY user_id) user_ids FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1;
SELECT 'linked' status,user_id,username,email,student_id,employee_id FROM users WHERE student_id IS NOT NULL OR employee_id IS NOT NULL UNION ALL SELECT 'unlinked',user_id,username,email,student_id,employee_id FROM users WHERE student_id IS NULL AND employee_id IS NULL;
SELECT u.user_id,u.username,u.email,COUNT(DISTINCT s.student_id) student_candidates,COUNT(DISTINCT e.employee_id) employee_candidates FROM users u LEFT JOIN students s ON BINARY s.email=BINARY u.email LEFT JOIN employees e ON BINARY e.email=BINARY u.email GROUP BY u.user_id,u.username,u.email HAVING student_candidates>1 OR employee_candidates>1;
SELECT ou.organizational_unit_id university_scope_reference_id,ou.unit_code,ou.unit_name FROM organizational_units ou WHERE ou.unit_code='PRES';
SET @scope_report=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes'),'SELECT s.*,CASE WHEN s.scope_type=''university'' AND old.unit_code IN (''VP_ADMIN'',''REG_OFFICE'',''EXAM_OFFICE'') THEN ''legacy-unit-scope'' ELSE ''invalid-or-orphan'' END finding FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type=''university'' AND root.organizational_unit_id=s.scope_id AND root.unit_code=''PRES'' LEFT JOIN organizational_units old ON s.scope_type=''university'' AND old.organizational_unit_id=s.scope_id LEFT JOIN colleges c ON s.scope_type=''college'' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type=''department'' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type=''program'' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type=''section'' AND co.course_offering_id=s.scope_id WHERE old.unit_code IN (''VP_ADMIN'',''REG_OFFICE'',''EXAM_OFFICE'') OR CASE s.scope_type WHEN ''university'' THEN root.organizational_unit_id WHEN ''college'' THEN c.college_id WHEN ''department'' THEN d.department_id WHEN ''program'' THEN p.academic_program_id WHEN ''section'' THEN co.course_offering_id ELSE NULL END IS NULL','SELECT ''user_access_scopes_not_created'' finding'); PREPARE stmt FROM @scope_report; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @operator_report=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes'),'SELECT u.user_id,u.username,u.email,r.role_code,''NEEDS_MANUAL_SCOPE'' finding FROM users u JOIN user_roles ur ON ur.user_id=u.user_id AND ur.is_active=1 JOIN roles r ON r.role_id=ur.role_id AND r.role_code IN (''exam_officer'',''registration_officer'') LEFT JOIN user_access_scopes s ON s.user_id=u.user_id AND s.is_active=1 LEFT JOIN organizational_units root ON s.scope_type=''university'' AND root.organizational_unit_id=s.scope_id AND root.unit_code=''PRES'' LEFT JOIN colleges c ON s.scope_type=''college'' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type=''department'' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type=''program'' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type=''section'' AND co.course_offering_id=s.scope_id GROUP BY u.user_id,u.username,u.email,r.role_code HAVING COUNT(root.organizational_unit_id)+COUNT(c.college_id)+COUNT(d.department_id)+COUNT(p.academic_program_id)+COUNT(co.course_offering_id)=0','SELECT ''user_access_scopes_not_created; operational scopes require manual review'' finding'); PREPARE stmt FROM @operator_report; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SELECT IF((SELECT COUNT(*) FROM organizational_units WHERE unit_code='PRES')<=1 AND NOT ((SELECT COUNT(*) FROM organizational_units WHERE unit_code='7')=1 AND (SELECT COUNT(*) FROM organizational_units WHERE unit_code='VP_ADMIN')=1) AND (SELECT COUNT(*) FROM roles WHERE role_code IN ('exam_officer','registration_officer','doctor_instructor','student') AND is_active=1)=4 AND (SELECT COUNT(*) FROM users WHERE username IN ('registrar','exam.board'))=2 AND (SELECT COUNT(*) FROM permissions WHERE permission_code IN ('students.view','students.manage','admissions.view','admissions.manage','academic_structure.view','courses.view','registration.view','registration.manage','exams.view','exams.manage','grades.view','grades.manage','attendance.view','attendance.manage','system_settings.view') AND is_active=1)=15 AND (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code IN ('presidency','vice_presidency','administration','directorate','office','center','club','college','institute','lab','unit') AND is_active=1)=11 AND NOT EXISTS(SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) AND NOT EXISTS(SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) AND (NOT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes') OR (EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='scope_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%') AND EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='user_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%') AND (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name IN ('user_access_scope_id','user_id','scope_type','scope_id','is_active','created_at','updated_at'))=7 AND EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND index_name='user_scope_unique' AND non_unique=0) AND EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='user_id' AND referenced_table_name='users' AND referenced_column_name='user_id'))),1,0) INTO @p01_core_ok;
SELECT @p01_core_ok core_can_apply;
-- Authoritative data gate. If the table already exists, any invalid grant or
-- an operational account without a valid grant blocks deployment only after the scope table exists.
SET @p01_scope_ok=1;
SET @scope_gate=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes'),
'SELECT IF(NOT EXISTS(SELECT 1 FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type=''university'' AND root.organizational_unit_id=s.scope_id AND root.unit_code=''PRES'' LEFT JOIN colleges c ON s.scope_type=''college'' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type=''department'' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type=''program'' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type=''section'' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN ''university'' THEN root.organizational_unit_id WHEN ''college'' THEN c.college_id WHEN ''department'' THEN d.department_id WHEN ''program'' THEN p.academic_program_id WHEN ''section'' THEN co.course_offering_id ELSE NULL END IS NULL),1,0) INTO @p01_scope_ok',
'SELECT 1 INTO @p01_scope_ok');
PREPARE stmt FROM @scope_gate; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SELECT @p01_scope_ok existing_scope_can_apply;

SELECT 'required_table_or_column' finding,req.table_name,req.column_name FROM (SELECT 'users' table_name,'student_id' column_name UNION ALL SELECT 'users','employee_id' UNION ALL SELECT 'employees','employee_number' UNION ALL SELECT 'employees','organizational_unit_id' UNION ALL SELECT 'organizational_units','unit_code' UNION ALL SELECT 'organizational_units','unit_type_id' UNION ALL SELECT 'organizational_units','parent_unit_id' UNION ALL SELECT 'organizational_unit_types','type_code' UNION ALL SELECT 'user_roles','user_id' UNION ALL SELECT 'role_permissions','role_id') req LEFT JOIN information_schema.columns c ON c.table_schema=DATABASE() AND c.table_name=req.table_name AND c.column_name=req.column_name WHERE c.column_name IS NULL;
SELECT 'missing_organizational_type' finding,expected.type_code FROM (SELECT 'presidency' type_code UNION ALL SELECT 'vice_presidency' type_code UNION ALL SELECT 'administration' type_code UNION ALL SELECT 'directorate' type_code UNION ALL SELECT 'office' type_code UNION ALL SELECT 'center' type_code UNION ALL SELECT 'club' type_code UNION ALL SELECT 'college' type_code UNION ALL SELECT 'institute' type_code UNION ALL SELECT 'lab' type_code UNION ALL SELECT 'unit' type_code) expected LEFT JOIN organizational_unit_types t ON t.type_code=expected.type_code AND t.is_active=1 WHERE t.unit_type_id IS NULL;
SELECT 'identity_index_name_conflict' finding,s.index_name,s.column_name,s.non_unique FROM information_schema.statistics s WHERE s.table_schema=DATABASE() AND s.table_name='users' AND ((s.index_name='uq_users_student_identity' AND NOT(s.column_name='student_id' AND s.non_unique=0)) OR (s.index_name='uq_users_employee_identity' AND NOT(s.column_name='employee_id' AND s.non_unique=0)));
SELECT 'deterministic_employee_conflict' finding,employee_id,employee_number,email FROM employees WHERE (email='registrar@rowad.edu' AND employee_number<>'P01-REGISTRAR') OR (email='exam.officer@rowad.edu' AND employee_number<>'P01-EXAM-OFFICER');
SELECT 'missing_reference_permission' finding,expected.permission_code FROM (SELECT 'academic_structure.view' permission_code UNION ALL SELECT 'academic_structure.manage' UNION ALL SELECT 'registration.view' UNION ALL SELECT 'grades.view') expected LEFT JOIN permissions p ON p.permission_code=expected.permission_code AND p.is_active=1 WHERE p.permission_id IS NULL;
SELECT IF(@p01_core_ok=1 AND @p01_scope_ok=1 AND NOT EXISTS(SELECT 1 FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) AND NOT EXISTS(SELECT 1 FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name='organizational_units' AND referenced_column_name='organizational_unit_id' AND table_name NOT IN ('boards','colleges','departments','employees','employee_positions','employee_unit_assignments','organizational_units')) AND (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code IN ('presidency','vice_presidency','administration','directorate','office','center','club','college','institute','lab','unit') AND is_active=1)=11 AND (SELECT COUNT(*) FROM permissions WHERE permission_code IN ('academic_structure.view','academic_structure.manage','registration.view','grades.view') AND is_active=1)=4 AND EXISTS(SELECT 1 FROM employee_types WHERE type_code='administrative' AND is_active=1) AND EXISTS(SELECT 1 FROM employee_statuses WHERE status_code='active' AND is_active=1) AND NOT EXISTS(SELECT 1 FROM information_schema.statistics s WHERE s.table_schema=DATABASE() AND s.table_name='users' AND ((s.index_name='uq_users_student_identity' AND NOT(s.column_name='student_id' AND s.non_unique=0)) OR (s.index_name='uq_users_employee_identity' AND NOT(s.column_name='employee_id' AND s.non_unique=0)))) AND NOT EXISTS(SELECT 1 FROM employees WHERE (email='registrar@rowad.edu' AND employee_number<>'P01-REGISTRAR') OR (email='exam.officer@rowad.edu' AND employee_number<>'P01-EXAM-OFFICER')) AND (SELECT COUNT(*) FROM information_schema.columns c JOIN (SELECT 'users' table_name,'student_id' column_name UNION ALL SELECT 'users','employee_id' UNION ALL SELECT 'employees','employee_number' UNION ALL SELECT 'employees','organizational_unit_id' UNION ALL SELECT 'organizational_units','unit_code' UNION ALL SELECT 'organizational_units','unit_type_id' UNION ALL SELECT 'organizational_units','parent_unit_id' UNION ALL SELECT 'organizational_unit_types','type_code' UNION ALL SELECT 'user_roles','user_id' UNION ALL SELECT 'role_permissions','role_id') req ON req.table_name=c.table_name AND req.column_name=c.column_name WHERE c.table_schema=DATABASE())=10,1,0) can_apply;
