-- P0-1 MANUAL PREFLIGHT: read-only and compatible with an empty organization/employees table.
SELECT VERSION() server_version,DATABASE() database_name;
SELECT expected.username,COUNT(u.user_id) user_matches,COUNT(u.employee_id) current_employee_links FROM (SELECT 'registrar' username UNION ALL SELECT 'exam.board') expected LEFT JOIN users u ON BINARY u.username=BINARY expected.username GROUP BY expected.username;
SELECT 'employees_empty_supported' check_name,COUNT(*) employee_count FROM employees;
SELECT type_code,is_active FROM organizational_unit_types WHERE type_code IN ('administration','center','club','college','directorate','institute','lab','office','presidency','unit','vice_presidency') ORDER BY type_code;
SELECT type_code,is_active FROM employee_types WHERE type_code='administrative';
SELECT status_code,is_active FROM employee_statuses WHERE status_code='active';
SELECT r.role_code,r.is_active FROM roles r WHERE r.role_code IN ('board_member','registration_officer','doctor_instructor','student') ORDER BY r.role_code;
SELECT p.permission_code,p.is_active FROM permissions p WHERE p.permission_code IN ('academic_structure.view','admissions.manage','admissions.view','attendance.manage','attendance.view','courses.view','exams.manage','exams.view','grades.manage','grades.view','registration.manage','registration.view','students.manage','students.view','system_settings.view') ORDER BY p.permission_code;
SELECT student_id,GROUP_CONCAT(user_id ORDER BY user_id) user_ids FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1;
SELECT employee_id,GROUP_CONCAT(user_id ORDER BY user_id) user_ids FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1;
SET @orphan_report=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes'),'SELECT s.user_access_scope_id,s.user_id,s.scope_type,s.scope_id,''ORPHAN_SCOPE'' finding FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type=''university'' AND root.organizational_unit_id=s.scope_id AND root.unit_code=''PRES'' LEFT JOIN colleges c ON s.scope_type=''college'' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type=''department'' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type=''program'' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type=''section'' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN ''university'' THEN root.organizational_unit_id WHEN ''college'' THEN c.college_id WHEN ''department'' THEN d.department_id WHEN ''program'' THEN p.academic_program_id WHEN ''section'' THEN co.course_offering_id END IS NULL','SELECT ''user_access_scopes_not_created_yet'' finding'); PREPARE stmt FROM @orphan_report; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @scope_gate=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes'),'SELECT IF(NOT EXISTS(SELECT 1 FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type=''university'' AND root.organizational_unit_id=s.scope_id AND root.unit_code=''PRES'' LEFT JOIN colleges c ON s.scope_type=''college'' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type=''department'' AND d.department_id=s.scope_id LEFT JOIN academic_programs ap ON s.scope_type=''program'' AND ap.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type=''section'' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN ''university'' THEN root.organizational_unit_id WHEN ''college'' THEN c.college_id WHEN ''department'' THEN d.department_id WHEN ''program'' THEN ap.academic_program_id WHEN ''section'' THEN co.course_offering_id END IS NULL),1,0) scope_can_apply','SELECT 1 scope_can_apply'); PREPARE stmt FROM @scope_gate; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SELECT IF((SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'registrar')=1 AND (SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'exam.board')=1 AND (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code IN ('administration','center','club','college','directorate','institute','lab','office','presidency','unit','vice_presidency') AND is_active=1)=11 AND (SELECT COUNT(*) FROM employee_types WHERE type_code='administrative' AND is_active=1)=1 AND (SELECT COUNT(*) FROM employee_statuses WHERE status_code='active' AND is_active=1)=1 AND (SELECT COUNT(*) FROM roles WHERE role_code IN ('board_member','registration_officer','doctor_instructor','student') AND is_active=1)=4 AND (SELECT COUNT(*) FROM permissions WHERE permission_code IN ('academic_structure.view','admissions.manage','admissions.view','attendance.manage','attendance.view','courses.view','exams.manage','exams.view','grades.manage','grades.view','registration.manage','registration.view','students.manage','students.view','system_settings.view') AND is_active=1)=15 AND NOT EXISTS(SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) AND NOT EXISTS(SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1),1,0) can_apply;
