-- P0-1 MANUAL APPLY: idempotent MySQL/MariaDB production migration.
CREATE TABLE IF NOT EXISTS user_access_scopes (user_access_scope_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,scope_type ENUM('university','college','department','program','section') NOT NULL,scope_id INT NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT NULL,updated_at TIMESTAMP NULL DEFAULT NULL,PRIMARY KEY(user_access_scope_id),UNIQUE KEY user_scope_unique(user_id,scope_type,scope_id),KEY active_scope_lookup(scope_type,scope_id,is_active),CONSTRAINT fk_user_access_scopes_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DELIMITER //
DROP PROCEDURE IF EXISTS p01_guard//
CREATE PROCEDURE p01_guard()
BEGIN
 IF (SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'registrar')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: registrar identity missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'exam.board')<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: exam.board identity missing or ambiguous'; END IF;
 IF EXISTS(SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: duplicate student links'; END IF;
 IF EXISTS(SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: duplicate employee links'; END IF;
 IF EXISTS(SELECT 1 FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type='university' AND root.organizational_unit_id=s.scope_id AND root.unit_code='PRES' LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs ap ON s.scope_type='program' AND ap.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN 'university' THEN root.organizational_unit_id WHEN 'college' THEN c.college_id WHEN 'department' THEN d.department_id WHEN 'program' THEN ap.academic_program_id WHEN 'section' THEN co.course_offering_id END IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: orphan access scope requires resolution'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='administration' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type administration missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='center' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type center missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='club' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type club missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='college' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type college missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='directorate' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type directorate missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='institute' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type institute missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='lab' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type lab missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='office' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type office missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='presidency' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type presidency missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='unit' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type unit missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='vice_presidency' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active unit type vice_presidency missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM employee_types WHERE type_code='administrative' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: administrative employee type missing'; END IF;
 IF (SELECT COUNT(*) FROM employee_statuses WHERE status_code='active' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: active employee status missing'; END IF;
 IF (SELECT COUNT(*) FROM roles WHERE role_code IN ('board_member','registration_officer','doctor_instructor','student') AND is_active=1)<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required roles missing'; END IF;
 IF (SELECT COUNT(*) FROM permissions WHERE permission_code IN ('academic_structure.view','admissions.manage','admissions.view','attendance.manage','attendance.view','courses.view','exams.manage','exams.view','grades.manage','grades.view','registration.manage','registration.view','students.manage','students.view','system_settings.view') AND is_active=1)<>15 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required permissions missing'; END IF;
END//
CALL p01_guard()//
DROP PROCEDURE p01_guard//
DELIMITER ;
START TRANSACTION;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT 'PRES','رئيس الجامعة',t.unit_type_id,NULL,'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '1','إدارة البحوث والدراسات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '11','مركز البحوث والدراسات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '12','مجلة جامعة الرواد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '13','المكتبة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '2','إدارة التطوير ودعم القرار',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '21','وحدة نظم المعلومات والتخطيط الاستراتيجي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '22','مكتب الجودة والاعتماد الأكاديمي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '23','إدارة المشاريع الإنتاجية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '3','إدارة التعليم الإلكتروني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '31','التعليم عن بعد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='3'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '32','التعليم الافتراضي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='3'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '4','الأمين العام للجامعة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '41','مكتب الشؤون القانونية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='4'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '42','مكتب الأمن والسلامة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='4'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '5','مديرية العلاقات العامة والإعلام',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '51','مكتب العلاقات العامة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='5'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '52','مكتب الإعلام والاتصال',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='5'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '6','وحدة التقييم والمتابعة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '7','نائب رئيس الجامعة للشؤون الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '71','مديرية الشؤون الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '711','مكتب الموارد البشرية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '712','مكتب الديوان والأرشيف',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '713','مكتب الرعاية الصحية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '714','مكتب الخدمات الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '715','المكتب التقني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '72','مديرية الشؤون المالية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '721','مكتب المحاسبة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '722','أمين الصندوق',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '723','أمين المستودع',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '73','مديرية شؤون الطلاب',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '731','مكتب الإرشاد والتوجيه',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '732','مكتب القبول والتسجيل',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '733','مكتب الخدمات الطلابية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '734','مكتب المنح والإيفاد والتبادل الطلابي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '735','إدارة الامتحانات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '736','مكتب التوثيق والتصديق',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '8','نائب رئيس الجامعة للشؤون العلمية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '81','إدارة التعليم الجامعي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='8'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '811','الكليات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='college' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '812','المعاهد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='institute' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '813','المخابر',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='lab' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '82','إدارة الدراسات العليا والبحث العلمي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='8'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '821','الماجستير',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '822','الدكتوراه',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '823','التعليم المهني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '9','نائب رئيس الجامعة للشؤون المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '91','إدارة تنمية وبناء القدرات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='9'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '911','مركز التأهيل والتدريب',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '912','مركز اللغات الأجنبية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '913','مركز تقنية المعلومات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '914','مركز ريادة الأعمال',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '92','إدارة الأنشطة المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='9'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '921','نادي الشباب والرياضة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '922','نادي التطوع والأنشطة المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '923','نادي أصدقاء البيئة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '924','مكتب المسؤولية المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '925','مكتب العدالة وحقوق الإنسان',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
-- Deterministic staff rows are created only for the two unlinked P0-1 identities. Existing employees are never repurposed.
INSERT INTO employees(employee_number,first_name,last_name,email,employee_type_id,employee_status_id,organizational_unit_id,created_at,updated_at) SELECT 'P01-REGISTRAR','P0-1','Registrar',u.email,et.employee_type_id,es.employee_status_id,ou.organizational_unit_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN employee_types et ON et.type_code='administrative' JOIN employee_statuses es ON es.status_code='active' JOIN organizational_units ou ON ou.unit_code='732' WHERE u.username='registrar' AND u.employee_id IS NULL AND NOT EXISTS(SELECT 1 FROM employees WHERE employee_number='P01-REGISTRAR');
INSERT INTO employees(employee_number,first_name,last_name,email,employee_type_id,employee_status_id,organizational_unit_id,created_at,updated_at) SELECT 'P01-EXAM-BOARD','P0-1','Exam Board',u.email,et.employee_type_id,es.employee_status_id,ou.organizational_unit_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN employee_types et ON et.type_code='administrative' JOIN employee_statuses es ON es.status_code='active' JOIN organizational_units ou ON ou.unit_code='735' WHERE u.username='exam.board' AND u.employee_id IS NULL AND NOT EXISTS(SELECT 1 FROM employees WHERE employee_number='P01-EXAM-BOARD');
UPDATE users u JOIN employees e ON e.employee_number=CASE u.username WHEN 'registrar' THEN 'P01-REGISTRAR' WHEN 'exam.board' THEN 'P01-EXAM-BOARD' END SET u.employee_id=e.employee_id WHERE u.username IN ('registrar','exam.board') AND u.employee_id IS NULL;
UPDATE employees e JOIN users u ON u.employee_id=e.employee_id JOIN organizational_units ou ON ou.unit_code=CASE u.username WHEN 'registrar' THEN '732' WHEN 'exam.board' THEN '735' END SET e.organizational_unit_id=ou.organizational_unit_id WHERE u.username IN ('registrar','exam.board');
INSERT INTO user_roles(user_id,role_id,assigned_at,is_active) SELECT u.user_id,r.role_id,CURRENT_TIMESTAMP,1 FROM users u JOIN roles r ON r.role_code=CASE u.username WHEN 'registrar' THEN 'registration_officer' WHEN 'exam.board' THEN 'board_member' END WHERE u.username IN ('registrar','exam.board') AND NOT EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.user_id AND ur.role_id=r.role_id);
UPDATE user_roles ur JOIN users u ON u.user_id=ur.user_id JOIN roles r ON r.role_id=ur.role_id SET ur.is_active=1 WHERE (u.username='registrar' AND r.role_code='registration_officer') OR (u.username='exam.board' AND r.role_code='board_member');
DROP TEMPORARY TABLE IF EXISTS p01_required_permissions;
CREATE TEMPORARY TABLE p01_required_permissions(role_code VARCHAR(80),permission_code VARCHAR(120),PRIMARY KEY(role_code,permission_code));
INSERT INTO p01_required_permissions VALUES
('board_member','students.view'),
('board_member','academic_structure.view'),
('board_member','courses.view'),
('board_member','registration.view'),
('board_member','exams.view'),
('board_member','exams.manage'),
('board_member','grades.view'),
('board_member','grades.manage'),
('board_member','system_settings.view'),
('registration_officer','students.view'),
('registration_officer','students.manage'),
('registration_officer','admissions.view'),
('registration_officer','admissions.manage'),
('registration_officer','academic_structure.view'),
('registration_officer','courses.view'),
('registration_officer','registration.view'),
('registration_officer','registration.manage'),
('registration_officer','system_settings.view'),
('doctor_instructor','courses.view'),
('doctor_instructor','students.view'),
('doctor_instructor','attendance.view'),
('doctor_instructor','attendance.manage'),
('doctor_instructor','grades.view'),
('doctor_instructor','grades.manage'),
('student','students.view'),
('student','registration.view'),
('student','grades.view'),
('student','attendance.view');
-- Insert only missing required grants: unrelated/custom grants are deliberately preserved.
INSERT INTO role_permissions(role_id,permission_id,granted_at) SELECT r.role_id,p.permission_id,CURRENT_TIMESTAMP FROM p01_required_permissions x JOIN roles r ON r.role_code=x.role_code JOIN permissions p ON p.permission_code=x.permission_code LEFT JOIN role_permissions rp ON rp.role_id=r.role_id AND rp.permission_id=p.permission_id WHERE rp.role_permission_id IS NULL;
INSERT INTO user_access_scopes(user_id,scope_type,scope_id,is_active,created_at,updated_at) SELECT u.user_id,'university',p.organizational_unit_id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN organizational_units p ON p.unit_code='PRES' WHERE u.username IN ('registrar','exam.board') ON DUPLICATE KEY UPDATE is_active=1,updated_at=CURRENT_TIMESTAMP;
DROP TEMPORARY TABLE p01_required_permissions;
COMMIT;
