-- P0-1 MANUAL APPLY. DDL is intentionally outside the DML transaction because MySQL/MariaDB implicitly commits DDL.
DELIMITER //
DROP PROCEDURE IF EXISTS p01_guard_and_ddl//
CREATE PROCEDURE p01_guard_and_ddl()
BEGIN
 IF (SELECT COUNT(*) FROM organizational_units WHERE unit_code='PRES')>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: PRES root is ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_units WHERE unit_code='7')=1 AND (SELECT COUNT(*) FROM organizational_units WHERE unit_code='VP_ADMIN')=1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: both 7 and VP_ADMIN exist; review manually'; END IF;
 IF (SELECT COUNT(*) FROM roles WHERE role_code IN ('exam_officer','registration_officer','doctor_instructor','student') AND is_active=1)<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required P0-1 role missing'; END IF;
 IF (SELECT COUNT(*) FROM users WHERE username IN ('registrar','exam_officer'))<>2 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: registrar and exam_officer test users must exist before identity linking'; END IF;
 IF (SELECT COUNT(*) FROM permissions WHERE permission_code IN ('students.view','students.manage','admissions.view','admissions.manage','academic_structure.view','courses.view','registration.view','registration.manage','exams.view','exams.manage','grades.view','grades.manage','attendance.view','attendance.manage','system_settings.view') AND is_active=1)<>15 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required P0-1 permission missing'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code IN ('presidency','vice_presidency','directorate','office') AND is_active=1)<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required organizational type missing or ambiguous'; END IF;
 IF EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND referenced_table_name='organizational_units' AND referenced_column_name='organizational_unit_id' AND table_name NOT IN ('boards','colleges','departments','employees','employee_positions','employee_unit_assignments','organizational_units')) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: unknown organizational-unit foreign key requires a reviewed migration rule'; END IF;
 IF EXISTS(SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: duplicate student links'; END IF;
 IF EXISTS(SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: duplicate employee links'; END IF;
 IF EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes') AND (NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='scope_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%') OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='user_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%') OR (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name IN ('user_access_scope_id','user_id','scope_type','scope_id','is_active','created_at','updated_at'))<>7 OR NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND index_name='user_scope_unique' AND non_unique=0) OR NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='user_access_scopes' AND column_name='user_id' AND referenced_table_name='users' AND referenced_column_name='user_id')) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: incompatible user_access_scopes structure'; END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='users' AND index_name='uq_users_student_identity') THEN ALTER TABLE users ADD UNIQUE KEY uq_users_student_identity(student_id); END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='users' AND index_name='uq_users_employee_identity') THEN ALTER TABLE users ADD UNIQUE KEY uq_users_employee_identity(employee_id); END IF;
END//
CALL p01_guard_and_ddl()//
DROP PROCEDURE p01_guard_and_ddl//
DELIMITER ;
CREATE TABLE IF NOT EXISTS user_access_scopes (user_access_scope_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,scope_type ENUM('university','college','department','program','section') NOT NULL,scope_id INT NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT NULL,updated_at TIMESTAMP NULL DEFAULT NULL,PRIMARY KEY(user_access_scope_id),UNIQUE KEY user_scope_unique(user_id,scope_type,scope_id),KEY active_scope_lookup(scope_type,scope_id,is_active),CONSTRAINT fk_user_access_scopes_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- The table DDL above may commit implicitly. This second, standalone guard runs
-- before any business DML and deliberately stops for every unresolved scope.
DELIMITER //
DROP PROCEDURE IF EXISTS p01_guard_scope_data//
CREATE PROCEDURE p01_guard_scope_data()
BEGIN
 IF EXISTS(SELECT 1 FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type='university' AND root.organizational_unit_id=s.scope_id AND root.unit_code='PRES' LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type='program' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN 'university' THEN root.organizational_unit_id WHEN 'college' THEN c.college_id WHEN 'department' THEN d.department_id WHEN 'program' THEN p.academic_program_id WHEN 'section' THEN co.course_offering_id ELSE NULL END IS NULL) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: orphan, legacy, or unsupported access scope requires manual resolution'; END IF;
END//
CALL p01_guard_scope_data()//
DROP PROCEDURE p01_guard_scope_data//
DELIMITER ;
START TRANSACTION;
DROP TEMPORARY TABLE IF EXISTS p01_expected;
CREATE TEMPORARY TABLE p01_expected(role_code VARCHAR(80),permission_code VARCHAR(120),PRIMARY KEY(role_code,permission_code));
INSERT INTO p01_expected VALUES ('exam_officer','students.view'),('exam_officer','academic_structure.view'),('exam_officer','courses.view'),('exam_officer','registration.view'),('exam_officer','exams.view'),('exam_officer','exams.manage'),('exam_officer','grades.view'),('exam_officer','grades.manage'),('exam_officer','system_settings.view'),('registration_officer','students.view'),('registration_officer','students.manage'),('registration_officer','admissions.view'),('registration_officer','admissions.manage'),('registration_officer','academic_structure.view'),('registration_officer','courses.view'),('registration_officer','registration.view'),('registration_officer','registration.manage'),('registration_officer','system_settings.view'),('doctor_instructor','courses.view'),('doctor_instructor','students.view'),('doctor_instructor','attendance.view'),('doctor_instructor','attendance.manage'),('doctor_instructor','grades.view'),('doctor_instructor','grades.manage'),('student','students.view'),('student','registration.view'),('student','grades.view'),('student','attendance.view');
INSERT INTO role_permissions(role_id,permission_id,granted_at) SELECT r.role_id,p.permission_id,CURRENT_TIMESTAMP FROM p01_expected x JOIN roles r USING(role_code) JOIN permissions p USING(permission_code) LEFT JOIN role_permissions rp ON rp.role_id=r.role_id AND rp.permission_id=p.permission_id WHERE rp.role_permission_id IS NULL;
-- Seed the official chart root as well as every descendant; no pre-existing PRES row is assumed.
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT 'PRES','رئيس الجامعة',t.unit_type_id,NULL,'Official organizational chart root',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=NULL,is_active=1,updated_at=CURRENT_TIMESTAMP;
UPDATE organizational_units SET unit_code='7',unit_name='نائب رئيس الجامعة للشؤون الإدارية',unit_type_id=(SELECT unit_type_id FROM organizational_unit_types WHERE type_code='vice_presidency' LIMIT 1) WHERE unit_code='VP_ADMIN' AND NOT EXISTS(SELECT 1 FROM (SELECT unit_code FROM organizational_units) x WHERE x.unit_code='7');
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '7','نائب رئيس الجامعة للشؤون الإدارية',t.unit_type_id,p.organizational_unit_id,'Official organizational code',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t JOIN organizational_units p ON p.unit_code='PRES' WHERE t.type_code='vice_presidency' AND NOT EXISTS(SELECT 1 FROM organizational_units WHERE unit_code IN ('7','VP_ADMIN'));
UPDATE organizational_units official JOIN organizational_unit_types t ON t.type_code='vice_presidency' JOIN organizational_units pres ON pres.unit_code='PRES' SET official.unit_name='نائب رئيس الجامعة للشؤون الإدارية',official.unit_type_id=t.unit_type_id,official.parent_unit_id=pres.organizational_unit_id,official.is_active=1 WHERE official.unit_code='7';
INSERT INTO organizational_unit_types(type_code,type_name,description,is_active,created_at,updated_at) SELECT 'administration','إدارة','Administrative unit',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM organizational_unit_types WHERE type_code='administration');
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT x.code,x.name,t.unit_type_id,p.organizational_unit_id,'Official P0-1 directorate',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM (SELECT '71' code,'مديرية الشؤون الإدارية' name UNION ALL SELECT '72','مديرية الشؤون المالية' UNION ALL SELECT '73','مديرية شؤون الطلاب') x JOIN organizational_unit_types t ON t.type_code='directorate' JOIN organizational_units p ON p.unit_code='7' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT x.code,x.name,t.unit_type_id,p.organizational_unit_id,'Official P0-1 unit',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM (SELECT '731' code,'مكتب الإرشاد والتوجيه' name,'office' type_code UNION ALL SELECT '732','مكتب القبول والتسجيل','office' UNION ALL SELECT '733','مكتب الخدمات الطلابية','office' UNION ALL SELECT '734','مكتب المنح والإيفاد والتبادل الطلابي','office' UNION ALL SELECT '735','إدارة الامتحانات','administration' UNION ALL SELECT '736','مكتب التوثيق والتدقيق','office') x JOIN organizational_unit_types t ON t.type_code=x.type_code JOIN organizational_units p ON p.unit_code='73' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),is_active=1,updated_at=CURRENT_TIMESTAMP;
UPDATE employees e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE employee_positions e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE employee_unit_assignments e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE boards e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE colleges e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE departments e JOIN organizational_units old ON old.organizational_unit_id=e.organizational_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET e.organizational_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE organizational_units child JOIN organizational_units old ON old.organizational_unit_id=child.parent_unit_id JOIN organizational_units official ON official.unit_code=CASE old.unit_code WHEN 'REG_OFFICE' THEN '732' WHEN 'EXAM_OFFICE' THEN '735' END SET child.parent_unit_id=official.organizational_unit_id WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE');
UPDATE organizational_units old SET is_active=0,description=CASE WHEN old.description LIKE '%Superseded by official unit%' THEN old.description ELSE CONCAT_WS(' ',old.description,'Superseded by official unit 732/735') END WHERE old.unit_code IN ('REG_OFFICE','EXAM_OFFICE') AND NOT EXISTS(SELECT 1 FROM employees WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM employee_positions WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM employee_unit_assignments WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM boards WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM colleges WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM departments WHERE organizational_unit_id=old.organizational_unit_id) AND NOT EXISTS(SELECT 1 FROM organizational_units WHERE parent_unit_id=old.organizational_unit_id);
-- Deterministic P0-1 test staff records and identity links. The users must already
-- exist with the documented test usernames; no password is created or reset here.
INSERT INTO employees(employee_number,first_name,last_name,email,hire_date,employee_type_id,employee_status_id,organizational_unit_id,created_at,updated_at)
SELECT 'P01-REGISTRAR','Test','Registrar','registrar@rowad.edu',CURRENT_DATE,et.employee_type_id,es.employee_status_id,ou.organizational_unit_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employee_types et JOIN employee_statuses es ON es.status_code='active' JOIN organizational_units ou ON ou.unit_code='732' WHERE et.type_code='administrative'
ON DUPLICATE KEY UPDATE first_name=VALUES(first_name),last_name=VALUES(last_name),email=VALUES(email),employee_type_id=VALUES(employee_type_id),employee_status_id=VALUES(employee_status_id),organizational_unit_id=VALUES(organizational_unit_id),updated_at=CURRENT_TIMESTAMP;
INSERT INTO employees(employee_number,first_name,last_name,email,hire_date,employee_type_id,employee_status_id,organizational_unit_id,created_at,updated_at)
SELECT 'P01-EXAM-OFFICER','Test','Exam Officer','exam.officer@rowad.edu',CURRENT_DATE,et.employee_type_id,es.employee_status_id,ou.organizational_unit_id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employee_types et JOIN employee_statuses es ON es.status_code='active' JOIN organizational_units ou ON ou.unit_code='735' WHERE et.type_code='administrative'
ON DUPLICATE KEY UPDATE first_name=VALUES(first_name),last_name=VALUES(last_name),email=VALUES(email),employee_type_id=VALUES(employee_type_id),employee_status_id=VALUES(employee_status_id),organizational_unit_id=VALUES(organizational_unit_id),updated_at=CURRENT_TIMESTAMP;
UPDATE users u JOIN employees e ON e.employee_number='P01-REGISTRAR' SET u.employee_id=e.employee_id WHERE u.username='registrar';
UPDATE users u JOIN employees e ON e.employee_number='P01-EXAM-OFFICER' SET u.employee_id=e.employee_id WHERE u.username='exam_officer';
INSERT INTO user_roles(user_id,role_id,assigned_by_user_id,assigned_at,is_active) SELECT u.user_id,r.role_id,NULL,CURRENT_TIMESTAMP,1 FROM users u JOIN roles r ON r.role_code=CASE u.username WHEN 'registrar' THEN 'registration_officer' WHEN 'exam_officer' THEN 'exam_officer' END LEFT JOIN user_roles ur ON ur.user_id=u.user_id AND ur.role_id=r.role_id WHERE u.username IN ('registrar','exam_officer') AND ur.user_role_id IS NULL;
UPDATE user_roles ur JOIN users u ON u.user_id=ur.user_id JOIN roles r ON r.role_id=ur.role_id SET ur.is_active=1 WHERE (u.username='registrar' AND r.role_code='registration_officer') OR (u.username='exam_officer' AND r.role_code='exam_officer');
INSERT INTO user_access_scopes(user_id,scope_type,scope_id,is_active,created_at,updated_at) SELECT u.user_id,'university',root.organizational_unit_id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN organizational_units root ON root.unit_code='PRES' WHERE u.username IN ('registrar','exam_officer') AND u.employee_id IS NOT NULL ON DUPLICATE KEY UPDATE is_active=1,updated_at=CURRENT_TIMESTAMP;
COMMIT;
-- MANUAL SCOPE TEMPLATE (do not run until IDs are reviewed):
-- INSERT INTO user_access_scopes(user_id,scope_type,scope_id,is_active,created_at,updated_at) SELECT u.user_id,'college',c.college_id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN colleges c ON c.college_code='REVIEWED_CODE' WHERE u.email='REVIEWED_EMAIL' ON DUPLICATE KEY UPDATE is_active=1,updated_at=CURRENT_TIMESTAMP;

-- Registrar scope template: review and replace only REVIEWED_COLLEGE_CODE before uncommenting.
-- INSERT INTO user_access_scopes(user_id,scope_type,scope_id,is_active,created_at,updated_at) SELECT u.user_id,'college',c.college_id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN colleges c ON c.college_code='REVIEWED_COLLEGE_CODE' WHERE u.username='registrar' AND u.employee_id=2 ON DUPLICATE KEY UPDATE is_active=1,updated_at=CURRENT_TIMESTAMP;
