-- P0-1 MANUAL APPLY: idempotent MySQL/MariaDB production migration.
CREATE TABLE IF NOT EXISTS user_access_scopes (user_access_scope_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,scope_type ENUM('university','college','department','program','section') NOT NULL,scope_id INT NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT NULL,updated_at TIMESTAMP NULL DEFAULT NULL,PRIMARY KEY(user_access_scope_id),UNIQUE KEY user_scope_unique(user_id,scope_type,scope_id),KEY active_scope_lookup(scope_type,scope_id,is_active),CONSTRAINT fk_user_access_scopes_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DELIMITER //
DROP PROCEDURE IF EXISTS p01_guard//
CREATE PROCEDURE p01_guard()
BEGIN
 IF (SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'registrar' AND employee_id IS NOT NULL)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: registrar must exist exactly once and link to an employee'; END IF;
 IF (SELECT COUNT(*) FROM users WHERE BINARY username=BINARY 'exam.board' AND employee_id IS NOT NULL)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: exam.board must exist exactly once and link to an employee'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='administration' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type administration missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='center' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type center missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='club' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type club missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='college' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type college missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='directorate' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type directorate missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='institute' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type institute missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='lab' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type lab missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='office' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type office missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='presidency' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type presidency missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='unit' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type unit missing or ambiguous'; END IF;
 IF (SELECT COUNT(*) FROM organizational_unit_types WHERE type_code='vice_presidency' AND is_active=1)<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STOP: required active unit type vice_presidency missing or ambiguous'; END IF;
END//
CALL p01_guard()//
DROP PROCEDURE p01_guard//
DELIMITER ;
START TRANSACTION;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT 'PRES','رئيس الجامعة',t.unit_type_id,NULL,'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '1','إدارة البحوث والدراسات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '11','مركز البحوث والدراسات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '12','مجلة جامعة الرواد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '13','المكتبة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='1'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '2','إدارة التطوير ودعم القرار',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '21','وحدة نظم المعلومات والتخطيط الاستراتيجي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '22','الجودة والاعتماد الأكاديمي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '23','مشاريع إنتاجية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='2'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '3','إدارة التعليم الإلكتروني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '31','التعليم عن بعد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='3'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '32','التعليم الافتراضي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='3'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '4','الأمين العام للجامعة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '41','مكتب الشؤون القانونية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='4'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '42','مكتب الأمن والسلامة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='4'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '5','مديرية العلاقات العامة والإعلام',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '51','مكتب العلاقات العامة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='5'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '52','مكتب الإعلام والاتصال',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='5'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '6','وحدة التقييم والمتابعة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '7','نائب رئيس الجامعة للشؤون الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '71','مديرية الشؤون الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '711','مكتب الموارد البشرية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '712','مكتب الديوان والأرشيف',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '713','مكتب الرعاية الصحية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '714','مكتب الخدمات الإدارية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '715','المكتب التقني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='71'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '72','مديرية الشؤون المالية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '721','مكتب المحاسبة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '722','أمين الصندوق',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '723','أمين المستودع',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='72'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '73','مديرية شؤون الطلاب',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='7'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='directorate' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '731','مكتب الإرشاد والتوجيه',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '732','مكتب القبول والتسجيل',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '733','مكتب الخدمات الطلابية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '734','مكتب المنح والإيفاد والتبادل الطلابي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '735','إدارة الامتحانات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '736','مكتب التوثيق والتصديق',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='73'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '8','نائب رئيس الجامعة للشؤون العلمية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '81','إدارة التعليم الجامعي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='8'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '811','الكليات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='college' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '812','المعاهد',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='institute' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '813','المخابر',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='81'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='lab' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '82','إدارة الدراسات العليا والبحث العلمي',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='8'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '821','الماجستير',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '822','الدكتوراه',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '823','التعليم المهني',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='82'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='unit' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '9','نائب رئيس الجامعة للشؤون المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='PRES'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='vice_presidency' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '91','إدارة تنمية وبناء القدرات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='9'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '911','مركز التأهيل والتدريب',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '912','مركز اللغات الأجنبية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '913','مركز تقنية المعلومات',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '914','مركز ريادة الأعمال',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='91'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='center' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '92','إدارة الأنشطة المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='9'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='administration' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '921','نادي الشباب والرياضة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '922','نادي التطوع والأنشطة المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '923','نادي أصدقاء البيئة',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='club' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '924','مكتب المسؤولية المجتمعية',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO organizational_units(unit_code,unit_name,unit_type_id,parent_unit_id,description,is_active,created_at,updated_at) SELECT '925','مكتب العدالة وحقوق الإنسان',t.unit_type_id,(SELECT organizational_unit_id FROM organizational_units WHERE unit_code='92'),'Official organizational chart',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM organizational_unit_types t WHERE t.type_code='office' ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),unit_type_id=VALUES(unit_type_id),parent_unit_id=VALUES(parent_unit_id),description=VALUES(description),is_active=1,updated_at=CURRENT_TIMESTAMP;
UPDATE employees e JOIN users u ON u.employee_id=e.employee_id JOIN organizational_units ou ON ou.unit_code=CASE u.username WHEN 'registrar' THEN '732' WHEN 'exam.board' THEN '735' END SET e.organizational_unit_id=ou.organizational_unit_id WHERE BINARY u.username IN (BINARY 'registrar',BINARY 'exam.board');
INSERT INTO user_access_scopes(user_id,scope_type,scope_id,is_active,created_at,updated_at) SELECT u.user_id,'university',p.organizational_unit_id,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM users u JOIN organizational_units p ON p.unit_code='PRES' WHERE u.username IN ('registrar','exam.board') ON DUPLICATE KEY UPDATE is_active=1,updated_at=CURRENT_TIMESTAMP;
COMMIT;
