-- P0-1 MANUAL VERIFY. Every status must be PASS and detail reports must be empty.
SELECT 'root_PRES_exists' check_name,IF(COUNT(*)=1,'PASS','FAIL') status,COUNT(*) actual FROM organizational_units WHERE unit_code='PRES';
SELECT 'official_7_unique' check_name,IF(COUNT(*)=1,'PASS','FAIL') status,COUNT(*) actual FROM organizational_units WHERE unit_code='7';
SELECT 'official_children_exist' check_name,IF(COUNT(DISTINCT unit_code)=7,'PASS','FAIL') status,COUNT(DISTINCT unit_code) actual FROM organizational_units WHERE unit_code IN ('73','731','732','733','734','735','736');
SELECT 'hierarchy_and_types' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM organizational_units u LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id LEFT JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id WHERE (u.unit_code='73' AND NOT (p.unit_code<=>'7' AND t.type_code<=>'directorate')) OR (u.unit_code IN ('731','732','733','734','736') AND NOT (p.unit_code<=>'73' AND t.type_code<=>'office')) OR (u.unit_code='735' AND NOT (p.unit_code<=>'73' AND t.type_code<=>'administration'));
SELECT 'legacy_units_inactive' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM organizational_units WHERE unit_code IN ('VP_ADMIN','REG_OFFICE','EXAM_OFFICE') AND is_active=1;
SELECT 'legacy_references_removed' check_name,IF(SUM(refs)=0,'PASS','FAIL') status,SUM(refs) failures FROM (SELECT COUNT(*) refs FROM employees x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM employee_positions x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM employee_unit_assignments x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM boards x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM colleges x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM departments x JOIN organizational_units u ON u.organizational_unit_id=x.organizational_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE') UNION ALL SELECT COUNT(*) FROM organizational_units x JOIN organizational_units u ON u.organizational_unit_id=x.parent_unit_id WHERE u.unit_code IN ('REG_OFFICE','EXAM_OFFICE')) q;
SELECT 'university_scope_reference' check_name,IF(COUNT(*)=1,'PASS','FAIL') status,MAX(organizational_unit_id) reference_id FROM organizational_units WHERE unit_code='PRES';
SELECT 'invalid_orphan_scopes' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM user_access_scopes s LEFT JOIN organizational_units root ON s.scope_type='university' AND root.organizational_unit_id=s.scope_id AND root.unit_code='PRES' LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type='program' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN 'university' THEN root.organizational_unit_id WHEN 'college' THEN c.college_id WHEN 'department' THEN d.department_id WHEN 'program' THEN p.academic_program_id WHEN 'section' THEN co.course_offering_id ELSE NULL END IS NULL;
SELECT 'duplicate_student_links' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM (SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) x;
SELECT 'duplicate_employee_links' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM (SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) x;
SELECT u.user_id,u.email,r.role_code,'NEEDS_MANUAL_SCOPE' finding FROM users u JOIN user_roles ur ON ur.user_id=u.user_id AND ur.is_active=1 JOIN roles r ON r.role_id=ur.role_id AND r.role_code IN ('exam_officer','registration_officer') LEFT JOIN user_access_scopes s ON s.user_id=u.user_id AND s.is_active=1 LEFT JOIN organizational_units root ON s.scope_type='university' AND root.organizational_unit_id=s.scope_id AND root.unit_code='PRES' LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type='program' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id GROUP BY u.user_id,u.email,r.role_code HAVING COUNT(root.organizational_unit_id)+COUNT(c.college_id)+COUNT(d.department_id)+COUNT(p.academic_program_id)+COUNT(co.course_offering_id)=0;
DROP TEMPORARY TABLE IF EXISTS p01_expected;
CREATE TEMPORARY TABLE p01_expected(role_code VARCHAR(80),permission_code VARCHAR(120),PRIMARY KEY(role_code,permission_code));
INSERT INTO p01_expected VALUES ('exam_officer','students.view'),('exam_officer','academic_structure.view'),('exam_officer','courses.view'),('exam_officer','registration.view'),('exam_officer','exams.view'),('exam_officer','exams.manage'),('exam_officer','grades.view'),('exam_officer','grades.manage'),('exam_officer','system_settings.view'),('registration_officer','students.view'),('registration_officer','students.manage'),('registration_officer','admissions.view'),('registration_officer','admissions.manage'),('registration_officer','academic_structure.view'),('registration_officer','courses.view'),('registration_officer','registration.view'),('registration_officer','registration.manage'),('registration_officer','system_settings.view'),('doctor_instructor','courses.view'),('doctor_instructor','students.view'),('doctor_instructor','attendance.view'),('doctor_instructor','attendance.manage'),('doctor_instructor','grades.view'),('doctor_instructor','grades.manage'),('student','students.view'),('student','registration.view'),('student','grades.view'),('student','attendance.view');
SELECT 'permission_matrix' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM (SELECT e.role_code,e.permission_code FROM p01_expected e LEFT JOIN roles r USING(role_code) LEFT JOIN permissions p USING(permission_code) LEFT JOIN role_permissions rp ON rp.role_id=r.role_id AND rp.permission_id=p.permission_id WHERE rp.role_permission_id IS NULL UNION ALL SELECT r.role_code,p.permission_code FROM role_permissions rp JOIN roles r ON r.role_id=rp.role_id JOIN permissions p ON p.permission_id=rp.permission_id LEFT JOIN p01_expected e ON e.role_code=r.role_code AND e.permission_code=p.permission_code WHERE r.role_code IN ('exam_officer','registration_officer','doctor_instructor','student') AND e.role_code IS NULL) x;
