SELECT COUNT(*)=1 table_present FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='user_access_scopes';
SELECT scope_type,COUNT(*) grants FROM user_access_scopes WHERE is_active=1 GROUP BY scope_type;
SELECT r.role_code,p.permission_code FROM role_permissions rp JOIN roles r ON r.role_id=rp.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE r.role_code IN ('exam_officer','registration_officer','doctor_instructor','student') ORDER BY r.role_code,p.permission_code;
SELECT unit_code,unit_name,t.type_code,parent_unit_id FROM organizational_units u JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id WHERE unit_code IN ('73','731','732','733','734','735','736') ORDER BY unit_code;
SELECT u.user_id,u.email,r.role_code FROM users u JOIN user_roles ur ON ur.user_id=u.user_id AND ur.is_active=1 JOIN roles r ON r.role_id=ur.role_id AND r.role_code IN ('exam_officer','registration_officer') LEFT JOIN user_access_scopes s ON s.user_id=u.user_id AND s.is_active=1 WHERE s.user_access_scope_id IS NULL ORDER BY u.user_id;
SELECT u.user_id,u.email,'ambiguous exact email' finding,COUNT(DISTINCT s.student_id)+COUNT(DISTINCT e.employee_id) matches FROM users u LEFT JOIN students s ON BINARY s.email=BINARY u.email LEFT JOIN employees e ON BINARY e.email=BINARY u.email GROUP BY u.user_id,u.email HAVING matches>1;
SELECT user_id,scope_type,scope_id,COUNT(*) duplicates FROM user_access_scopes GROUP BY user_id,scope_type,scope_id HAVING duplicates>1;

-- Each nonzero count makes verification NOT READY.
SELECT 'invalid_or_orphan_scopes' check_name,COUNT(*) failures FROM user_access_scopes s LEFT JOIN organizational_units ou ON s.scope_type='university' AND ou.organizational_unit_id=s.scope_id AND EXISTS(SELECT 1 FROM organizational_unit_types t WHERE t.unit_type_id=ou.unit_type_id AND t.type_code='university') LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type='program' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id WHERE CASE s.scope_type WHEN 'university' THEN ou.organizational_unit_id WHEN 'college' THEN c.college_id WHEN 'department' THEN d.department_id WHEN 'program' THEN p.academic_program_id WHEN 'section' THEN co.course_offering_id ELSE NULL END IS NULL;
SELECT 'duplicate_student_identity' check_name,COUNT(*) failures FROM (SELECT student_id FROM users WHERE student_id IS NOT NULL GROUP BY student_id HAVING COUNT(*)>1) x UNION ALL SELECT 'duplicate_employee_identity',COUNT(*) FROM (SELECT employee_id FROM users WHERE employee_id IS NOT NULL GROUP BY employee_id HAVING COUNT(*)>1) y;
SELECT 'invalid_org_hierarchy' check_name,COUNT(*) failures FROM organizational_units u LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id LEFT JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id WHERE (u.unit_code='73' AND (p.unit_code<>'7' OR t.type_code<>'directorate')) OR (u.unit_code IN ('731','732','733','734','736') AND (p.unit_code<>'73' OR t.type_code<>'office')) OR (u.unit_code='735' AND (p.unit_code<>'73' OR t.type_code<>'administration'));
SELECT 'active_legacy_duplicates' check_name,COUNT(*) failures FROM organizational_units WHERE unit_code IN ('REG_OFFICE','EXAM_OFFICE') AND is_active=1;
SELECT 'operational_users_without_valid_scope' check_name,COUNT(DISTINCT u.user_id) failures FROM users u JOIN user_roles ur ON ur.user_id=u.user_id AND ur.is_active=1 JOIN roles r ON r.role_id=ur.role_id AND r.role_code IN ('exam_officer','registration_officer') LEFT JOIN user_access_scopes s ON s.user_id=u.user_id AND s.is_active=1 LEFT JOIN colleges c ON s.scope_type='college' AND c.college_id=s.scope_id LEFT JOIN departments d ON s.scope_type='department' AND d.department_id=s.scope_id LEFT JOIN academic_programs p ON s.scope_type='program' AND p.academic_program_id=s.scope_id LEFT JOIN course_offerings co ON s.scope_type='section' AND co.course_offering_id=s.scope_id LEFT JOIN organizational_units ou ON s.scope_type='university' AND ou.organizational_unit_id=s.scope_id AND EXISTS(SELECT 1 FROM organizational_unit_types t WHERE t.unit_type_id=ou.unit_type_id AND t.type_code='university') GROUP BY u.user_id HAVING COUNT(c.college_id)+COUNT(d.department_id)+COUNT(p.academic_program_id)+COUNT(co.course_offering_id)+COUNT(ou.organizational_unit_id)=0;

DROP TEMPORARY TABLE IF EXISTS p01_expected;
CREATE TEMPORARY TABLE p01_expected(role_code VARCHAR(80),permission_code VARCHAR(120),PRIMARY KEY(role_code,permission_code));
INSERT INTO p01_expected VALUES
('exam_officer','students.view'),('exam_officer','academic_structure.view'),('exam_officer','courses.view'),('exam_officer','registration.view'),('exam_officer','exams.view'),('exam_officer','exams.manage'),('exam_officer','grades.view'),('exam_officer','grades.manage'),('exam_officer','system_settings.view'),
('registration_officer','students.view'),('registration_officer','students.manage'),('registration_officer','admissions.view'),('registration_officer','admissions.manage'),('registration_officer','academic_structure.view'),('registration_officer','courses.view'),('registration_officer','registration.view'),('registration_officer','registration.manage'),('registration_officer','system_settings.view'),
('doctor_instructor','courses.view'),('doctor_instructor','students.view'),('doctor_instructor','attendance.view'),('doctor_instructor','attendance.manage'),('doctor_instructor','grades.view'),('doctor_instructor','grades.manage'),
('student','students.view'),('student','registration.view'),('student','grades.view'),('student','attendance.view');
SELECT 'permission_matrix_mismatch' check_name,COUNT(*) failures FROM (
 SELECT e.role_code,e.permission_code FROM p01_expected e LEFT JOIN roles r USING(role_code) LEFT JOIN permissions p USING(permission_code) LEFT JOIN role_permissions rp ON rp.role_id=r.role_id AND rp.permission_id=p.permission_id WHERE rp.role_permission_id IS NULL
 UNION ALL SELECT r.role_code,p.permission_code FROM role_permissions rp JOIN roles r ON r.role_id=rp.role_id JOIN permissions p ON p.permission_id=rp.permission_id LEFT JOIN p01_expected e ON e.role_code=r.role_code AND e.permission_code=p.permission_code WHERE r.role_code IN ('exam_officer','registration_officer','doctor_instructor','student') AND e.role_code IS NULL
) mismatches;
SELECT 'missing_official_org_units' check_name,7-COUNT(DISTINCT unit_code) failures FROM organizational_units WHERE unit_code IN ('73','731','732','733','734','735','736');
