-- P0-1 MANUAL VERIFY: every row in the official chart is an exact contract.
DROP TEMPORARY TABLE IF EXISTS p01_expected_chart;
CREATE TEMPORARY TABLE p01_expected_chart(unit_code VARCHAR(50) PRIMARY KEY,unit_name VARCHAR(255),type_code VARCHAR(50),parent_code VARCHAR(50) NULL);
INSERT INTO p01_expected_chart VALUES
('PRES','رئيس الجامعة','presidency',NULL),
('1','إدارة البحوث والدراسات','administration','PRES'),
('11','مركز البحوث والدراسات','center','1'),
('12','مجلة جامعة الرواد','unit','1'),
('13','المكتبة','center','1'),
('2','إدارة التطوير ودعم القرار','administration','PRES'),
('21','وحدة نظم المعلومات والتخطيط الاستراتيجي','unit','2'),
('22','الجودة والاعتماد الأكاديمي','unit','2'),
('23','مشاريع إنتاجية','unit','2'),
('3','إدارة التعليم الإلكتروني','administration','PRES'),
('31','التعليم عن بعد','unit','3'),
('32','التعليم الافتراضي','unit','3'),
('4','الأمين العام للجامعة','administration','PRES'),
('41','مكتب الشؤون القانونية','office','4'),
('42','مكتب الأمن والسلامة','office','4'),
('5','مديرية العلاقات العامة والإعلام','directorate','PRES'),
('51','مكتب العلاقات العامة','office','5'),
('52','مكتب الإعلام والاتصال','office','5'),
('6','وحدة التقييم والمتابعة','unit','PRES'),
('7','نائب رئيس الجامعة للشؤون الإدارية','vice_presidency','PRES'),
('71','مديرية الشؤون الإدارية','directorate','7'),
('711','مكتب الموارد البشرية','office','71'),
('712','مكتب الديوان والأرشيف','office','71'),
('713','مكتب الرعاية الصحية','office','71'),
('714','مكتب الخدمات الإدارية','office','71'),
('715','المكتب التقني','office','71'),
('72','مديرية الشؤون المالية','directorate','7'),
('721','مكتب المحاسبة','office','72'),
('722','أمين الصندوق','office','72'),
('723','أمين المستودع','office','72'),
('73','مديرية شؤون الطلاب','directorate','7'),
('731','مكتب الإرشاد والتوجيه','office','73'),
('732','مكتب القبول والتسجيل','office','73'),
('733','مكتب الخدمات الطلابية','office','73'),
('734','مكتب المنح والإيفاد والتبادل الطلابي','office','73'),
('735','إدارة الامتحانات','administration','73'),
('736','مكتب التوثيق والتصديق','office','73'),
('8','نائب رئيس الجامعة للشؤون العلمية','vice_presidency','PRES'),
('81','إدارة التعليم الجامعي','administration','8'),
('811','الكليات','college','81'),
('812','المعاهد','institute','81'),
('813','المخابر','lab','81'),
('82','إدارة الدراسات العليا والبحث العلمي','administration','8'),
('821','الماجستير','unit','82'),
('822','الدكتوراه','unit','82'),
('823','التعليم المهني','unit','82'),
('9','نائب رئيس الجامعة للشؤون المجتمعية','vice_presidency','PRES'),
('91','إدارة تنمية وبناء القدرات','administration','9'),
('911','مركز التأهيل والتدريب','center','91'),
('912','مركز اللغات الأجنبية','center','91'),
('913','مركز تقنية المعلومات','center','91'),
('914','مركز ريادة الأعمال','center','91'),
('92','إدارة الأنشطة المجتمعية','administration','9'),
('921','نادي الشباب والرياضة','club','92'),
('922','نادي التطوع والأنشطة المجتمعية','club','92'),
('923','نادي أصدقاء البيئة','club','92'),
('924','مكتب المسؤولية المجتمعية','office','92'),
('925','مكتب العدالة وحقوق الإنسان','office','92');
SELECT 'official_chart_exact_58' check_name,IF(COUNT(*)=0,'PASS','FAIL') status,COUNT(*) failures FROM p01_expected_chart e LEFT JOIN organizational_units u ON u.unit_code=e.unit_code AND u.unit_name=e.unit_name AND u.is_active=1 LEFT JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id AND t.type_code=e.type_code LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id WHERE u.organizational_unit_id IS NULL OR t.unit_type_id IS NULL OR NOT (p.unit_code <=> e.parent_code);
SELECT e.unit_code,e.unit_name expected_name,e.type_code expected_type,e.parent_code expected_parent,u.unit_name actual_name,t.type_code actual_type,p.unit_code actual_parent FROM p01_expected_chart e LEFT JOIN organizational_units u ON u.unit_code=e.unit_code LEFT JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id WHERE u.organizational_unit_id IS NULL OR u.unit_name<>e.unit_name OR u.is_active<>1 OR NOT (t.type_code<=>e.type_code) OR NOT (p.unit_code<=>e.parent_code);
SELECT 'staff_identity_units' check_name,IF(COUNT(*)=2,'PASS','FAIL') status,COUNT(*) actual FROM users u JOIN employees emp ON emp.employee_id=u.employee_id JOIN organizational_units ou ON ou.organizational_unit_id=emp.organizational_unit_id WHERE (u.username='registrar' AND ou.unit_code='732') OR (u.username='exam.board' AND ou.unit_code='735');
SELECT 'staff_university_scopes' check_name,IF(COUNT(DISTINCT u.user_id)=2,'PASS','FAIL') status,COUNT(DISTINCT u.user_id) actual FROM users u JOIN user_access_scopes s ON s.user_id=u.user_id AND s.scope_type='university' AND s.is_active=1 JOIN organizational_units p ON p.organizational_unit_id=s.scope_id AND p.unit_code='PRES' WHERE u.username IN ('registrar','exam.board');
SELECT 'OVERALL' check_name,IF(NOT EXISTS(SELECT 1 FROM p01_expected_chart e LEFT JOIN organizational_units u ON u.unit_code=e.unit_code AND u.unit_name=e.unit_name AND u.is_active=1 LEFT JOIN organizational_unit_types t ON t.unit_type_id=u.unit_type_id AND t.type_code=e.type_code LEFT JOIN organizational_units p ON p.organizational_unit_id=u.parent_unit_id WHERE u.organizational_unit_id IS NULL OR t.unit_type_id IS NULL OR NOT (p.unit_code<=>e.parent_code)) AND (SELECT COUNT(*) FROM users u JOIN employees emp ON emp.employee_id=u.employee_id JOIN organizational_units ou ON ou.organizational_unit_id=emp.organizational_unit_id WHERE (u.username='registrar' AND ou.unit_code='732') OR (u.username='exam.board' AND ou.unit_code='735'))=2,'PASS','FAIL') status;
DROP TEMPORARY TABLE p01_expected_chart;
