import { Notice, Pager } from '../scientific-courses/CatalogControls'
import { SCOPES, TYPES } from './programs'

const groupKey = g => `${g.requirement_scope}:${g.requirement_type}`
const courseValue = c => c ? `${SCOPES[c.requirement_scope] || 'غير مصنف'} — ${TYPES[c.course_type] || 'غير محدد'} — السنة ${c.academic_level_id ?? 'غير محددة'} — الفصل ${c.recommended_semester_id ?? 'غير محدد'} — ${c.is_active ? 'فعال' : 'غير فعال'}` : 'خارج الخطة'
export default function WorkspaceHistory({ read, page, onPage }) {
  return <section className="space-y-3 rounded-[16px] border border-primary/12 bg-white p-5"><h3 className="font-bold">سجل التغييرات</h3>{read.loading && <Notice>تحميل السجل…</Notice>}{read.error && <Notice error>{read.error.message}</Notice>}
    {read.data?.data.map(e => <details key={e.id} className="rounded-[10px] border border-primary/15 p-3 text-[12px]"><summary>{e.actor} — {e.created_at} — {e.action === 'workspace_saved' ? 'تعديل للطلاب الجدد فقط' : 'إجراء سابق'}</summary>{e.details_available && !e.after?.groups ? <div className="space-y-2">{[['course_name', 'اسم المادة'], ['course_code', 'رمز المادة'], ['credit_hours', 'الساعات المعتمدة'], ['theoretical_hours', 'الساعات النظرية'], ['practical_hours', 'الساعات العملية'], ['description', 'الوصف'], ['is_active', 'نشاط أصل المادة']].map(([field, title]) => JSON.stringify(e.before?.[field]) === JSON.stringify(e.after?.[field]) ? null : <p key={field}>{title}: {String(e.before?.[field] ?? 'غير موجود')} ← {String(e.after?.[field] ?? 'غير محدد')}</p>)}<p>تصحيح أصل المادة المشترك يظهر في ارتباطاته؛ لا يغيّر هذا العرض سجل النتائج أو إسنادات الطلاب.</p></div> : e.details_available ? <div className="space-y-2">
      {e.before.total_credit_hours !== e.after.total_credit_hours && <p>ساعات التخرج: {e.before.total_credit_hours ?? 'غير محدد'} ← {e.after.total_credit_hours ?? 'غير محدد'}</p>}
      {[...new Set([...e.before.groups, ...e.after.groups].map(groupKey))].map(key => { const old = e.before.groups.find(g => groupKey(g) === key), next = e.after.groups.find(g => groupKey(g) === key); return JSON.stringify(old) === JSON.stringify(next) ? null : <p key={key}>{SCOPES[(next || old).requirement_scope]} — {TYPES[(next || old).requirement_type]}: {old ? old.required_credit_hours ?? 'غير محدد' : 'مجموعة مفقودة'} ← {next ? next.required_credit_hours ?? 'غير محدد' : 'مجموعة مفقودة'}</p> })}
      {[...new Set([...e.before.courses, ...e.after.courses].map(c => c.course_id))].map(id => { const old = e.before.courses.find(c => c.course_id === id), next = e.after.courses.find(c => c.course_id === id); const label = e.course_labels[id]; return JSON.stringify(old) === JSON.stringify(next) ? null : <div key={id}><b>{label ? `${label.course_name} (${label.course_code})` : `مادة ${id}`}</b><p>{courseValue(old)} ← {courseValue(next)}</p></div> })}
      <p>البرامج المختارة: {e.selected_program_ids.map(id => e.selected_program_labels?.[id] || `برنامج ${id}`).join('، ')}. نطاق التطبيق: الطلاب الجدد فقط.</p>
    </div> : <p>تفاصيل القيم السابقة والجديدة غير مسجلة لهذا الإجراء.</p>}</details>)}
    {read.data?.meta.total === 0 && <Notice>لا توجد تغييرات مسجلة.</Notice>}<Pager meta={read.data?.meta} onPage={onPage} disabled={read.loading || page < 1} />
  </section>
}
