import { useEffect, useState } from 'react'
import { apiRequest } from '../../../services/apiClient'
import { calendarApi } from '../../academic-calendar/academicCalendarApi'

export default function MinimumEnrollmentQueue() {
  const [catalog, setCatalog] = useState({ academic_years: [], semesters: [] })
  const [yearId, setYearId] = useState(''); const [semesterId, setSemesterId] = useState('')
  const [rows, setRows] = useState([]); const [notes, setNotes] = useState({}); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  useEffect(() => { calendarApi.catalog(true).then(response => { const data = response?.data ?? { academic_years: [], semesters: [] }; setCatalog(data); setYearId(String(data.academic_years?.find(year => year.is_current)?.academic_year_id ?? '')); setSemesterId(String(data.semesters?.find(semester => semester.is_active)?.semester_id ?? '')) }).catch(error => setError(error?.message || 'تعذر تحميل الفترات.')) }, [])
  async function load() { if (!yearId || !semesterId) return; try { const response = await apiRequest(`/v1/vice-presidency/scientific/semester-offerings/minimum-enrollment?academic_year_id=${yearId}&semester_id=${semesterId}&per_page=100`); setRows(response?.data?.data ?? []) } catch (error) { setRows([]); setError(error?.message || 'تعذر تحميل مراجعات الحد الأدنى.') } }
  useEffect(() => { load() }, [yearId, semesterId])
  async function decide(row, decision) { const id = row.course_offering_minimum_enrollment_review_id; setBusy(`${id}-${decision}`); setError(''); try { await apiRequest(`/v1/vice-presidency/scientific/semester-offerings/minimum-enrollment/${id}/decide`, { method: 'POST', body: JSON.stringify({ decision, notes: notes[id] ?? '' }) }); await load() } catch (error) { setError(error?.message || 'تعذر حفظ القرار.') } finally { setBusy('') } }
  return <div className="space-y-5 px-2 py-6" dir="rtl"><header className="rounded-[18px] border border-primary/15 bg-white p-6"><h1 className="text-[22px] font-black">قرارات الحد الأدنى للطروحات</h1><p className="mt-2 text-[13px] text-text-light">قرار علمي مستقل لكل طرح؛ قرار الإلغاء ينتقل إلى مسار الإغلاق الثنائي ولا يلغي التسجيلات قبل اعتماد النائب الإداري.</p></header><div className="flex gap-2 rounded-[14px] bg-white p-4"><select value={yearId} onChange={event => setYearId(event.target.value)} className="rounded-[9px] border p-2">{catalog.academic_years.map(year => <option key={year.academic_year_id} value={year.academic_year_id}>{year.year_name}</option>)}</select><select value={semesterId} onChange={event => setSemesterId(event.target.value)} className="rounded-[9px] border p-2">{catalog.semesters.map(semester => <option key={semester.semester_id} value={semester.semester_id}>{semester.semester_name}</option>)}</select></div>{error ? <p className="rounded-[9px] bg-red-50 p-3 text-red-700">{error}</p> : null}<div className="space-y-3">{rows.map(row => { const id = row.course_offering_minimum_enrollment_review_id; const actionable = row.status === 'dean_recommended'; return <section key={id} className="rounded-[15px] border border-primary/12 bg-white p-4"><h2 className="font-black">{row.course?.course_code} — {row.course?.course_name}</h2><p className="text-[12px] text-text-light">المسجلون {row.enrolled_count_snapshot} / الحد الأدنى {row.minimum_enrollment_snapshot} · توصية العميد: {row.dean_recommendation ?? '—'} · الحالة: {row.status}</p>{row.dean_notes ? <p className="mt-2 text-[12px]">سبب العميد: {row.dean_notes}</p> : null}{actionable ? <div className="mt-3 flex flex-wrap gap-2"><input value={notes[id] ?? ''} onChange={event => setNotes(current => ({ ...current, [id]: event.target.value }))} placeholder="سبب القرار العلمي" className="min-w-[260px] rounded-[9px] border p-2 text-[12px]"/><button disabled={busy || (notes[id] ?? '').trim().length < 8} onClick={() => decide(row, 'continue')} className="rounded-[9px] border border-primary/25 px-3 py-2 text-primary">استمرار استثنائي</button><button disabled={busy || (notes[id] ?? '').trim().length < 8} onClick={() => decide(row, 'cancel')} className="rounded-[9px] border border-red-200 px-3 py-2 text-red-700">بدء الإلغاء الرسمي</button></div> : null}</section> })}</div></div>
}
