import { useEffect, useRef, useState } from 'react'
import { Dialog, Field, Notice, inputClass, primaryButton, secondaryButton } from '../../vice-presidency/components/GovernanceUi'
import { blankProposal, hrError, label, proposalPayload } from '../lib/hrOffice'
import { hrRead, hrWrite } from '../lib/hrApi'

export function Input({ title, value, set, type = 'text', required = false, hint, pattern, disabled = false }) { return <Field label={title} hint={hint}><input className={inputClass} type={type} value={value ?? ''} onChange={e => set(e.target.value)} required={required} pattern={pattern} disabled={disabled} /></Field> }
export function Select({ title, value, set, choices, required = false, hint, disabled = false }) { return <Field label={title} hint={hint}><select className={inputClass} value={value ?? ''} onChange={e => set(e.target.value)} required={required} disabled={disabled}><option value="">اختر…</option>{choices.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field> }
export function Lookup({ title, path, value, set, describe, pickedLabel = '' }) {
  const [q, setQ] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState(null); const [error, setError] = useState(''); const sequence = useRef(0)
  useEffect(() => {
    const seq = ++sequence.current; const abort = new AbortController(); let active = true
    const timer = setTimeout(() => { hrRead(path, { q, page }, abort.signal).then(json => { if (active && seq === sequence.current) { setData(json.data); setError('') } }).catch(e => { if (active && seq === sequence.current && e.name !== 'AbortError') setError(hrError(e)) }) }, 300)
    return () => { active = false; clearTimeout(timer); abort.abort() }
  }, [path, q, page])
  const rows = data?.rows || data?.data || []; const totalPages = data?.meta?.last_page || data?.last_page || 1
  return <div className="space-y-2"><Input title={`بحث — ${title}`} value={q} set={v => { if (v === q) return; ++sequence.current; setData(null); setQ(v); setPage(1) }} />{error && <Notice tone="error">{error}</Notice>}<Select title={title} value={value} set={id => set(id, rows.find(r => String(r.id) === id))} choices={[...(value ? [[value, pickedLabel || `اختيار محفوظ #${value}`]] : []), ...rows.filter(r => String(r.id) !== String(value)).map(r => [r.id, describe(r)])]} />{totalPages > 1 && <div className="flex gap-2"><button type="button" className={secondaryButton} disabled={page === 1} onClick={() => setPage(p => p - 1)}>السابق</button><span>{page} / {totalPages}</span><button type="button" className={secondaryButton} disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>التالي</button></div>}</div>
}

export function RelationFields({ form, set, options, forNewPerson = false, predecessors = [], needItem = null }) {
  const field = key => value => set(f => ({ ...f, [key]: value }))
  return <div className="grid grid-cols-2 gap-4 max-[560px]:grid-cols-1">
    <Select title="الهيئة" value={form.body} set={v => set(f => ({ ...f, body: v, college_id: '', organizational_unit_id: '' }))} choices={['educational', 'administrative'].map(k => [k, label(k)])} required />
    {form.body === 'educational' ? <Select title="الكلية" value={form.college_id} set={field('college_id')} choices={options.colleges.map(c => [c.college_id, c.college_name])} required /> : <Select title="الوحدة التنظيمية" value={form.organizational_unit_id} set={field('organizational_unit_id')} choices={options.units.map(u => [u.organizational_unit_id, u.unit_name])} required />}
    <Select title="العلاقة الوظيفية" value={form.relationship_type} set={v => set(f => ({ ...f, relationship_type: v, ends_on: v === 'temporary_contract' ? f.ends_on : '', work_mode: v === 'employment' ? 'full' : f.work_mode }))} choices={['temporary_contract', 'continuous_contract', 'employment'].map(k => [k, label(k)])} required />
    <Select title="نمط العمل" value={form.work_mode} set={field('work_mode')} choices={(form.relationship_type === 'employment' ? ['full'] : ['full', 'part']).map(k => [k, label(k)])} required />
    <Input title="تاريخ البداية الفعلي" type="date" value={form.starts_on} set={field('starts_on')} required />
    {form.relationship_type === 'temporary_contract' && <Input title="تاريخ النهاية المؤكد" type="date" value={form.ends_on} set={field('ends_on')} hint="اليوم السابق لنفس تاريخ البداية بعد ثلاثة أشهر؛ لا نستنتج تاريخًا من إنشاء السجل." required />}
    <Select title="المنصب المسجل" value={form.position_id} set={field('position_id')} choices={options.positions.map(p => [p.position_id, p.position_title])} disabled={!!needItem} hint={needItem ? needItem.position_id ? 'المنصب محدد في بند الاحتياج ولا يمكن استبداله في القبول.' : 'هذا البند يستخدم صفة وظيفية نصية دون منصب مسجل.' : 'وصف العلاقة لا يمنح دورًا أو تكليفًا أو تعيين عميد.'} />
    <Input title="الصفة الوظيفية" value={form.job_title} set={field('job_title')} required disabled={!!needItem} hint={needItem ? 'مستعادة من بند الاحتياج المحدد.' : undefined} />
    {predecessors.length > 0 && <Select title="العلاقة السابقة للتجديد / التحويل" value={form.predecessor_id} set={field('predecessor_id')} choices={predecessors.map(r => [r.id, `${label(r.relationship_type)} — ${r.starts_on} إلى ${r.ends_on || 'مستمر'}`])} required />}
    {forNewPerson && <><Input title="رقم الموظف — بعد الاعتماد فقط" value={form.employee_number} set={field('employee_number')} required /><Select title="نوع الموظف الحالي" value={form.employee_type_id} set={field('employee_type_id')} choices={options.employee_types.map(t => [t.employee_type_id, t.type_name])} required /><Input title="الرتبة الأكاديمية" value={form.academic_rank} set={field('academic_rank')} /><Input title="الاختصاص" value={form.specialization} set={field('specialization')} /></>}
    <Input title="الملاحظات" value={form.notes} set={field('notes')} />
  </div>
}

export function Editor({ title, initial, onClose, onSaved, write, children, onGuard, onAccessLost }) {
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [uncertain, setUncertain] = useState(false)
  const dirty = JSON.stringify(form) !== JSON.stringify(initial)
  useEffect(() => { onGuard({ dirty, busy, uncertain }); return () => onGuard({ dirty: false, busy: false, uncertain: false }) }, [dirty, busy, uncertain, onGuard])
  const close = () => { if (busy) return; if ((dirty || uncertain) && !window.confirm('هل تريد إغلاق المسودة؟ عند فقدان الرد تحقق من السجل قبل تكرار الحفظ.')) return; onClose() }
  async function submit(e) {
    e.preventDefault(); if (busy || uncertain) return; setBusy(true); setError('')
    try { const json = await write(form); onSaved(json.data) } catch (e) { if ([401, 403].includes(e.status)) onAccessLost?.(e); setError(hrError(e)); if (!e.status || e.status >= 500 || e.status === 409) setUncertain(true) } finally { setBusy(false) }
  }
  return <Dialog title={title} as="form" onSubmit={submit} onClose={close} footer={<><button type="button" className={secondaryButton} onClick={close} disabled={busy}>إغلاق</button><button type="submit" className={primaryButton} disabled={busy || uncertain}>{busy ? 'جارٍ الحفظ…' : 'حفظ'}</button></>}><div className="p-6 space-y-4">{error && <Notice tone="error">{error}</Notice>}{uncertain && <Notice tone="warning">المحاولة مقفلة حتى تراجع السجل الحالي صراحة. أغلق النافذة وافتح الملف للتحقق؛ لم نعد إرسال الطلب.</Notice>}{children(form, setForm)}</div></Dialog>
}

const emptyItem = () => ({ job_title: '', position_id: '', quantity: 1, education: '', specialization: '', skills: '', experience: '', notes: '', is_active: true })
export function NeedEditor({ row, options, ...rest }) {
  const initial = row ? { title: row.title, body: row.body, college_id: row.college_id || '', organizational_unit_id: row.organizational_unit_id || '', notes: row.notes || '', status: row.status, items: row.items.map(i => ({ ...emptyItem(), ...Object.fromEntries(Object.keys(emptyItem()).map(k => [k, i[k]])), id: i.id })) } : { title: '', body: 'educational', college_id: '', organizational_unit_id: '', notes: '', status: 'open', items: [emptyItem()] }
  return <Editor {...rest} title={row ? 'تعديل الاحتياج' : 'إضافة احتياج'} initial={initial} write={f => hrWrite(row ? `needs/${row.id}` : 'needs', { ...f, ...(row ? { revision: row.revision } : {}), college_id: f.college_id ? Number(f.college_id) : null, organizational_unit_id: f.body === 'educational' ? null : Number(f.organizational_unit_id), items: f.items.map(i => ({ ...i, quantity: Number(i.quantity), position_id: i.position_id ? Number(i.position_id) : null, is_active: !!i.is_active })) }, row ? 'PATCH' : 'POST')}>
    {(f, set) => <><div className="grid grid-cols-2 gap-4 max-[560px]:grid-cols-1"><Input title="عنوان الاحتياج" value={f.title} set={v => set(s => ({ ...s, title: v }))} required /><Select title="الهيئة" value={f.body} set={v => set(s => ({ ...s, body: v }))} choices={['educational', 'administrative'].map(k => [k, label(k)])} required />{f.body === 'educational' ? <Select title="الكلية" value={f.college_id} set={v => set(s => ({ ...s, college_id: v }))} choices={options.colleges.map(c => [c.college_id, c.college_name])} required /> : <Select title="الوحدة" value={f.organizational_unit_id} set={v => set(s => ({ ...s, organizational_unit_id: v, college_id: '' }))} choices={options.units.map(u => [u.organizational_unit_id, u.unit_name])} required />}<Select title="حالة الاحتياج" value={f.status} set={v => set(s => ({ ...s, status: v }))} choices={['open', 'closed'].map(k => [k, label(k)])} /></div>
      <Notice>العدد يمثل احتياجًا إضافيًا يحدده المكتب، لا عجزًا محسوبًا من عدد المدرسين الحاليين. التعليم والمهارات والخبرة مطلوبة لكل بند؛ يمكن كتابة وصف صريح مثل «لا تُشترط خبرة». القيم القديمة الناقصة تبقى فارغة حتى تُستكمل صراحة.</Notice>
      {f.items.map((i, index) => <fieldset key={i.id || `new-${index}`} className="rounded-[12px] border p-4 space-y-3"><legend className="px-2 font-bold">المنصب المطلوب {index + 1}</legend><div className="grid grid-cols-2 gap-3 max-[560px]:grid-cols-1">{[['job_title', 'الصفة الوظيفية'], ['quantity', 'العدد الإضافي'], ['education', 'التعليم المطلوب'], ['specialization', 'الاختصاص'], ['skills', 'المهارات'], ['experience', 'الخبرة'], ['notes', 'الملاحظات']].map(([k, name]) => <Input key={k} title={name} type={k === 'quantity' ? 'number' : 'text'} value={i[k]} required={['job_title', 'quantity', 'education', 'skills', 'experience'].includes(k)} pattern={['education', 'skills', 'experience'].includes(k) ? '.*\\S.*' : undefined} set={v => set(s => ({ ...s, items: s.items.map((r, at) => at === index ? { ...r, [k]: v } : r) }))} />)}<Select title="المنصب" value={i.position_id} set={v => set(s => ({ ...s, items: s.items.map((r, at) => at === index ? { ...r, position_id: v } : r) }))} choices={options.positions.map(p => [p.position_id, p.position_title])} /></div><label className="flex gap-2"><input type="checkbox" checked={!!i.is_active} onChange={e => set(s => ({ ...s, items: s.items.map((r, at) => at === index ? { ...r, is_active: e.target.checked } : r) }))} />بند فعال</label>{!i.id && f.items.length > 1 && <button type="button" className={secondaryButton} onClick={() => set(s => ({ ...s, items: s.items.filter((_, at) => at !== index) }))}>إزالة البند غير المحفوظ</button>}</fieldset>)}<button type="button" className={secondaryButton} onClick={() => set(s => ({ ...s, items: [...s.items, emptyItem()] }))}>إضافة منصب مطلوب</button><Input title="ملاحظات الاحتياج" value={f.notes} set={v => set(s => ({ ...s, notes: v }))} /></>}
  </Editor>
}

export function CandidateEditor({ row, ...rest }) {
  const initial = row ? Object.fromEntries(['need_item_id', 'employee_id', 'first_name', 'last_name', 'father_name', 'phone_number', 'email', 'education', 'specialization', 'skills', 'experience', 'notes'].map(k => [k, row[k] || ''])) : { need_item_id: '', employee_id: '', first_name: '', last_name: '', father_name: '', phone_number: '', email: '', education: '', specialization: '', skills: '', experience: '', notes: '' }
  const [need, setNeed] = useState(null)
  return <Editor {...rest} title="ملف المرشح" initial={initial} write={f => hrWrite(row ? `candidates/${row.id}` : 'candidates', { ...f, need_item_id: Number(f.need_item_id), employee_id: f.employee_id ? Number(f.employee_id) : null, email: f.email || null, ...(row ? { revision: row.revision } : {}) }, row ? 'PATCH' : 'POST')}>
    {(f, set) => <>{!row && <><Lookup title="الاحتياج" path="needs" value={need?.id} set={(_, selected) => { setNeed(selected); set(s => ({ ...s, need_item_id: '' })) }} describe={n => n.title} /><Select title="بند المنصب المحدد" value={f.need_item_id} set={v => set(s => ({ ...s, need_item_id: v }))} choices={(need?.items || []).map(i => [i.id, `${i.job_title} — المتبقي ${i.remaining}`])} required /></>}<Notice>لا ينشئ تسجيل المرشح أو المقابلة موظفًا أو حسابًا أو ملف رواتب. اختر ملف الموظف الموجود صراحة إذا كان المرشح عاملًا حاليًا.</Notice><div className="grid grid-cols-2 gap-4 max-[560px]:grid-cols-1">{[['first_name', 'الاسم'], ['last_name', 'الكنية'], ['father_name', 'اسم الأب'], ['phone_number', 'الهاتف'], ['email', 'البريد'], ['education', 'التعليم'], ['specialization', 'الاختصاص'], ['skills', 'المهارات'], ['experience', 'الخبرة'], ['notes', 'الملاحظات']].map(([k, name]) => <Input key={k} title={name} value={f[k]} required={['first_name', 'last_name'].includes(k)} set={v => set(s => ({ ...s, [k]: v }))} />)}</div><Lookup title="موظف موجود — اختياري" path="workers" value={f.employee_id} set={v => set(s => ({ ...s, employee_id: v }))} describe={e => `${e.employee_number} — ${e.first_name} ${e.last_name}`} /></>}
  </Editor>
}

export function RelationshipEditor({ worker, candidate, request, classification = false, options, ...rest }) {
  const proposal = request?.proposal || { ...blankProposal(), body: candidate?.need?.body || worker?.employee?.current_body || '', college_id: candidate?.need?.college_id || '', organizational_unit_id: candidate?.need?.organizational_unit_id || '', job_title: candidate?.item?.job_title || '' }
  const initial = { kind: request?.kind || (candidate ? 'accept' : 'issue'), reason: request?.reason || '', proposal: candidate ? { ...proposal, position_id: candidate.item.position_id || '', job_title: candidate.item.job_title } : proposal }
  return <Editor {...rest} title={classification ? 'استكمال البيانات القائمة' : request ? 'تصحيح طلب العلاقة' : 'إعداد علاقة وظيفية'} initial={initial} write={f => classification ? hrWrite(`workers/${worker.employee.employee_id}/classification`, { revision: worker.employee.hr_revision, reason: f.reason, proposal: proposalPayload(f.proposal) }) : hrWrite(request ? `requests/${request.id}` : 'requests', { kind: f.kind, reason: f.reason, proposal: proposalPayload(f.proposal), ...(candidate ? { candidate_id: candidate.candidate.id } : { employee_id: worker.employee.employee_id }), ...(request ? { revision: request.revision } : {}) }, request ? 'PATCH' : 'POST')}>
    {(f, set) => <><Notice>{classification ? 'توثيق العلاقة الموجودة بتواريخ يحددها المكتب. لا نختلق اعتمادًا تاريخيًا ولا نغيّر الحسابات أو العمادة أو التكليفات.' : 'العلاقة لا تصبح نافذة قبل اعتماد النائب الإداري وحلول تاريخ بدايتها. لا ينشأ حساب دخول أو ملف مالي تلقائيًا.'}</Notice>{!classification && !candidate && <Select title="نوع الإجراء" value={f.kind} set={v => set(s => ({ ...s, kind: v }))} choices={['issue', 'renew', 'convert'].map(k => [k, label(k)])} />}<RelationFields options={options} form={f.proposal} set={change => set(s => ({ ...s, proposal: typeof change === 'function' ? change(s.proposal) : change }))} needItem={candidate?.item} forNewPerson={!!candidate && !candidate.candidate.employee_id} predecessors={['renew', 'convert'].includes(f.kind) ? worker?.relationships || [] : []} /><Input title={classification ? 'سبب استكمال البيانات' : 'سبب الطلب'} value={f.reason} set={v => set(s => ({ ...s, reason: v }))} required /></>}
  </Editor>
}
