import { useState } from 'react'
import apiClient from '../../../services/apiClient'

export default function SupplementaryExamRegistrations(){
 const [period,setPeriod]=useState(''),[rows,setRows]=useState([]),[meta,setMeta]=useState(null),[message,setMessage]=useState('')
 const load=async()=>{const r=await apiClient.get(`/v1/registration-office/supplementary-exam-periods/${period}/registrations`);setRows(r.data?.data??[]);setMeta(r.data)}
 const transition=async action=>{await apiClient.post(`/v1/registration-office/supplementary-exam-periods/${period}/${action}-registration`);setMessage(action==='open'?'تم فتح التسجيل':'تم تثبيت القائمة النهائية');await load()}
 return <main dir="rtl" className="p-6"><h1 className="text-2xl font-bold">التسجيل في الامتحانات التكميلية</h1><p className="text-gray-600 my-2">لا يمكن تجاوز الأهلية الأكاديمية أو إضافة مقرر من هذه الشاشة.</p><div className="flex gap-2 my-4"><input className="border rounded p-2" value={period} onChange={e=>setPeriod(e.target.value)} placeholder="رقم الدورة"/><button className="border rounded p-2" onClick={load}>عرض القائمة</button><button className="bg-primary text-white rounded p-2" onClick={()=>transition('open')}>فتح التسجيل</button><button className="bg-red-700 text-white rounded p-2" onClick={()=>transition('close')}>إغلاق التسجيل وتثبيت القائمة</button></div>{message&&<p>{message}</p>}<h2 className="font-bold my-3">{meta?.list_status==='fixed'?'القائمة النهائية':'قائمة أولية'} — عدد المسجلين: {rows.length}</h2><div className="overflow-auto bg-white border rounded"><table className="w-full"><thead><tr><th>الطالب</th><th>المادة</th><th>البرنامج</th><th>سبب الأهلية</th><th>قناة التسجيل</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.supplementary_exam_registration_id}><td>{x.student?.student_number}</td><td>{x.offering?.course?.course_name}</td><td>{x.offering?.academic_program?.program_name}</td><td>{x.eligibility_reason}</td><td>{x.registration_channel}</td></tr>)}</tbody></table></div></main>
}
