import { useEffect, useState } from 'react'
import { apiRequest } from '../../../services/apiClient'

export default function SupplementaryExamRegistrations(){
 const [periods,setPeriods]=useState([]),[period,setPeriod]=useState(''),[rows,setRows]=useState([]),[meta,setMeta]=useState(null),[query,setQuery]=useState(''),[students,setStudents]=useState([]),[student,setStudent]=useState(null),[eligible,setEligible]=useState([]),[message,setMessage]=useState('')
 useEffect(()=>{apiRequest('/v1/supplementary-exam-registration-periods').then(payload=>setPeriods(payload?.data??[]))},[])
 const load=async()=>{if(!period)return;const payload=await apiRequest(`/v1/registration-office/supplementary-exam-periods/${period}/registrations`);setRows(payload?.data??[]);setMeta(payload)}
 useEffect(()=>{load()},[period]) // eslint-disable-line react-hooks/exhaustive-deps
 const search=async()=>{const params=new URLSearchParams({search:query,per_page:'10'});const payload=await apiRequest(`/v1/students?${params.toString()}`);setStudents(payload?.data?.data??[])}
 const selectStudent=async s=>{setStudent(s);setStudents([]);const params=new URLSearchParams({supplementary_exam_period_id:String(period),student_id:String(s.student_id),eligible:'1'});const payload=await apiRequest(`/v1/supplementary-exam-eligibility?${params.toString()}`);setEligible(payload?.data??[])}
 const transition=async action=>{await apiRequest(`/v1/registration-office/supplementary-exam-periods/${period}/${action}-registration`,{method:'POST'});setMessage(action==='open'?'تم فتح التسجيل':'تم تثبيت القائمة النهائية');await load()}
 const register=async item=>{await apiRequest('/v1/registration-office/supplementary-exam-registrations',{method:'POST',body:JSON.stringify({supplementary_exam_offering_id:item.supplementary_exam_offering_id??item.supplementary_offering_id,student_course_registration_id:item.original_registration_id})});await load()}
 const cancel=async row=>{const reason=window.prompt('سبب الإلغاء مطلوب');if(!reason?.trim())return;await apiRequest(`/v1/registration-office/supplementary-exam-registrations/${row.supplementary_exam_registration_id}/cancel`,{method:'POST',body:JSON.stringify({reason})});await load()}
 return <main dir="rtl" className="p-6"><h1 className="text-2xl font-bold">التسجيل في الامتحانات التكميلية</h1><p className="text-gray-600 my-2">لا يمكن تجاوز الأهلية الأكاديمية أو اختيار مصدر غير معتمد.</p><div className="flex flex-wrap gap-2 my-4"><select className="border rounded p-2" value={period} onChange={e=>setPeriod(e.target.value)}><option value="">اختر الدورة</option>{periods.map(p=><option key={p.supplementary_exam_period_id} value={p.supplementary_exam_period_id}>{p.period_name} — {p.status}</option>)}</select><button disabled={!period} className="bg-primary text-white rounded p-2 disabled:opacity-40" onClick={()=>transition('open')}>فتح التسجيل</button><button disabled={!period} className="bg-red-700 text-white rounded p-2 disabled:opacity-40" onClick={()=>transition('close')}>إغلاق التسجيل وتثبيت القائمة</button></div>{message&&<p>{message}</p>}<p className="font-bold">حالة النافذة: {meta?.period_status??'—'} — {meta?.list_status==='fixed'?'القائمة النهائية':'قائمة أولية'}</p><section className="my-5 border rounded p-4"><h2 className="font-bold">تسجيل طالب مؤهل</h2><div className="flex gap-2 my-2"><input className="border rounded p-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم أو اسم الطالب"/><button onClick={search}>بحث</button></div>{students.map(s=><button className="block border-b p-2" key={s.student_id} onClick={()=>selectStudent(s)}>{s.student_number} — {s.full_name??s.name}</button>)}{student&&<p className="font-bold my-2">الطالب: {student.student_number}</p>}{eligible.map(x=><div className="flex justify-between border-t p-2" key={`${x.supplementary_exam_offering_id}-${x.original_registration_id}`}><span>{x.course_name??`المقرر ${x.supplementary_exam_offering_id}`} — {x.eligibility_reason}</span><button disabled={meta?.period_status!=='registration_open'} onClick={()=>register(x)} className="text-primary disabled:opacity-40">تسجيل</button></div>)}</section><h2 className="font-bold my-3">عدد المسجلين: {rows.length}</h2><div className="overflow-auto bg-white border rounded"><table className="w-full"><thead><tr><th>الطالب</th><th>المادة</th><th>البرنامج</th><th>سبب الأهلية</th><th>الإجراء</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x.supplementary_exam_registration_id}><td>{x.student?.student_number}</td><td>{x.offering?.course?.course_name}</td><td>{x.offering?.academic_program?.program_name}</td><td>{x.eligibility_reason}</td><td><button disabled={meta?.period_status!=='registration_open'} onClick={()=>cancel(x)} className="text-red-700 disabled:opacity-40">إلغاء بسبب</button></td></tr>)}</tbody></table></div></main>
}
