-- READ ONLY. Fully qualified; no DATABASE(), SIGNAL, DELIMITER, or procedures.
SET @db_ok := (SELECT COUNT(*)=1 FROM information_schema.schemata WHERE schema_name='alrowad_uni_rust');
SET @phase4_tables := (SELECT COUNT(*)=9 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND table_name IN ('supplementary_exam_periods','supplementary_exam_period_events','supplementary_exam_offerings','supplementary_exam_offering_sources','supplementary_exam_offering_events','supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events','supplementary_exam_registrations','supplementary_exam_registration_events'));
SET @regular_tables := (SELECT COUNT(*)=6 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND table_name IN ('student_course_registrations','student_course_results','grading_policies','faculty_members','users','role_permissions'));
SET @phase4_columns := (SELECT COUNT(*)=15 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_periods' AND column_name IN ('supplementary_exam_period_id','status')) OR (table_name='supplementary_exam_offerings' AND column_name IN ('supplementary_exam_offering_id','supplementary_exam_period_id','academic_program_id','course_id')) OR (table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_course_registration_id','student_id','status','current_slot')) OR (table_name='student_course_results' AND column_name IN ('student_course_registration_id','practical_total')) OR (table_name='grading_policies' AND column_name='theoretical_max_mark')));
SET @phase4_engine := (SELECT COUNT(*)=9 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_periods','supplementary_exam_period_events','supplementary_exam_offerings','supplementary_exam_offering_sources','supplementary_exam_offering_events','supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events','supplementary_exam_registrations','supplementary_exam_registration_events') AND engine='InnoDB');
SET @phase4_indexes := (SELECT COUNT(*)>=4 FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_course_registration_id')) OR (table_name='supplementary_exam_offerings' AND column_name='supplementary_exam_offering_id')));
SET @phase4_fk := (SELECT COUNT(*)>=3 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND referenced_table_name IS NOT NULL AND ((table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_offering_id','student_course_registration_id')) OR (table_name='supplementary_exam_offerings' AND column_name='supplementary_exam_period_id')));
SET @roles_ok := (SELECT COUNT(*)=2 FROM `alrowad_uni_rust`.`roles` WHERE role_code IN ('doctor_instructor','exam_officer') AND is_active=1);
SET @module_ok := (SELECT COUNT(*)=1 FROM `alrowad_uni_rust`.`system_modules` WHERE module_code='exams' AND is_active=1);
SET @target_conflicts := (SELECT COUNT(*) FROM information_schema.tables t WHERE t.table_schema='alrowad_uni_rust' AND t.table_name IN ('supplementary_exam_grader_assignments','supplementary_exam_grade_results','supplementary_exam_grade_submissions','supplementary_exam_grade_events') AND (t.table_type<>'BASE TABLE' OR t.engine<>'InnoDB'));
SET @target_shape_conflicts := (SELECT COUNT(*) FROM information_schema.tables t WHERE t.table_schema='alrowad_uni_rust' AND t.table_name='supplementary_exam_grade_results' AND NOT EXISTS (SELECT 1 FROM information_schema.columns c WHERE c.table_schema=t.table_schema AND c.table_name=t.table_name AND c.column_name='supplementary_exam_registration_id'));
SET @ready := @db_ok AND @phase4_tables AND @regular_tables AND @phase4_columns AND @phase4_engine AND @phase4_indexes AND @phase4_fk AND @roles_ok AND @module_ok AND @target_conflicts=0 AND @target_shape_conflicts=0;
SELECT 'LEGACY' report_section,'supplementary_exam_results' object_name,IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_results'),'LEGACY_PRESERVED','ABSENT') classification;
SELECT 'TARGET' report_section,e.table_name,IF(t.table_name IS NULL,'ABSENT',IF(t.engine='InnoDB' AND (@target_shape_conflicts=0 OR e.table_name<>'supplementary_exam_grade_results'),'COMPATIBLE','CONFLICT')) classification FROM (SELECT 'supplementary_exam_grader_assignments' table_name UNION ALL SELECT 'supplementary_exam_grade_results' UNION ALL SELECT 'supplementary_exam_grade_submissions' UNION ALL SELECT 'supplementary_exam_grade_events') e LEFT JOIN information_schema.tables t ON t.table_schema='alrowad_uni_rust' AND t.table_name=e.table_name;
SELECT 'OVERALL' report_section,IF(@ready,'READY','BLOCKED') result;
