-- READ ONLY. Verification is at least as strict as preflight.
SET @database_ready := (SELECT COUNT(*)=1 FROM information_schema.schemata WHERE schema_name='alrowad_uni_rust');
SET @phase14_tables_ready := (SELECT COUNT(*)=9 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND engine='InnoDB' AND table_name IN ('supplementary_exam_periods','supplementary_exam_period_events','supplementary_exam_offerings','supplementary_exam_offering_sources','supplementary_exam_offering_events','supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events','supplementary_exam_registrations','supplementary_exam_registration_events'));
SET @phase14_columns_ready := (SELECT COUNT(*)=12 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_periods' AND column_name IN ('supplementary_exam_period_id','status')) OR (table_name='supplementary_exam_offerings' AND column_name IN ('supplementary_exam_offering_id','supplementary_exam_period_id','academic_program_id','course_id')) OR (table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_course_registration_id','student_id','status','current_slot'))));
SET @phase14_keys_ready := (SELECT COUNT(*)=3 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_offerings' AND column_name='supplementary_exam_period_id' AND referenced_table_name='supplementary_exam_periods' AND referenced_column_name='supplementary_exam_period_id') OR (table_name='supplementary_exam_registrations' AND column_name='supplementary_exam_offering_id' AND referenced_table_name='supplementary_exam_offerings' AND referenced_column_name='supplementary_exam_offering_id') OR (table_name='supplementary_exam_registrations' AND column_name='student_course_registration_id' AND referenced_table_name='student_course_registrations' AND referenced_column_name='student_course_registration_id')));
SET @regular_tables_ready := (SELECT COUNT(*)=10 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND engine='InnoDB' AND table_name IN ('student_course_registrations','student_course_results','grading_policies','faculty_members','students','users','roles','permissions','role_permissions','system_modules'));
SET @regular_columns_ready := (SELECT COUNT(*)=14 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='student_course_registrations' AND column_name IN ('student_course_registration_id','student_id')) OR (table_name='student_course_results' AND column_name IN ('student_course_registration_id','practical_total')) OR (table_name='grading_policies' AND column_name IN ('theoretical_max_mark','practical_max_mark','minimum_theoretical_mark','minimum_practical_mark','minimum_final_mark')) OR (table_name='faculty_members' AND column_name IN ('faculty_member_id','employee_id','is_active')) OR (table_name='users' AND column_name IN ('user_id','employee_id'))));
SET @dependency_types_ready := (SELECT COUNT(*)=10 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_periods' AND column_name='supplementary_exam_period_id' AND column_type='int(11)' AND is_nullable='NO') OR (table_name='supplementary_exam_offerings' AND column_name IN ('supplementary_exam_offering_id','supplementary_exam_period_id','academic_program_id','course_id') AND column_type='int(11)' AND is_nullable='NO') OR (table_name='supplementary_exam_registrations' AND column_name IN ('supplementary_exam_registration_id','supplementary_exam_offering_id','student_course_registration_id','student_id') AND column_type='int(11)' AND is_nullable='NO') OR (table_name='supplementary_exam_registrations' AND column_name='current_slot' AND data_type='tinyint' AND is_nullable='YES'));
SET @dependency_fk_signedness_ready := (SELECT COUNT(*)=3 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND ((k.table_name='supplementary_exam_offerings' AND k.column_name='supplementary_exam_period_id') OR (k.table_name='supplementary_exam_registrations' AND k.column_name IN ('supplementary_exam_offering_id','student_course_registration_id'))) AND lc.column_type=rc.column_type);
SET @rbac_dependencies_ready := (SELECT COUNT(*)=2 FROM `alrowad_uni_rust`.`roles` WHERE role_code IN ('doctor_instructor','exam_officer') AND is_active=1) AND (SELECT COUNT(*)=1 FROM `alrowad_uni_rust`.`system_modules` WHERE module_code='exams' AND is_active=1);
SET @verify_a_exists := (SELECT COUNT(*) = 1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments');
SET @verify_a_compatible := IF(@verify_a_exists, (SELECT COUNT(*)=1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND table_type='BASE TABLE' AND engine='InnoDB') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='supplementary_exam_grader_assignment_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND LOWER(extra)=LOWER('auto_increment')) AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='supplementary_exam_offering_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='faculty_member_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='current_slot' AND data_type='tinyint' AND column_type='tinyint(4)' AND is_nullable='YES' AND LOWER(column_default)=LOWER('1') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='assigned_by_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='assigned_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='ended_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='created_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND column_name='updated_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND LOWER(extra)=LOWER('on update current_timestamp()')) AND
    (SELECT COUNT(*)=9 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND index_name='PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_grader_assignment_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_offering_id,current_slot') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='faculty_member_id,current_slot') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='assigned_by_user_id') AND
    (SELECT COUNT(*)=3 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grader_assignments' AND referenced_table_name IS NOT NULL) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grader_assignments' AND k.column_name='supplementary_exam_offering_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_offerings' AND k.referenced_column_name='supplementary_exam_offering_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grader_assignments' AND k.column_name='faculty_member_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='faculty_members' AND k.referenced_column_name='faculty_member_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grader_assignments' AND k.column_name='assigned_by_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type), 0);
SET @verify_a_classification := IF(NOT @verify_a_exists,'ABSENT',IF(@verify_a_compatible,'COMPATIBLE','CONFLICT'));
SET @verify_r_exists := (SELECT COUNT(*) = 1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results');
SET @verify_r_compatible := IF(@verify_r_exists, (SELECT COUNT(*)=1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND table_type='BASE TABLE' AND engine='InnoDB') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='supplementary_exam_grade_result_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND LOWER(extra)=LOWER('auto_increment')) AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='supplementary_exam_registration_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='supplementary_exam_offering_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='student_course_registration_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='student_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='theoretical_mark' AND data_type='decimal' AND column_type='decimal(5,2)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='status' AND data_type='varchar' AND column_type='varchar(24)' AND is_nullable='NO' AND LOWER(column_default)=LOWER('draft') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='submission_version' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND LOWER(column_default)=LOWER('1') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='last_edited_by_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='published_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='created_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND column_name='updated_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND LOWER(extra)=LOWER('on update current_timestamp()')) AND
    (SELECT COUNT(*)=12 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name='PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_grade_result_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_registration_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='supplementary_exam_offering_id,status') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='student_course_registration_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='student_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='last_edited_by_user_id') AND
    (SELECT COUNT(*)=5 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_results' AND referenced_table_name IS NOT NULL) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_results' AND k.column_name='supplementary_exam_registration_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_registrations' AND k.referenced_column_name='supplementary_exam_registration_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_results' AND k.column_name='supplementary_exam_offering_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_offerings' AND k.referenced_column_name='supplementary_exam_offering_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_results' AND k.column_name='student_course_registration_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='student_course_registrations' AND k.referenced_column_name='student_course_registration_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_results' AND k.column_name='student_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='students' AND k.referenced_column_name='student_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_results' AND k.column_name='last_edited_by_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type), 0);
SET @verify_r_classification := IF(NOT @verify_r_exists,'ABSENT',IF(@verify_r_compatible,'COMPATIBLE','CONFLICT'));
SET @verify_s_exists := (SELECT COUNT(*) = 1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions');
SET @verify_s_compatible := IF(@verify_s_exists, (SELECT COUNT(*)=1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND table_type='BASE TABLE' AND engine='InnoDB') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='supplementary_exam_grade_submission_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND LOWER(extra)=LOWER('auto_increment')) AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='supplementary_exam_offering_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='grader_assignment_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='submission_version' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='status' AND data_type='varchar' AND column_type='varchar(24)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='submitted_by_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='submitted_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='reviewed_by_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='reviewed_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='review_reason' AND data_type='text' AND column_type='text' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='published_by_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='published_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='created_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND column_name='updated_at' AND data_type='timestamp' AND column_type='timestamp' AND is_nullable='NO' AND LOWER(column_default)=LOWER('current_timestamp()') AND LOWER(extra)=LOWER('on update current_timestamp()')) AND
    (SELECT COUNT(*)=14 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name='PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_grade_submission_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_offering_id,submission_version') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='grader_assignment_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='submitted_by_user_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='reviewed_by_user_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='published_by_user_id') AND
    (SELECT COUNT(*)=5 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_submissions' AND referenced_table_name IS NOT NULL) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_submissions' AND k.column_name='supplementary_exam_offering_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_offerings' AND k.referenced_column_name='supplementary_exam_offering_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_submissions' AND k.column_name='grader_assignment_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_grader_assignments' AND k.referenced_column_name='supplementary_exam_grader_assignment_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_submissions' AND k.column_name='submitted_by_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_submissions' AND k.column_name='reviewed_by_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_submissions' AND k.column_name='published_by_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type), 0);
SET @verify_s_classification := IF(NOT @verify_s_exists,'ABSENT',IF(@verify_s_compatible,'COMPATIBLE','CONFLICT'));
SET @verify_e_exists := (SELECT COUNT(*) = 1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events');
SET @verify_e_compatible := IF(@verify_e_exists, (SELECT COUNT(*)=1 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND table_type='BASE TABLE' AND engine='InnoDB') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='supplementary_exam_grade_event_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND LOWER(extra)=LOWER('auto_increment')) AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='supplementary_exam_grade_result_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='supplementary_exam_grade_submission_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='event_type' AND data_type='varchar' AND column_type='varchar(40)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='from_status' AND data_type='varchar' AND column_type='varchar(24)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='to_status' AND data_type='varchar' AND column_type='varchar(24)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='submission_version' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='theoretical_mark' AND data_type='decimal' AND column_type='decimal(5,2)' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='actor_user_id' AND data_type='int' AND column_type='int(11)' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='notes' AND data_type='text' AND column_type='text' AND is_nullable='YES' AND column_default IS NULL AND extra='') AND
    EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND column_name='created_at' AND data_type='datetime' AND column_type='datetime' AND is_nullable='NO' AND column_default IS NULL AND extra='') AND
    (SELECT COUNT(*)=11 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND index_name='PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=0 AND i.index_columns='supplementary_exam_grade_event_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='supplementary_exam_grade_result_id,created_at') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='supplementary_exam_grade_submission_id') AND
    EXISTS(SELECT 1 FROM (SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') index_columns FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique) i WHERE i.non_unique=1 AND i.index_columns='actor_user_id') AND
    (SELECT COUNT(*)=3 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_grade_events' AND referenced_table_name IS NOT NULL) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_events' AND k.column_name='supplementary_exam_grade_result_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_grade_results' AND k.referenced_column_name='supplementary_exam_grade_result_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_events' AND k.column_name='supplementary_exam_grade_submission_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='supplementary_exam_grade_submissions' AND k.referenced_column_name='supplementary_exam_grade_submission_id' AND lc.column_type=rc.column_type) AND
    EXISTS(SELECT 1 FROM information_schema.key_column_usage k JOIN information_schema.columns lc ON lc.table_schema=k.table_schema AND lc.table_name=k.table_name AND lc.column_name=k.column_name JOIN information_schema.columns rc ON rc.table_schema=k.referenced_table_schema AND rc.table_name=k.referenced_table_name AND rc.column_name=k.referenced_column_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='supplementary_exam_grade_events' AND k.column_name='actor_user_id' AND k.referenced_table_schema='alrowad_uni_rust' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id' AND lc.column_type=rc.column_type), 0);
SET @verify_e_classification := IF(NOT @verify_e_exists,'ABSENT',IF(@verify_e_compatible,'COMPATIBLE','CONFLICT'));
SET @permission_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`permissions` p LEFT JOIN `alrowad_uni_rust`.`system_modules` m ON m.module_id=p.module_id WHERE p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish') AND (p.is_active<>1 OR m.module_code<>'exams'));
SET @forbidden_mappings := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish') AND NOT ((r.role_code='doctor_instructor' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.enter')) OR (r.role_code='exam_officer' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish'))));
SET @rbac_adoption_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`permissions` p WHERE p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish') AND COALESCE(p.description,'')<>'owned:supplementary-exam-grading-phase5' AND NOT EXISTS (SELECT 1 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id WHERE rp.permission_id=p.permission_id AND ((r.role_code='doctor_instructor' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.enter')) OR (r.role_code='exam_officer' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish')))));
SET @rbac_safe := @permission_conflicts=0 AND @forbidden_mappings=0 AND @rbac_adoption_conflicts=0;
SET @permissions_ready := (SELECT COUNT(*)=5 FROM `alrowad_uni_rust`.`permissions` p JOIN `alrowad_uni_rust`.`system_modules` m ON m.module_id=p.module_id WHERE p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish') AND p.is_active=1 AND m.module_code='exams');
SET @expected_mappings := (SELECT COUNT(DISTINCT CONCAT(r.role_code,':',p.permission_code))=7 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE (r.role_code='doctor_instructor' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.enter')) OR (r.role_code='exam_officer' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish')));
SET @verify_pass := @database_ready AND @phase14_tables_ready AND @phase14_columns_ready AND @phase14_keys_ready AND @regular_tables_ready AND @regular_columns_ready AND @dependency_types_ready AND @dependency_fk_signedness_ready AND @rbac_dependencies_ready AND @verify_a_compatible AND @verify_r_compatible AND @verify_s_compatible AND @verify_e_compatible AND @permissions_ready AND @expected_mappings AND @forbidden_mappings=0 AND @permission_conflicts=0;
-- This is the only visible operator report and must remain the final statement.
SELECT 'OVERALL' AS report_section, IF(@verify_pass,'PASS','FAIL') AS result;
