-- READ ONLY verification.
SET @tables := (SELECT COUNT(*)=4 FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_type='BASE TABLE' AND engine='InnoDB' AND table_name IN ('supplementary_exam_grader_assignments','supplementary_exam_grade_results','supplementary_exam_grade_submissions','supplementary_exam_grade_events'));
SET @columns := (SELECT COUNT(*)=35 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='supplementary_exam_grader_assignments' AND column_name IN ('supplementary_exam_grader_assignment_id','supplementary_exam_offering_id','faculty_member_id','current_slot','assigned_by_user_id','assigned_at','ended_at')) OR (table_name='supplementary_exam_grade_results' AND column_name IN ('supplementary_exam_grade_result_id','supplementary_exam_registration_id','supplementary_exam_offering_id','student_course_registration_id','student_id','theoretical_mark','status','submission_version','last_edited_by_user_id','published_at')) OR (table_name='supplementary_exam_grade_submissions' AND column_name IN ('supplementary_exam_grade_submission_id','supplementary_exam_offering_id','grader_assignment_id','submission_version','status','submitted_by_user_id','submitted_at','reviewed_by_user_id','reviewed_at','review_reason','published_by_user_id','published_at')) OR (table_name='supplementary_exam_grade_events' AND column_name IN ('supplementary_exam_grade_event_id','supplementary_exam_grade_result_id','supplementary_exam_grade_submission_id','event_type','from_status','to_status'))));
SET @pk_auto := (SELECT COUNT(*)=4 FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND extra LIKE '%auto_increment%' AND column_name IN ('supplementary_exam_grader_assignment_id','supplementary_exam_grade_result_id','supplementary_exam_grade_submission_id','supplementary_exam_grade_event_id'));
SET @unique := (SELECT COUNT(DISTINCT CONCAT(table_name,':',index_name))>=3 FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND ((table_name='supplementary_exam_grader_assignments' AND column_name IN ('supplementary_exam_offering_id','current_slot')) OR (table_name='supplementary_exam_grade_results' AND column_name='supplementary_exam_registration_id') OR (table_name='supplementary_exam_grade_submissions' AND column_name IN ('supplementary_exam_offering_id','submission_version'))));
SET @fks := (SELECT COUNT(*)>=14 FROM information_schema.key_column_usage WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_grader_assignments','supplementary_exam_grade_results','supplementary_exam_grade_submissions','supplementary_exam_grade_events') AND referenced_table_name IS NOT NULL);
SET @permissions := (SELECT COUNT(*)=5 FROM `alrowad_uni_rust`.`permissions` p JOIN `alrowad_uni_rust`.`system_modules` m ON m.module_id=p.module_id WHERE m.module_code='exams' AND p.is_active=1 AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish'));
SET @matrix := (SELECT COUNT(DISTINCT CONCAT(r.role_code,':',p.permission_code))=7 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE (r.role_code='doctor_instructor' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.enter')) OR (r.role_code='exam_officer' AND p.permission_code IN ('supplementary_exams.grades.view','supplementary_exams.grades.assign','supplementary_exams.grades.enter','supplementary_exams.grades.review','supplementary_exams.grades.publish')));
SET @forbidden := (SELECT COUNT(*)=0 FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE p.permission_code IN ('supplementary_exams.grades.assign','supplementary_exams.grades.review','supplementary_exams.grades.publish') AND r.role_code<>'exam_officer');
SELECT 'OVERALL' report_section,IF(@tables AND @columns AND @pk_auto AND @unique AND @fks AND @permissions AND @matrix AND @forbidden,'PASS','FAIL') result;
