-- READ ONLY. Accept deployment only when the final row is OVERALL | PASS.
USE `alrowad_uni_rust`;

SET @srd_verify_core_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN (
  'academic_years','semesters','users','students','course_offerings','academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions',
  'student_registration_requests','student_registration_request_items','student_registration_request_events','student_course_registrations',
  'semester_offering_requests','semester_offering_reviews','semester_offering_events','permissions','roles','role_permissions','user_roles','user_access_scopes','organizational_units'
));
SET @srd_verify_core_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
  (table_name='academic_years' AND column_name IN ('academic_year_id','is_current','is_active','calendar_lifecycle_status')) OR
  (table_name='semesters' AND column_name IN ('semester_id','semester_code','is_active')) OR (table_name='users' AND column_name='user_id') OR
  (table_name='students' AND column_name IN ('student_id','academic_program_id')) OR (table_name='course_offerings' AND column_name IN ('course_offering_id','academic_year_id','semester_id','status')) OR
  (table_name='academic_calendar_event_types' AND column_name IN ('academic_calendar_event_type_id','event_type_code','is_active')) OR
  (table_name='academic_calendar_events' AND column_name IN ('academic_calendar_event_id','academic_year_id','semester_id','academic_calendar_event_type_id','cancelled_at','created_by_user_id')) OR
  (table_name='academic_calendar_event_versions' AND column_name IN ('academic_calendar_event_version_id','academic_calendar_event_id','version_number','starts_at','ends_at','is_enforcement','publication_status','superseded_at','published_event_slot')) OR
  (table_name='student_registration_requests' AND column_name IN ('student_registration_request_id','student_id','academic_year_id','semester_id','status','last_submitted_at','advisor_user_id')) OR
  (table_name='student_registration_request_items' AND column_name IN ('student_registration_request_item_id','student_registration_request_id','course_offering_id','student_course_registration_id')) OR
  (table_name='student_registration_request_events' AND column_name IN ('student_registration_request_event_id','student_registration_request_id','event_type','actor_user_id','from_status','to_status','created_at')) OR
  (table_name='student_course_registrations' AND column_name IN ('student_course_registration_id','student_id','course_offering_id','registration_status_id')) OR
  (table_name='semester_offering_requests' AND column_name IN ('semester_offering_request_id','course_offering_id')) OR (table_name='semester_offering_reviews' AND column_name IN ('semester_offering_review_id','semester_offering_request_id')) OR (table_name='semester_offering_events' AND column_name IN ('semester_offering_event_id','semester_offering_request_id')) OR
  (table_name='permissions' AND column_name IN ('permission_id','permission_code')) OR (table_name='roles' AND column_name IN ('role_id','role_code')) OR (table_name='role_permissions' AND column_name IN ('role_id','permission_id')) OR
  (table_name='user_roles' AND column_name IN ('user_id','role_id','is_active')) OR (table_name='user_access_scopes' AND column_name IN ('user_id','scope_type','scope_id','is_active')) OR (table_name='organizational_units' AND column_name IN ('organizational_unit_id','unit_code','is_active'))
));
SET @srd_verify_data_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND column_name='is_active' AND table_name IN ('permissions','roles'));
SET @srd_verify_signed_keys := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND (
  (table_name='academic_years' AND column_name='academic_year_id') OR (table_name='semesters' AND column_name='semester_id') OR (table_name='users' AND column_name='user_id') OR
  (table_name='academic_calendar_event_types' AND column_name='academic_calendar_event_type_id') OR (table_name='academic_calendar_events' AND column_name='academic_calendar_event_id') OR (table_name='academic_calendar_event_versions' AND column_name='academic_calendar_event_version_id') OR
  (table_name='student_registration_requests' AND column_name='student_registration_request_id') OR (table_name='student_registration_request_items' AND column_name='student_registration_request_item_id') OR (table_name='student_registration_request_events' AND column_name='student_registration_request_event_id') OR
  (table_name='student_course_registrations' AND column_name='student_course_registration_id') OR (table_name='course_offerings' AND column_name='course_offering_id')
));
SET @srd_verify_version_indexes := (SELECT COUNT(*) FROM (
  SELECT index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) columns_in_order,MIN(non_unique) non_unique FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='academic_calendar_event_versions' AND index_name IN ('uq_acev_event_version','uq_acev_published_event_slot','idx_acev_event_status','idx_acev_publication_window') GROUP BY index_name
) x WHERE (index_name='uq_acev_event_version' AND columns_in_order='academic_calendar_event_id,version_number' AND non_unique=0) OR (index_name='uq_acev_published_event_slot' AND columns_in_order='published_event_slot' AND non_unique=0) OR (index_name='idx_acev_event_status' AND columns_in_order='academic_calendar_event_id,publication_status') OR (index_name='idx_acev_publication_window' AND columns_in_order='publication_status,starts_at,ends_at'));
SET @srd_verify_request_indexes := (SELECT COUNT(*) FROM (
  SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) columns_in_order,MIN(non_unique) non_unique FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND ((table_name='student_registration_requests' AND index_name IN ('uq_student_registration_request_term','idx_student_registration_requests_status')) OR (table_name='student_registration_request_events' AND index_name='idx_srr_events_request')) GROUP BY table_name,index_name
) x WHERE (table_name='student_registration_requests' AND index_name='uq_student_registration_request_term' AND columns_in_order='student_id,academic_year_id,semester_id' AND non_unique=0) OR (table_name='student_registration_requests' AND index_name='idx_student_registration_requests_status' AND columns_in_order='status,last_submitted_at') OR (table_name='student_registration_request_events' AND index_name='idx_srr_events_request' AND columns_in_order='student_registration_request_id,created_at'));
SET @srd_verify_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND data_type='datetime' AND is_nullable='YES' AND (
  (table_name='academic_calendar_event_versions' AND column_name IN ('student_registration_ends_at','advisor_approval_ends_at')) OR
  (table_name='student_registration_requests' AND column_name='expired_at')
));
SET @srd_verify_comments := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND column_comment LIKE 'Owned by semester-registration-deadlines-phase2%' AND (
  (table_name='academic_calendar_event_versions' AND column_name IN ('student_registration_ends_at','advisor_approval_ends_at')) OR
  (table_name='student_registration_requests' AND column_name='expired_at')
));
SET @srd_verify_runtime_contract := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
  (table_name='student_registration_requests' AND column_name='status' AND data_type='varchar' AND character_maximum_length>=9) OR
  (table_name='student_registration_request_events' AND column_name='event_type' AND data_type='varchar' AND character_maximum_length>=16) OR
  (table_name='student_registration_request_events' AND column_name IN ('from_status','to_status') AND data_type='varchar' AND character_maximum_length>=9) OR
  (table_name='student_registration_request_events' AND column_name='actor_user_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND is_nullable='YES')
));
SET @srd_verify_registration_type := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code='course_registration' AND is_active=1);
SET @srd_verify_permission_duplicates := (SELECT COUNT(*) FROM (SELECT permission_code FROM `alrowad_uni_rust`.`permissions` WHERE permission_code IN ('registration_requests.view','registration_requests.review') AND is_active=1 GROUP BY permission_code HAVING COUNT(*)<>1) duplicate_permissions);
SET @srd_verify_advisor_role := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`roles` WHERE role_code='academic_advisor' AND is_active=1);
SET @srd_verify_operational_year := ((SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_years` WHERE is_current=1)=1 AND (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_years` WHERE calendar_lifecycle_status='active')=1 AND (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_years` WHERE is_current=1 AND is_active=1 AND calendar_lifecycle_status='active')=1);
SET @srd_verify_permission_codes := (SELECT COUNT(DISTINCT permission_code) FROM `alrowad_uni_rust`.`permissions` WHERE permission_code IN ('registration_requests.view','registration_requests.review') AND is_active=1);
SET @srd_verify_advisor_mappings := (SELECT COUNT(DISTINCT p.permission_code) FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`role_permissions` rp ON rp.role_id=r.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE r.role_code='academic_advisor' AND r.is_active=1 AND p.is_active=1 AND p.permission_code IN ('registration_requests.view','registration_requests.review'));
SET @srd_verify_phase1_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('semester_offering_requests','semester_offering_reviews','semester_offering_events'));
SET @srd_verify_deadline_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_versions` v JOIN `alrowad_uni_rust`.`academic_calendar_events` e ON e.academic_calendar_event_id=v.academic_calendar_event_id JOIN `alrowad_uni_rust`.`academic_calendar_event_types` t ON t.academic_calendar_event_type_id=e.academic_calendar_event_type_id WHERE
  (t.event_type_code<>'course_registration' AND (v.student_registration_ends_at IS NOT NULL OR v.advisor_approval_ends_at IS NOT NULL)) OR
  (t.event_type_code='course_registration' AND ((v.student_registration_ends_at IS NULL)<>(v.advisor_approval_ends_at IS NULL) OR (v.student_registration_ends_at IS NOT NULL AND (v.starts_at>v.student_registration_ends_at OR v.student_registration_ends_at>v.advisor_approval_ends_at OR v.ends_at<>v.advisor_approval_ends_at))))
);
SET @srd_verify_request_conflicts := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`student_registration_requests` WHERE (status='expired' AND expired_at IS NULL) OR (status<>'expired' AND expired_at IS NOT NULL));
SET @srd_verify_root_duplicates := (SELECT COUNT(*) FROM (SELECT e.academic_year_id,e.semester_id FROM `alrowad_uni_rust`.`academic_calendar_events` e JOIN `alrowad_uni_rust`.`academic_calendar_event_types` t ON t.academic_calendar_event_type_id=e.academic_calendar_event_type_id WHERE t.event_type_code='course_registration' AND e.cancelled_at IS NULL GROUP BY e.academic_year_id,e.semester_id HAVING COUNT(*)>1) duplicate_roots);
SET @srd_verify_legacy_rows := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_versions` v JOIN `alrowad_uni_rust`.`academic_calendar_events` e ON e.academic_calendar_event_id=v.academic_calendar_event_id JOIN `alrowad_uni_rust`.`academic_calendar_event_types` t ON t.academic_calendar_event_type_id=e.academic_calendar_event_type_id WHERE t.event_type_code='course_registration' AND v.student_registration_ends_at IS NULL AND v.advisor_approval_ends_at IS NULL);
SET @srd_verify_ready := (@srd_verify_core_tables=21 AND @srd_verify_core_columns=76 AND @srd_verify_data_columns=2 AND @srd_verify_signed_keys=11 AND @srd_verify_version_indexes=4 AND @srd_verify_request_indexes=3 AND @srd_verify_columns=3 AND @srd_verify_comments=3 AND @srd_verify_runtime_contract=5 AND @srd_verify_registration_type=1 AND @srd_verify_permission_duplicates=0 AND @srd_verify_advisor_role=1 AND @srd_verify_operational_year=1 AND @srd_verify_permission_codes=2 AND @srd_verify_advisor_mappings=2 AND @srd_verify_phase1_tables=3 AND @srd_verify_deadline_conflicts=0 AND @srd_verify_request_conflicts=0 AND @srd_verify_root_duplicates=0);

SELECT 'REQUIRED_STRUCTURE' report_section,IF(@srd_verify_core_tables=21 AND @srd_verify_core_columns=76 AND @srd_verify_data_columns=2 AND @srd_verify_signed_keys=11 AND @srd_verify_version_indexes=4 AND @srd_verify_request_indexes=3,'PASS','FAIL') result,CONCAT('tables=',@srd_verify_core_tables,'/21; columns=',@srd_verify_core_columns,'/76; signed_keys=',@srd_verify_signed_keys,'/11; calendar_indexes=',@srd_verify_version_indexes,'/4; request_indexes=',@srd_verify_request_indexes,'/3') detail;
SELECT 'PHASE2_COLUMNS' report_section,IF(@srd_verify_columns=3 AND @srd_verify_comments=3 AND @srd_verify_runtime_contract=5,'PASS','FAIL') result,CONCAT('compatible=',@srd_verify_columns,'/3; ownership=',@srd_verify_comments,'/3; runtime_columns=',@srd_verify_runtime_contract,'/5') detail;
SELECT 'PRESERVED_CONTRACTS' report_section,IF(@srd_verify_registration_type=1 AND @srd_verify_permission_duplicates=0 AND @srd_verify_advisor_role=1 AND @srd_verify_operational_year=1 AND @srd_verify_permission_codes=2 AND @srd_verify_advisor_mappings=2 AND @srd_verify_phase1_tables=3,'PASS','FAIL') result,CONCAT('course_registration=',@srd_verify_registration_type,'; operational_year=',@srd_verify_operational_year,'; advisor_role=',@srd_verify_advisor_role,'; advisor_permissions=',@srd_verify_permission_codes,'/2; advisor_mappings=',@srd_verify_advisor_mappings,'/2; phase1_tables=',@srd_verify_phase1_tables,'/3') detail;
SELECT 'DATA_COMPATIBILITY' report_section,IF(@srd_verify_deadline_conflicts=0 AND @srd_verify_request_conflicts=0 AND @srd_verify_root_duplicates=0,'PASS','FAIL') result,CONCAT('deadline_conflicts=',@srd_verify_deadline_conflicts,'; request_conflicts=',@srd_verify_request_conflicts,'; duplicate_roots=',@srd_verify_root_duplicates,'; legacy_fallback_rows=',@srd_verify_legacy_rows) detail;
SELECT 'OVERALL' report_section,IF(@srd_verify_ready,'PASS','FAIL') result;
