-- Guarded, rerunnable MariaDB 10.11 apply. It recomputes compatibility and
-- never trusts variables or output from 00_preflight.sql. Every object is
-- fully qualified so an absent target database also reaches BLOCKED safely.

SET @sog_apply_core_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('course_offerings','program_courses','courses','semesters','users','teaching_assignment_requests','teaching_assignment_reviews','course_offering_instructors','academic_calendar_event_types','academic_calendar_events','academic_calendar_event_versions','academic_programs','academic_years','departments','colleges','faculty_members','system_modules','permissions','roles','role_permissions','user_roles','user_access_scopes','organizational_units'));
SET @sog_apply_core_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND (
  (table_name='course_offerings' AND column_name IN ('course_offering_id','course_id','academic_program_id','academic_year_id','semester_id','status')) OR
  (table_name='program_courses' AND column_name IN ('program_course_id','academic_program_id','course_id','course_type','is_active')) OR
  (table_name='courses' AND column_name IN ('course_id','theoretical_hours','practical_hours')) OR
  (table_name='semesters' AND column_name IN ('semester_id','semester_code')) OR
  (table_name='course_offering_instructors' AND column_name IN ('course_offering_instructor_id','course_offering_id','faculty_member_id','instructor_role','is_active')) OR
  (table_name='teaching_assignment_requests' AND column_name IN ('teaching_assignment_request_id','course_offering_id','faculty_member_id','instructor_role','current_slot','status','action_type','target_course_offering_instructor_id')) OR
  (table_name='teaching_assignment_reviews' AND column_name IN ('teaching_assignment_review_id','teaching_assignment_request_id','review_authority','status','reviewed_by_user_id','reviewed_at','reason','updated_at')) OR
  (table_name='academic_calendar_event_types' AND column_name IN ('academic_calendar_event_type_id','event_type_code','is_active')) OR
  (table_name='academic_calendar_events' AND column_name IN ('academic_calendar_event_id','academic_year_id','semester_id','academic_calendar_event_type_id','cancelled_at')) OR
  (table_name='academic_calendar_event_versions' AND column_name IN ('academic_calendar_event_id','publication_status','is_enforcement','starts_at','ends_at','superseded_at')) OR
  (table_name='users' AND column_name='user_id') OR
  (table_name='academic_programs' AND column_name IN ('academic_program_id','department_id','is_active')) OR
  (table_name='academic_years' AND column_name='academic_year_id') OR
  (table_name='departments' AND column_name IN ('department_id','college_id','is_active')) OR
  (table_name='colleges' AND column_name IN ('college_id','is_active')) OR
  (table_name='faculty_members' AND column_name='faculty_member_id') OR
  (table_name='system_modules' AND column_name IN ('module_id','module_code','is_active')) OR
  (table_name='permissions' AND column_name IN ('permission_id','module_id','permission_code','permission_name','description','is_active','created_at','updated_at')) OR
  (table_name='roles' AND column_name IN ('role_id','role_code','is_active')) OR
  (table_name='role_permissions' AND column_name IN ('role_id','permission_id','granted_at')) OR
  (table_name='user_roles' AND column_name IN ('user_id','role_id','is_active')) OR
  (table_name='user_access_scopes' AND column_name IN ('user_id','scope_type','scope_id','is_active')) OR
  (table_name='organizational_units' AND column_name IN ('organizational_unit_id','unit_code','is_active'))
));
SET @sog_apply_parent_keys := (SELECT COUNT(*) FROM (SELECT table_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND index_name='PRIMARY' AND table_name IN ('course_offerings','program_courses','users','system_modules','permissions','roles') GROUP BY table_name) pk JOIN information_schema.columns c ON c.table_schema='alrowad_uni_rust' AND c.table_name=pk.table_name AND c.column_name=pk.cols WHERE c.data_type='int' AND c.column_type NOT LIKE '%unsigned%' AND ((pk.table_name='course_offerings' AND pk.cols='course_offering_id') OR (pk.table_name='program_courses' AND pk.cols='program_course_id') OR (pk.table_name='users' AND pk.cols='user_id') OR (pk.table_name='system_modules' AND pk.cols='module_id') OR (pk.table_name='permissions' AND pk.cols='permission_id') OR (pk.table_name='roles' AND pk.cols='role_id')));
SET @sog_apply_effective_indexes := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND index_name IN ('uq_tar_current_slot','uq_course_offering_role') GROUP BY table_name,index_name) x WHERE (table_name='teaching_assignment_requests' AND index_name='uq_tar_current_slot' AND cols='course_offering_id,instructor_role,current_slot') OR (table_name='course_offering_instructors' AND index_name='uq_course_offering_role' AND cols='course_offering_id,instructor_role'));
SET @sog_apply_semesters:=0,@sog_apply_calendar:=0,@sog_apply_pres:=0,@sog_apply_roles:=0,@sog_apply_role_duplicates:=1,@sog_apply_module:=0,@sog_apply_permission_conflicts:=1,@sog_apply_permission_duplicates:=1,@sog_apply_mapping_conflicts:=1;
SET @sog_sql := IF(@sog_apply_core_tables=23 AND @sog_apply_core_columns=89, 'SET @sog_apply_semesters=(SELECT COUNT(DISTINCT semester_code) FROM `alrowad_uni_rust`.`semesters` WHERE semester_code IN (''first'',''second'',''summer'')),@sog_apply_calendar=(SELECT COUNT(*) FROM `alrowad_uni_rust`.`academic_calendar_event_types` WHERE event_type_code=''course_registration'' AND is_active=1),@sog_apply_pres=(SELECT COUNT(*) FROM `alrowad_uni_rust`.`organizational_units` WHERE unit_code=''PRES'' AND is_active=1),@sog_apply_roles=(SELECT COUNT(DISTINCT role_code) FROM `alrowad_uni_rust`.`roles` WHERE role_code IN (''dean'',''vice_president_scientific'',''vice_president_administrative'') AND is_active=1),@sog_apply_role_duplicates=(SELECT COUNT(*) FROM (SELECT role_code FROM `alrowad_uni_rust`.`roles` WHERE role_code IN (''dean'',''vice_president_scientific'',''vice_president_administrative'') AND is_active=1 GROUP BY role_code HAVING COUNT(*)>1) x),@sog_apply_module=(SELECT COUNT(*) FROM `alrowad_uni_rust`.`system_modules` WHERE module_code=''courses'' AND is_active=1),@sog_apply_permission_conflicts=(SELECT COUNT(*) FROM `alrowad_uni_rust`.`permissions` p LEFT JOIN `alrowad_uni_rust`.`system_modules` m ON m.module_id=p.module_id WHERE p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.manage'',''course_offerings.semester_governance.review_scientific'') AND (p.is_active<>1 OR COALESCE(m.module_code,'''')<>''courses'' OR COALESCE(m.is_active,0)<>1)),@sog_apply_permission_duplicates=(SELECT COUNT(*) FROM (SELECT permission_code FROM `alrowad_uni_rust`.`permissions` WHERE permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.manage'',''course_offerings.semester_governance.review_scientific'') GROUP BY permission_code HAVING COUNT(*)>1) x),@sog_apply_mapping_conflicts=(SELECT COUNT(*) FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.manage'',''course_offerings.semester_governance.review_scientific'') AND NOT (r.is_active=1 AND ((r.role_code=''dean'' AND p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.manage'')) OR (r.role_code=''vice_president_scientific'' AND p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.review_scientific'')))))', 'SELECT ''CORE_PREREQUISITES'' report_section,''BLOCKED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;

SET @sog_apply_target_tables := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('semester_offering_requests','semester_offering_reviews','semester_offering_events'));
SET @sog_apply_target_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='semester_offering_requests' AND column_name IN ('semester_offering_request_id','course_offering_id','program_course_id','course_type','is_selected','minimum_enrollment','status','submission_version','created_by_user_id','submitted_by_user_id','submitted_at','approved_at','materialized_at','created_at','updated_at')) OR (table_name='semester_offering_reviews' AND column_name IN ('semester_offering_review_id','semester_offering_request_id','submission_version','status','reviewed_by_user_id','reviewed_at','reason','created_at','updated_at')) OR (table_name='semester_offering_events' AND column_name IN ('semester_offering_event_id','semester_offering_request_id','submission_version','event_type','actor_user_id','note','occurred_at'))));
SET @sog_apply_target_shape := (SELECT COUNT(*) FROM information_schema.columns c JOIN (
  SELECT 'semester_offering_requests' t,'semester_offering_request_id' n,'int' d,'NO' z UNION ALL SELECT 'semester_offering_requests','course_offering_id','int','NO' UNION ALL SELECT 'semester_offering_requests','program_course_id','int','NO' UNION ALL SELECT 'semester_offering_requests','course_type','varchar','NO' UNION ALL SELECT 'semester_offering_requests','is_selected','tinyint','NO' UNION ALL SELECT 'semester_offering_requests','minimum_enrollment','int','YES' UNION ALL SELECT 'semester_offering_requests','status','varchar','NO' UNION ALL SELECT 'semester_offering_requests','submission_version','int','NO' UNION ALL SELECT 'semester_offering_requests','created_by_user_id','int','NO' UNION ALL SELECT 'semester_offering_requests','submitted_by_user_id','int','YES' UNION ALL SELECT 'semester_offering_requests','submitted_at','datetime','YES' UNION ALL SELECT 'semester_offering_requests','approved_at','datetime','YES' UNION ALL SELECT 'semester_offering_requests','materialized_at','datetime','YES' UNION ALL SELECT 'semester_offering_requests','created_at','timestamp','NO' UNION ALL SELECT 'semester_offering_requests','updated_at','timestamp','NO'
  UNION ALL SELECT 'semester_offering_reviews','semester_offering_review_id','int','NO' UNION ALL SELECT 'semester_offering_reviews','semester_offering_request_id','int','NO' UNION ALL SELECT 'semester_offering_reviews','submission_version','int','NO' UNION ALL SELECT 'semester_offering_reviews','status','varchar','NO' UNION ALL SELECT 'semester_offering_reviews','reviewed_by_user_id','int','YES' UNION ALL SELECT 'semester_offering_reviews','reviewed_at','datetime','YES' UNION ALL SELECT 'semester_offering_reviews','reason','varchar','YES' UNION ALL SELECT 'semester_offering_reviews','created_at','timestamp','NO' UNION ALL SELECT 'semester_offering_reviews','updated_at','timestamp','NO'
  UNION ALL SELECT 'semester_offering_events','semester_offering_event_id','int','NO' UNION ALL SELECT 'semester_offering_events','semester_offering_request_id','int','NO' UNION ALL SELECT 'semester_offering_events','submission_version','int','NO' UNION ALL SELECT 'semester_offering_events','event_type','varchar','NO' UNION ALL SELECT 'semester_offering_events','actor_user_id','int','NO' UNION ALL SELECT 'semester_offering_events','note','varchar','YES' UNION ALL SELECT 'semester_offering_events','occurred_at','datetime','NO'
) e ON e.t=c.table_name AND e.n=c.column_name WHERE c.table_schema='alrowad_uni_rust' AND c.data_type=e.d AND c.is_nullable=e.z AND (e.d NOT IN ('int','tinyint') OR c.column_type NOT LIKE '%unsigned%') AND (c.table_name<>'semester_offering_requests' OR c.column_name<>'course_type' OR c.character_maximum_length>=16) AND (c.column_name<>'status' OR c.character_maximum_length>=16) AND (c.column_name<>'event_type' OR c.character_maximum_length>=32) AND (c.column_name NOT IN ('reason','note') OR c.character_maximum_length>=1000));
SET @sog_apply_pks := (SELECT COUNT(*) FROM (SELECT table_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND index_name='PRIMARY' AND table_name IN ('semester_offering_requests','semester_offering_reviews','semester_offering_events') GROUP BY table_name) x WHERE (table_name='semester_offering_requests' AND cols='semester_offering_request_id') OR (table_name='semester_offering_reviews' AND cols='semester_offering_review_id') OR (table_name='semester_offering_events' AND cols='semester_offering_event_id'));
SET @sog_apply_unique := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND non_unique=0 AND index_name IN ('uq_sor_offering','uq_sorv_request_version') GROUP BY table_name,index_name) x WHERE (table_name='semester_offering_requests' AND index_name='uq_sor_offering' AND cols='course_offering_id') OR (table_name='semester_offering_reviews' AND index_name='uq_sorv_request_version' AND cols='semester_offering_request_id,submission_version'));
SET @sog_apply_indexes := (SELECT COUNT(*) FROM (SELECT table_name,index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND index_name IN ('idx_sor_status_submitted','idx_sor_program_course','idx_sor_materialized','idx_sorv_status','idx_soe_request_time','idx_soe_type_time') GROUP BY table_name,index_name) x WHERE (table_name='semester_offering_requests' AND index_name='idx_sor_status_submitted' AND cols='status,submitted_at') OR (table_name='semester_offering_requests' AND index_name='idx_sor_program_course' AND cols='program_course_id') OR (table_name='semester_offering_requests' AND index_name='idx_sor_materialized' AND cols='materialized_at') OR (table_name='semester_offering_reviews' AND index_name='idx_sorv_status' AND cols='status,reviewed_at') OR (table_name='semester_offering_events' AND index_name='idx_soe_request_time' AND cols='semester_offering_request_id,occurred_at') OR (table_name='semester_offering_events' AND index_name='idx_soe_type_time' AND cols='event_type,occurred_at'));
SET @sog_apply_fks := (SELECT COUNT(*) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints rc ON rc.constraint_schema=k.table_schema AND rc.table_name=k.table_name AND rc.constraint_name=k.constraint_name WHERE k.table_schema='alrowad_uni_rust' AND k.referenced_table_schema='alrowad_uni_rust' AND rc.update_rule='RESTRICT' AND rc.delete_rule='RESTRICT' AND (
  (k.constraint_name='fk_sor_offering' AND k.table_name='semester_offering_requests' AND k.column_name='course_offering_id' AND k.referenced_table_name='course_offerings' AND k.referenced_column_name='course_offering_id') OR (k.constraint_name='fk_sor_program_course' AND k.table_name='semester_offering_requests' AND k.column_name='program_course_id' AND k.referenced_table_name='program_courses' AND k.referenced_column_name='program_course_id') OR (k.constraint_name='fk_sor_created_by' AND k.table_name='semester_offering_requests' AND k.column_name='created_by_user_id' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id') OR (k.constraint_name='fk_sor_submitted_by' AND k.table_name='semester_offering_requests' AND k.column_name='submitted_by_user_id' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id') OR (k.constraint_name='fk_sorv_request' AND k.table_name='semester_offering_reviews' AND k.column_name='semester_offering_request_id' AND k.referenced_table_name='semester_offering_requests' AND k.referenced_column_name='semester_offering_request_id') OR (k.constraint_name='fk_sorv_reviewer' AND k.table_name='semester_offering_reviews' AND k.column_name='reviewed_by_user_id' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id') OR (k.constraint_name='fk_soe_request' AND k.table_name='semester_offering_events' AND k.column_name='semester_offering_request_id' AND k.referenced_table_name='semester_offering_requests' AND k.referenced_column_name='semester_offering_request_id') OR (k.constraint_name='fk_soe_actor' AND k.table_name='semester_offering_events' AND k.column_name='actor_user_id' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id')
));
SET @sog_apply_checks := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_type='CHECK' AND ((table_name='semester_offering_requests' AND constraint_name IN ('chk_sor_course_type','chk_sor_selected','chk_sor_minimum','chk_sor_status','chk_sor_version','chk_sor_submission','chk_sor_approval','chk_sor_materialization')) OR (table_name='semester_offering_reviews' AND constraint_name IN ('chk_sorv_version','chk_sorv_status','chk_sorv_provenance')) OR (table_name='semester_offering_events' AND constraint_name IN ('chk_soe_version','chk_soe_type'))));
SET @sog_apply_comments := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('semester_offering_requests','semester_offering_reviews','semester_offering_events') AND table_comment LIKE 'Owned by semester-offering-governance-phase1%');
SET @sog_apply_name_conflicts := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND constraint_name IN ('fk_sor_offering','fk_sor_program_course','fk_sor_created_by','fk_sor_submitted_by','fk_sorv_request','fk_sorv_reviewer','fk_soe_request','fk_soe_actor','chk_sor_course_type','chk_sor_selected','chk_sor_minimum','chk_sor_status','chk_sor_version','chk_sor_submission','chk_sor_approval','chk_sor_materialization','chk_sorv_version','chk_sorv_status','chk_sorv_provenance','chk_soe_version','chk_soe_type') AND table_name NOT IN ('semester_offering_requests','semester_offering_reviews','semester_offering_events'));
SET @sog_apply_target_state := IF(@sog_apply_target_tables=0,IF(@sog_apply_name_conflicts=0,'ABSENT','CONFLICTING'),IF(@sog_apply_target_tables=3 AND @sog_apply_target_columns=31 AND @sog_apply_target_shape=31 AND @sog_apply_pks=3 AND @sog_apply_unique=2 AND @sog_apply_indexes=6 AND @sog_apply_fks=8 AND @sog_apply_checks=13 AND @sog_apply_comments=3,'COMPATIBLE','CONFLICTING'));

SET @sog_apply_ready := (@sog_apply_core_tables=23 AND @sog_apply_core_columns=89 AND @sog_apply_parent_keys=6 AND @sog_apply_semesters=3 AND @sog_apply_effective_indexes=2 AND @sog_apply_calendar=1 AND @sog_apply_pres=1 AND @sog_apply_roles=3 AND @sog_apply_role_duplicates=0 AND @sog_apply_module=1 AND @sog_apply_target_state<>'CONFLICTING' AND @sog_apply_permission_conflicts=0 AND @sog_apply_permission_duplicates=0 AND @sog_apply_mapping_conflicts=0);

SET @sog_sql := IF(@sog_apply_ready AND @sog_apply_target_state='ABSENT', 'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`semester_offering_requests` (`semester_offering_request_id` INT NOT NULL AUTO_INCREMENT,`course_offering_id` INT NOT NULL,`program_course_id` INT NOT NULL,`course_type` VARCHAR(16) NOT NULL,`is_selected` TINYINT(1) NOT NULL DEFAULT 1,`minimum_enrollment` INT NULL,`status` VARCHAR(16) NOT NULL DEFAULT ''draft'',`submission_version` INT NOT NULL DEFAULT 0,`created_by_user_id` INT NOT NULL,`submitted_by_user_id` INT NULL,`submitted_at` DATETIME NULL,`approved_at` DATETIME NULL,`materialized_at` DATETIME NULL,`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`semester_offering_request_id`),UNIQUE KEY `uq_sor_offering` (`course_offering_id`),KEY `idx_sor_status_submitted` (`status`,`submitted_at`),KEY `idx_sor_program_course` (`program_course_id`),KEY `idx_sor_materialized` (`materialized_at`),CONSTRAINT `chk_sor_course_type` CHECK (`course_type` IN (''mandatory'',''elective'')),CONSTRAINT `chk_sor_selected` CHECK (`is_selected` IN (0,1)),CONSTRAINT `chk_sor_minimum` CHECK (`minimum_enrollment` IS NULL OR `minimum_enrollment` > 0),CONSTRAINT `chk_sor_status` CHECK (`status` IN (''draft'',''submitted'',''returned'',''approved'')),CONSTRAINT `chk_sor_version` CHECK (`submission_version` >= 0),CONSTRAINT `chk_sor_submission` CHECK ((`status`=''draft'' AND `submission_version`=0 AND `submitted_by_user_id` IS NULL AND `submitted_at` IS NULL) OR (`status` IN (''submitted'',''returned'',''approved'') AND `submission_version`>=1 AND `submitted_by_user_id` IS NOT NULL AND `submitted_at` IS NOT NULL)),CONSTRAINT `chk_sor_approval` CHECK ((`status`=''approved'' AND `approved_at` IS NOT NULL) OR (`status`<>''approved'' AND `approved_at` IS NULL)),CONSTRAINT `chk_sor_materialization` CHECK (`materialized_at` IS NULL OR (`status`=''approved'' AND `approved_at` IS NOT NULL)),CONSTRAINT `fk_sor_offering` FOREIGN KEY (`course_offering_id`) REFERENCES `alrowad_uni_rust`.`course_offerings` (`course_offering_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT `fk_sor_program_course` FOREIGN KEY (`program_course_id`) REFERENCES `alrowad_uni_rust`.`program_courses` (`program_course_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT `fk_sor_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT `fk_sor_submitted_by` FOREIGN KEY (`submitted_by_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-offering-governance-phase1; one governance root per normal offering''', 'SELECT ''PHASE1_DDL'' report_section, ''SKIPPED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;
SET @sog_sql := IF(@sog_apply_ready AND @sog_apply_target_state='ABSENT', 'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`semester_offering_reviews` (`semester_offering_review_id` INT NOT NULL AUTO_INCREMENT,`semester_offering_request_id` INT NOT NULL,`submission_version` INT NOT NULL,`status` VARCHAR(16) NOT NULL DEFAULT ''pending'',`reviewed_by_user_id` INT NULL,`reviewed_at` DATETIME NULL,`reason` VARCHAR(1000) NULL,`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`semester_offering_review_id`),UNIQUE KEY `uq_sorv_request_version` (`semester_offering_request_id`,`submission_version`),KEY `idx_sorv_status` (`status`,`reviewed_at`),CONSTRAINT `chk_sorv_version` CHECK (`submission_version` > 0),CONSTRAINT `chk_sorv_status` CHECK (`status` IN (''pending'',''approved'',''returned'')),CONSTRAINT `chk_sorv_provenance` CHECK ((`status`=''pending'' AND `reviewed_by_user_id` IS NULL AND `reviewed_at` IS NULL AND `reason` IS NULL) OR (`status`=''approved'' AND `reviewed_by_user_id` IS NOT NULL AND `reviewed_at` IS NOT NULL AND `reason` IS NULL) OR (`status`=''returned'' AND `reviewed_by_user_id` IS NOT NULL AND `reviewed_at` IS NOT NULL AND CHAR_LENGTH(TRIM(`reason`))>0)),CONSTRAINT `fk_sorv_request` FOREIGN KEY (`semester_offering_request_id`) REFERENCES `alrowad_uni_rust`.`semester_offering_requests` (`semester_offering_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT `fk_sorv_reviewer` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-offering-governance-phase1; immutable scientific review per submission version''', 'SELECT ''PHASE1_DDL'' report_section, ''SKIPPED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;
SET @sog_sql := IF(@sog_apply_ready AND @sog_apply_target_state='ABSENT', 'CREATE TABLE IF NOT EXISTS `alrowad_uni_rust`.`semester_offering_events` (`semester_offering_event_id` INT NOT NULL AUTO_INCREMENT,`semester_offering_request_id` INT NOT NULL,`submission_version` INT NOT NULL DEFAULT 0,`event_type` VARCHAR(32) NOT NULL,`actor_user_id` INT NOT NULL,`note` VARCHAR(1000) NULL,`occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`semester_offering_event_id`),KEY `idx_soe_request_time` (`semester_offering_request_id`,`occurred_at`),KEY `idx_soe_type_time` (`event_type`,`occurred_at`),CONSTRAINT `chk_soe_version` CHECK (`submission_version` >= 0),CONSTRAINT `chk_soe_type` CHECK (`event_type` IN (''prepared'',''updated'',''deselected'',''submitted'',''resubmitted'',''scientific_returned'',''scientific_approved'',''materialized'')),CONSTRAINT `fk_soe_request` FOREIGN KEY (`semester_offering_request_id`) REFERENCES `alrowad_uni_rust`.`semester_offering_requests` (`semester_offering_request_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT `fk_soe_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `alrowad_uni_rust`.`users` (`user_id`) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=''Owned by semester-offering-governance-phase1; append-only transition history''', 'SELECT ''PHASE1_DDL'' report_section, ''SKIPPED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;

SET @sog_sql := IF(@sog_apply_ready, 'INSERT INTO `alrowad_uni_rust`.`permissions` (`module_id`,`permission_code`,`permission_name`,`description`,`is_active`,`created_at`,`updated_at`) SELECT m.module_id,s.permission_code,s.permission_name,s.description,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM `alrowad_uni_rust`.`system_modules` m JOIN (SELECT ''course_offerings.semester_governance.view'' permission_code,''Semester Offering Governance View'' permission_name,''View semester offering governance'' description UNION ALL SELECT ''course_offerings.semester_governance.manage'',''Semester Offering Governance Manage'',''Prepare and submit semester offerings as Dean'' UNION ALL SELECT ''course_offerings.semester_governance.review_scientific'',''Semester Offering Scientific Review'',''Approve or return semester offerings as Scientific VP'') s WHERE m.module_code=''courses'' AND m.is_active=1 AND NOT EXISTS (SELECT 1 FROM `alrowad_uni_rust`.`permissions` p WHERE p.permission_code=s.permission_code)', 'SELECT ''PHASE1_RBAC'' report_section,''SKIPPED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;
SET @sog_sql := IF(@sog_apply_ready, 'INSERT INTO `alrowad_uni_rust`.`role_permissions` (`role_id`,`permission_id`,`granted_at`) SELECT r.role_id,p.permission_id,CURRENT_TIMESTAMP FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`permissions` p ON ((r.role_code=''dean'' AND p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.manage'')) OR (r.role_code=''vice_president_scientific'' AND p.permission_code IN (''course_offerings.semester_governance.view'',''course_offerings.semester_governance.review_scientific''))) WHERE r.is_active=1 AND p.is_active=1 AND NOT EXISTS (SELECT 1 FROM `alrowad_uni_rust`.`role_permissions` rp WHERE rp.role_id=r.role_id AND rp.permission_id=p.permission_id)', 'SELECT ''PHASE1_RBAC'' report_section,''SKIPPED'' result');
PREPARE sog_apply_stmt FROM @sog_sql; EXECUTE sog_apply_stmt; DEALLOCATE PREPARE sog_apply_stmt;

SELECT 'APPLY_GUARD' report_section,IF(@sog_apply_ready,'PASS','FAIL') result,CONCAT('target=',@sog_apply_target_state,'; core_tables=',@sog_apply_core_tables,'/23; core_columns=',@sog_apply_core_columns,'/89; signed_primary_keys=',@sog_apply_parent_keys,'/6; permission_conflicts=',@sog_apply_permission_conflicts,'; mapping_conflicts=',@sog_apply_mapping_conflicts) detail;
SELECT 'OVERALL' report_section,IF(@sog_apply_ready,'APPLIED','BLOCKED') result;
