-- Read-only deployment verification.
SELECT COUNT(DISTINCT table_name) INTO @dependency_count FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_periods','supplementary_exam_period_events','supplementary_exam_offerings','supplementary_exam_offering_sources','supplementary_exam_offering_events','student_course_registrations','registration_statuses','student_course_results','result_statuses','grade_components','student_grade_components','grade_part_approvals','grade_approvals','approval_statuses','grading_policies','users','roles','permissions','role_permissions');
SELECT COUNT(*) INTO @target_count FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events');
SELECT COUNT(*) INTO @unique_count FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='supplementary_exam_theoretical_deferrals' AND non_unique=0 AND index_name<>'PRIMARY';
SELECT COUNT(*) INTO @fk_count FROM information_schema.referential_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name IN ('supplementary_exam_theoretical_deferrals','supplementary_exam_theoretical_deferral_events');
SELECT COUNT(*) INTO @invalid_rows FROM `alrowad_uni_rust`.`supplementary_exam_theoretical_deferrals` WHERE (status='declared' AND current_slot<>1) OR (status IN ('cancelled','superseded') AND current_slot IS NOT NULL) OR status NOT IN ('declared','cancelled','superseded');
SELECT COUNT(*) INTO @orphan_events FROM `alrowad_uni_rust`.`supplementary_exam_theoretical_deferral_events` e LEFT JOIN `alrowad_uni_rust`.`supplementary_exam_theoretical_deferrals` d ON d.supplementary_exam_theoretical_deferral_id=e.supplementary_exam_theoretical_deferral_id WHERE d.supplementary_exam_theoretical_deferral_id IS NULL;
SELECT COUNT(*) INTO @self_forbidden FROM `alrowad_uni_rust`.`role_permissions` rp JOIN `alrowad_uni_rust`.`roles` r ON r.role_id=rp.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE p.permission_code='supplementary_exams.deferrals.self' AND r.role_code<>'student';
SET @ok := @dependency_count=19 AND @target_count=2 AND @unique_count>=2 AND @fk_count=6 AND @invalid_rows=0 AND @orphan_events=0 AND @self_forbidden=0;
SELECT 'OVERALL' AS report_section,IF(@ok,'PASS','FAIL') AS result,IF(@dependency_count<>19,'PHASE2_NOT_DEPLOYED',IF(@ok,NULL,'PHASE3_CONTRACT_INVALID')) AS blocker_code;
