<?php
namespace Tests\Feature;
use Tests\TestCase;
class SupplementaryExamRegistrationSqlContractTest extends TestCase
{
 private function sql($n){return file_get_contents(database_path("sql/supplementary-exam-registration/$n"));}
 public function test_phpmyadmin_policy():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql'] as $n){$s=$this->sql($n);$this->assertDoesNotMatchRegularExpression('/\b(SIGNAL|DELIMITER|CREATE\s+PROCEDURE)\b|DATABASE\s*\(/i',$s);$this->assertMatchesRegularExpression('/SELECT\s.+;\s*$/is',$s);$this->assertStringContainsString("table_schema='alrowad_uni_rust'",$s);}}
 public function test_forward_scripts_share_non_compensatable_dependency_and_target_contracts():void{$guards=['@p1_period_identity_unique_ok','@p2_offering_identity_unique_ok','@p2_source_identity_unique_ok','@p3_deferral_identity_unique_ok','@p3_deferral_current_unique_ok','@p2_offering_period_fk_ok','@p2_offering_program_fk_ok','@p2_offering_course_fk_ok','@p2_offering_opener_fk_ok','@p2_offering_closer_fk_ok','@reg_pk_ok','@reg_identity_unique_ok','@reg_current_unique_ok','@reg_student_current_index_ok','@reg_offering_status_index_ok','@reg_registered_by_index_ok','@reg_cancelled_by_index_ok','@reg_offering_fk_ok','@reg_student_fk_ok','@reg_original_registration_fk_ok','@reg_registered_actor_fk_ok','@reg_cancelled_actor_fk_ok','@event_pk_ok','@event_history_index_ok','@event_actor_index_ok','@event_registration_fk_ok','@event_actor_fk_ok','@p2_offering_program_signedness_ok','@reg_offering_signedness_ok','@event_actor_signedness_ok'];foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$sql=$this->sql($n);foreach($guards as$guard)$this->assertStringContainsString($guard,$sql,"$n missing $guard");foreach(['@dependency_semantic_uniques','@reg_indexes','@reg_fks','@reg_signedness','@event_indexes','@event_fks','@event_signedness']as$removed)$this->assertStringNotContainsString($removed,$sql);}}
 public function test_semantics_accept_equivalent_names_but_cannot_be_compensated_by_duplicates():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$sql=$this->sql($n);$this->assertStringContainsString('GROUP BY index_name',$sql);$this->assertStringContainsString("cols='student_id,current_slot' OR cols LIKE 'student_id,current_slot,%'",$sql);$this->assertStringContainsString("column_name='academic_program_id' AND referenced_table_name='academic_programs'",$sql);$this->assertStringContainsString('EXISTS(SELECT 1 FROM information_schema.key_column_usage',$sql);}}
 public function test_event_compatibility_is_named_typed_and_semantic():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);$this->assertStringContainsString("table_name='supplementary_exam_registration_events'",$s);$this->assertStringContainsString("column_name='supplementary_exam_registration_event_id'",$s);$this->assertStringContainsString("supplementary_exam_registration_id,created_at",$s);$this->assertStringContainsString('@event_registration_fk_ok',$s);}}
 public function test_rbac_collision_and_off_matrix_are_blocking():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);foreach(['@permission_collision','@permission_duplicates','@off_matrix']as$x)$this->assertStringContainsString($x,$s);}$this->assertStringContainsString('RBAC_CONFLICT',$this->sql('00_preflight.sql'));$this->assertStringContainsString('RBAC_CONFLICT',$this->sql('01_apply.sql'));$this->assertStringContainsString('RBAC_INVALID',$this->sql('02_verify.sql'));}
 public function test_verify_checks_duplicates_provenance_null_slot_and_summer_order():void{$v=$this->sql('02_verify.sql');foreach(['@duplicate_identity','@duplicate_current','supplementary_exam_offering_sources','scr.student_id<>r.student_id','current_slot IS NULL OR r.current_slot<>1','semester_order=3','HAVING COUNT(*)>3']as$x)$this->assertStringContainsString($x,$v);$this->assertStringNotContainsString('semester_id=3',$v);}
 public function test_apply_and_rollback_are_conservative():void{$a=$this->sql('01_apply.sql');$this->assertStringNotContainsString('CREATE TABLE IF NOT EXISTS',$a);$this->assertStringContainsString("@reg_state='ABSENT'",$a);$this->assertStringContainsString("@event_state='ABSENT'",$a);$r=$this->sql('03_rollback.sql');foreach(['@reg_exists','@event_exists','@reg_owned','@event_owned','BLOCKED_IN_USE']as$x)$this->assertStringContainsString($x,$r);}
 public function test_no_forbidden_academic_mutations():void{$all=implode("\n",array_map(fn($n)=>$this->sql($n),['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql']));foreach(['INSERT INTO `alrowad_uni_rust`.`student_course_registrations`','INSERT INTO `alrowad_uni_rust`.`course_offerings`','UPDATE `alrowad_uni_rust`.`supplementary_exam_results`'] as $x)$this->assertStringNotContainsString($x,$all);}
 public function test_dependency_does_not_use_cross_table_aggregate_type_fk_or_index_counts():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);$this->assertStringNotContainsString('@dependency_types',$s);$this->assertStringNotContainsString('@dependency_fks',$s);$this->assertStringNotContainsString('@dependency_supporting_indexes',$s);}}
 public function test_apply_recomputes_full_target_state_after_each_ddl():void{$sql=$this->sql('01_apply.sql');$this->assertGreaterThanOrEqual(3,substr_count($sql,'SET @reg_state := IF('));$this->assertGreaterThanOrEqual(3,substr_count($sql,'SET @event_state := IF('));$this->assertStringContainsString("SET @post_reg_ready := @reg_state='COMPATIBLE'",$sql);$this->assertStringContainsString("SET @post_event_ready := @event_state='COMPATIBLE'",$sql);}
 public function test_preflight_has_visible_operator_report():void{$s=$this->sql('00_preflight.sql');foreach(['OPERATOR REPORT','PHASE3_DEPENDENCY','PERIOD_LIFECYCLE_WIDTH','REGISTRATIONS_TABLE','REGISTRATION_EVENTS_TABLE','RBAC','TARGET_SCHEMA','OVERALL','RUN 01_apply.sql']as$x)$this->assertStringContainsString($x,$s);$this->assertStringContainsString('UNION ALL',$s);}
 public function test_apply_has_visible_operator_report():void{$s=$this->sql('01_apply.sql');foreach(['OPERATOR REPORT','APPLY_GUARD','REGISTRATIONS_TABLE','REGISTRATION_EVENTS_TABLE','RBAC_PERMISSIONS','RBAC_ROLE_MAPPINGS','POST_APPLY_SCHEMA','POST_APPLY_RBAC','APPLY_RESULT','RUN 02_verify.sql']as$x)$this->assertStringContainsString($x,$s);$this->assertStringContainsString('UNION ALL',$s);}
 public function test_verify_has_visible_operator_matrix():void{$s=$this->sql('02_verify.sql');foreach(['OPERATOR REPORT','PHASE3_DEPENDENCY','PERIOD_LIFECYCLE','REGISTRATIONS_COLUMNS','REGISTRATIONS_PRIMARY_KEY','REGISTRATIONS_UNIQUES','REGISTRATIONS_INDEXES','REGISTRATIONS_FOREIGN_KEYS','REGISTRATION_EVENTS_COLUMNS','REGISTRATION_EVENTS_PRIMARY_KEY','REGISTRATION_EVENTS_INDEXES','REGISTRATION_EVENTS_FOREIGN_KEYS','RBAC_PERMISSIONS','RBAC_ROLE_MATRIX','ROW_STATUS_INVARIANTS','PROVENANCE_INVARIANTS','STUDENT_IDENTITY_INVARIANTS','DUPLICATE_INVARIANTS','SUMMER_MAX_3_INVARIANT','OVERALL']as$x)$this->assertStringContainsString($x,$s);$this->assertStringContainsString('UNION ALL',$s);}
 public function test_rollback_has_visible_operator_report():void{$s=$this->sql('03_rollback.sql');foreach(['ROLLBACK_GUARD','REGISTRATION_EVENTS_ACTION','REGISTRATIONS_ACTION','RBAC_ACTION','ROLLBACK_RESULT','BLOCKED_ADOPTED','NOTHING_TO_DO']as$x)$this->assertStringContainsString($x,$s);$this->assertStringContainsString('UNION ALL',$s);}
 public function test_final_operator_reports_are_plain_select_union_resultsets():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);$marker=strrpos($s,'OPERATOR REPORT');$this->assertNotFalse($marker);$report=substr($s,$marker);$this->assertStringContainsString('SELECT',$report);$this->assertStringContainsString('UNION ALL',$report);$this->assertStringNotContainsString('PREPARE',$report);}}
}
