<?php
namespace Tests\Feature;
use App\Support\SupplementaryExamEligibilityGovernance;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;
class SupplementaryExamEligibilitySchemaReadyRuntimeTest extends TestCase
{
 protected function setUp():void{parent::setUp();$this->drop();$this->parents();$this->phase1();$this->phase2();$this->phase3();}
 protected function tearDown():void{$this->drop();parent::tearDown();}
 public function test_full_runtime_contract_is_ready():void{$this->assertTrue(SupplementaryExamEligibilityGovernance::schemaReady());}
 public function test_missing_required_column_fails_closed():void{Schema::table('supplementary_exam_theoretical_deferrals',fn(Blueprint $t)=>$t->dropColumn('supersede_reason'));$this->assertFalse(SupplementaryExamEligibilityGovernance::schemaReady());}
 public function test_missing_current_slot_unique_fails_closed():void{Schema::table('supplementary_exam_theoretical_deferrals',fn(Blueprint $t)=>$t->dropUnique('def_current'));$this->assertFalse(SupplementaryExamEligibilityGovernance::schemaReady());}
 public function test_missing_identity_unique_fails_closed():void{Schema::table('supplementary_exam_theoretical_deferrals',fn(Blueprint $t)=>$t->dropUnique('def_identity'));$this->assertFalse(SupplementaryExamEligibilityGovernance::schemaReady());}
 public function test_missing_event_history_index_fails_closed():void{Schema::table('supplementary_exam_theoretical_deferral_events',fn(Blueprint $t)=>$t->dropIndex('event_history'));$this->assertFalse(SupplementaryExamEligibilityGovernance::schemaReady());}
 public function test_missing_active_permission_fails_closed():void{DB::table('permissions')->where('permission_code','supplementary_exams.deferrals.self')->update(['is_active'=>0]);$this->assertFalse(SupplementaryExamEligibilityGovernance::schemaReady());}
 private function parents():void{Schema::create('users',fn(Blueprint$t)=>$t->integer('user_id')->autoIncrement());foreach(['academic_programs'=>'academic_program_id','courses'=>'course_id','course_offerings'=>'course_offering_id']as$n=>$id)Schema::create($n,fn(Blueprint$t)=>$t->integer($id)->autoIncrement());Schema::create('permissions',function(Blueprint$t){$t->integer('permission_id')->autoIncrement();$t->string('permission_code')->unique();$t->boolean('is_active');});DB::table('permissions')->insert([['permission_code'=>'supplementary_exams.eligibility.view','is_active'=>1],['permission_code'=>'supplementary_exams.deferrals.self','is_active'=>1]]);}
 private function phase1():void{Schema::create('supplementary_exam_periods',function(Blueprint$t){$t->integer('supplementary_exam_period_id')->autoIncrement();$t->integer('academic_year_id');$t->integer('semester_id');$t->string('status');$t->integer('opened_by_user_id')->nullable();$t->dateTime('opened_at')->nullable();$t->text('decision_note')->nullable();$t->unique(['academic_year_id','semester_id'],'period_identity');});Schema::create('supplementary_exam_period_events',function(Blueprint$t){$t->integer('supplementary_exam_period_event_id')->autoIncrement();$t->integer('supplementary_exam_period_id');$t->string('event_type');$t->string('from_status')->nullable();$t->string('to_status');$t->integer('actor_user_id');$t->text('notes')->nullable();$t->timestamp('created_at');$t->index('supplementary_exam_period_id');$t->index('actor_user_id');$t->index(['event_type','to_status']);$t->foreign('supplementary_exam_period_id')->references('supplementary_exam_period_id')->on('supplementary_exam_periods');$t->foreign('actor_user_id')->references('user_id')->on('users');});}
 private function phase2():void{Schema::create('supplementary_exam_offerings',function(Blueprint$t){$t->integer('supplementary_exam_offering_id')->autoIncrement();$t->integer('supplementary_exam_period_id');$t->integer('academic_program_id');$t->integer('course_id');$t->string('status',16);$t->integer('opened_by_user_id');$t->dateTime('opened_at');$t->integer('closed_by_user_id')->nullable();$t->dateTime('closed_at')->nullable();$t->timestamp('created_at');$t->timestamp('updated_at');$t->unique(['supplementary_exam_period_id','academic_program_id','course_id'],'off_identity');$t->foreign('supplementary_exam_period_id')->references('supplementary_exam_period_id')->on('supplementary_exam_periods');$t->foreign('academic_program_id')->references('academic_program_id')->on('academic_programs');$t->foreign('course_id')->references('course_id')->on('courses');$t->foreign('opened_by_user_id')->references('user_id')->on('users');$t->foreign('closed_by_user_id')->references('user_id')->on('users');});Schema::create('supplementary_exam_offering_sources',function(Blueprint$t){$t->integer('supplementary_exam_offering_source_id')->autoIncrement();$t->integer('supplementary_exam_offering_id');$t->integer('course_offering_id');$t->timestamp('created_at');$t->unique(['supplementary_exam_offering_id','course_offering_id'],'source_identity');$t->foreign('supplementary_exam_offering_id')->references('supplementary_exam_offering_id')->on('supplementary_exam_offerings');$t->foreign('course_offering_id')->references('course_offering_id')->on('course_offerings');});Schema::create('supplementary_exam_offering_events',function(Blueprint$t){$t->integer('supplementary_exam_offering_event_id')->autoIncrement();$t->integer('supplementary_exam_offering_id');$t->string('event_type');$t->string('from_status')->nullable();$t->string('to_status');$t->integer('actor_user_id');$t->text('notes')->nullable();$t->timestamp('created_at');$t->index('supplementary_exam_offering_id');$t->index('actor_user_id');$t->index(['event_type','to_status']);$t->foreign('supplementary_exam_offering_id')->references('supplementary_exam_offering_id')->on('supplementary_exam_offerings');$t->foreign('actor_user_id')->references('user_id')->on('users');});}
 private function phase3():void{Schema::create('student_course_registrations',fn(Blueprint$t)=>$t->integer('student_course_registration_id')->autoIncrement());Schema::create('supplementary_exam_theoretical_deferrals',function(Blueprint$t){$t->integer('supplementary_exam_theoretical_deferral_id')->autoIncrement();$t->integer('supplementary_exam_offering_id');$t->integer('student_course_registration_id');$t->string('status',16);$t->tinyInteger('current_slot')->nullable();$t->integer('declared_by_user_id');$t->dateTime('declared_at');$t->integer('cancelled_by_user_id')->nullable();$t->dateTime('cancelled_at')->nullable();$t->text('cancellation_reason')->nullable();$t->dateTime('superseded_at')->nullable();$t->text('supersede_reason')->nullable();$t->timestamp('created_at');$t->timestamp('updated_at');$t->unique(['supplementary_exam_offering_id','student_course_registration_id'],'def_identity');$t->unique(['student_course_registration_id','current_slot'],'def_current');$t->index('declared_by_user_id');$t->index('cancelled_by_user_id');$t->foreign('supplementary_exam_offering_id')->references('supplementary_exam_offering_id')->on('supplementary_exam_offerings');$t->foreign('student_course_registration_id')->references('student_course_registration_id')->on('student_course_registrations');$t->foreign('declared_by_user_id')->references('user_id')->on('users');$t->foreign('cancelled_by_user_id')->references('user_id')->on('users');});Schema::create('supplementary_exam_theoretical_deferral_events',function(Blueprint$t){$t->integer('supplementary_exam_theoretical_deferral_event_id')->autoIncrement();$t->integer('supplementary_exam_theoretical_deferral_id');$t->string('event_type',16);$t->string('from_status',16)->nullable();$t->string('to_status',16);$t->integer('actor_user_id');$t->text('notes')->nullable();$t->dateTime('created_at');$t->index(['supplementary_exam_theoretical_deferral_id','created_at'],'event_history');$t->index('actor_user_id');$t->foreign('supplementary_exam_theoretical_deferral_id')->references('supplementary_exam_theoretical_deferral_id')->on('supplementary_exam_theoretical_deferrals');$t->foreign('actor_user_id')->references('user_id')->on('users');});}
 private function drop():void{Schema::disableForeignKeyConstraints();foreach(['supplementary_exam_theoretical_deferral_events','supplementary_exam_theoretical_deferrals','student_course_registrations','supplementary_exam_offering_events','supplementary_exam_offering_sources','supplementary_exam_offerings','supplementary_exam_period_events','supplementary_exam_periods','course_offerings','courses','academic_programs','permissions','users']as$t)Schema::dropIfExists($t);Schema::enableForeignKeyConstraints();}
}
