<?php
namespace Tests\Feature;
use App\Support\SupplementaryExamPolicy;
use App\Support\SupplementaryExamRegistrationGovernance;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
class SupplementaryExamRegistrationContractTest extends TestCase
{
 #[Test] public function phase_four_is_phase_three_guarded_and_has_no_superadmin_mutation():void{$g=file_get_contents(app_path('Support/SupplementaryExamRegistrationGovernance.php'));$s=file_get_contents(app_path('Services/SupplementaryExamRegistrationService.php'));$w=file_get_contents(app_path('Services/SupplementaryExamRegistrationWindowService.php'));$this->assertStringContainsString('SupplementaryExamEligibilityGovernance::schemaReady()',$g);$this->assertStringContainsString('isRegistrationOfficer()',$s.$w);$this->assertStringContainsString('effectivePermissions()->contains',$s.$w);$this->assertStringNotContainsString('hasPermission(',$s.$w);}
 #[Test] public function registration_reuses_live_eligibility_provenance_policy_and_student_lock():void{$s=file_get_contents(app_path('Services/SupplementaryExamRegistrationService.php'));foreach(['Student::query()->lockForUpdate()','SupplementaryExamOfferingSource::query()','$this->eligibility->evaluate','SupplementaryExamPolicy::maxCoursesPerStudent','where(\'current_slot\',1)'] as $proof)$this->assertStringContainsString($proof,$s);$this->assertStringNotContainsString('StudentCourseRegistration::query()->create',$s);$this->assertStringNotContainsString('CourseOffering::query()->create',$s);}
 #[Test] public function lifecycle_has_no_reopen_and_closure_revalidates():void{$routes=file_get_contents(base_path('routes/api.php'));$w=file_get_contents(app_path('Services/SupplementaryExamRegistrationWindowService.php'));$this->assertStringContainsString("if (\$period->status === 'registration_closed')",$w);$this->assertStringContainsString("if (\$period->status !== 'registration_open')",$w);$this->assertStringContainsString('$this->eligibility->evaluate',$w);$this->assertStringNotContainsString('reopen-registration',$routes);}
 #[Test] public function closure_rejects_empty_duplicate_and_cross_period_targets_before_terminal_transition():void{$w=file_get_contents(app_path('Services/SupplementaryExamRegistrationWindowService.php'));foreach(["where('status', 'registered')","where('current_slot', 1)",'$rows->isEmpty()','supplementary_exam_registration_roster_empty',"orderBy('student_course_registration_id')",'$targetIds->unique()->count() !== $targetIds->count()','supplementary_exam_registration_duplicate_target_conflict',"whereNotIn('supplementary_exam_registration_id', \$rows->modelKeys())",'SupplementaryExamRegistrationGovernance::FIXED_ROSTER_PERIOD_STATUSES','supplementary_exam_registration_cross_period_target_conflict',"\$period->load('semester')","\$rows->load('offering.sources')",'$this->eligibility->evaluationContext(',"\$period->forceFill(['status' => 'registration_closed'])->save()"]as$proof)$this->assertStringContainsString($proof,$w);$transition=strpos($w,"\$period->forceFill(['status' => 'registration_closed'])->save()");foreach(['supplementary_exam_registration_roster_empty','supplementary_exam_registration_duplicate_target_conflict','supplementary_exam_registration_cross_period_target_conflict']as$code)$this->assertLessThan($transition,strpos($w,$code));$targetsLocked=strpos($w,"->keyBy('student_course_registration_id');");foreach(["\$period->load('semester')","\$rows->load('offering.sources')",'$this->eligibility->evaluationContext(']as$snapshot)$this->assertLessThan(strpos($w,$snapshot),$targetsLocked);}
 #[Test] public function centralized_summer_policy_remains_authoritative():void{$this->assertSame(3,SupplementaryExamPolicy::SUMMER_MAX_COURSES_PER_STUDENT);$s=file_get_contents(app_path('Services/SupplementaryExamRegistrationService.php'));$this->assertStringNotContainsString('semester_id === 3',$s);}
 #[Test] public function phase_four_period_context_does_not_expand_phase_one_period_permission():void{$routes=file_get_contents(base_path('routes/api.php'));$phase1=file_get_contents(app_path('Services/SupplementaryExamPeriodGovernanceService.php'));$phase4=file_get_contents(app_path('Http/Controllers/Api/SupplementaryExamRegistrationOfficeController.php'));$this->assertStringContainsString('supplementary-exam-registration-periods',$routes);$this->assertStringContainsString('SupplementaryExamPeriodGovernance::PERMISSION_VIEW',$phase1);$this->assertStringContainsString('SupplementaryExamRegistrationGovernance::VIEW',$phase4);$this->assertStringNotContainsString('SupplementaryExamPeriodGovernance::PERMISSION_VIEW',$phase4);}
}
