<?php
namespace Tests\Feature;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
class SupplementaryExamEligibilitySqlContractTest extends TestCase
{
 private function sql(string $name):string{return file_get_contents(database_path("sql/supplementary-exam-eligibility/$name"));}
 public function test_all_manual_files_obey_phpmyadmin_contract():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql']as$name){$sql=$this->sql($name);$this->assertDoesNotMatchRegularExpression('/\b(SIGNAL|DELIMITER|CREATE\s+PROCEDURE)\b|DATABASE\s*\(/i',$sql);$this->assertMatchesRegularExpression('/SELECT\s.+;\s*$/is',$sql);$this->assertStringContainsString("table_schema='alrowad_uni_rust'",str_replace(' = ','=',$sql));}}
 public function test_preflight_apply_and_verify_share_full_phase2_contract():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$name){$sql=$this->sql($name);foreach(['@phase_columns','@phase_primary_ai','@phase_fk_semantics','@phase_semantic_uniques','@phase_supporting_indexes','@dependency_rbac','@status_contract','@grade_policy_contract','@exam_module_contract']as$guard)$this->assertStringContainsString($guard,$sql,"$name missing $guard");$this->assertStringContainsString('PHASE2_NOT_DEPLOYED',$sql);}}
 public function test_target_compatibility_is_semantic_not_existence_based():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$name){$sql=$this->sql($name);foreach(['@deferral_contract','@deferral_fks','@deferral_indexes','@deferral_engine','@event_contract','@event_fks','@event_indexes','@event_engine',"'CONFLICT'"]as$guard)$this->assertStringContainsString($guard,$sql);}}
 public function test_apply_never_silently_adopts_or_overwrites():void{$sql=$this->sql('01_apply.sql');$this->assertStringNotContainsString('CREATE TABLE IF NOT EXISTS',$sql);$this->assertStringNotContainsString('ON DUPLICATE KEY UPDATE',$sql);$this->assertStringContainsString("@deferral_state='ABSENT'",$sql);$this->assertStringContainsString("@event_state='ABSENT'",$sql);$this->assertStringContainsString('@permission_collision',$sql);$this->assertStringContainsString('@off_matrix',$sql);}
 public function test_verify_catches_exact_rbac_null_invariant_orphans_and_duplicates():void{$sql=$this->sql('02_verify.sql');$this->assertStringContainsString("current_slot IS NULL OR current_slot<>1",$sql);foreach(['@rbac_exact=5','@off_matrix=0','@orphan_deferrals=0','@orphan_events=0','@duplicate_identity=0','@duplicate_current=0']as$check)$this->assertStringContainsString($check,$sql);}
 public function test_rollback_is_optional_table_safe_and_preserves_adopted_objects():void{$sql=$this->sql('03_rollback.sql');$this->assertStringContainsString("IF(@deferral_exists=1",$sql);$this->assertStringContainsString("IF(@event_exists=1",$sql);$this->assertStringContainsString('@deferral_owned=1',$sql);$this->assertStringContainsString('@event_owned=1',$sql);$this->assertStringContainsString('BLOCKED_IN_USE',$sql);$this->assertDoesNotMatchRegularExpression('/^SELECT COUNT\(\*\).*FROM `alrowad_uni_rust`\.`supplementary_exam_theoretical_/m',$sql);}
 public function test_pack_does_not_create_phase4_or_mutate_academic_results():void{$all=implode("\n",array_map(fn($f)=>$this->sql($f),['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql']));$this->assertStringNotContainsString('CREATE TABLE `alrowad_uni_rust`.`supplementary_exam_registrations`',$all);$this->assertStringNotContainsString('UPDATE `alrowad_uni_rust`.`student_course_results`',$all);$this->assertStringNotContainsString('UPDATE `alrowad_uni_rust`.`student_grade_components`',$all);}
}
