<?php
namespace Tests\Feature;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
class SupplementaryExamGradingContractTest extends TestCase
{
 private function service():string{return file_get_contents(app_path('Services/SupplementaryExamGradingService.php'));}
 #[Test] public function fixed_roster_and_canonical_theoretical_only_policy_are_enforced():void{$s=$this->service();$this->assertMatchesRegularExpression("/where\\('status',\\s*'registered'\\)/",$s);$this->assertMatchesRegularExpression("/where\\('current_slot',\\s*1\\)/",$s);foreach(['gradingPolicyLimits()','theoretical_max_mark','buildCalculationForRequiredParts(','preserved_practical_mark'] as $x)$this->assertStringContainsString($x,$s);foreach(['StudentCourseResult::query()->update','StudentGradeComponent::','GradeApproval::query()->update','GradeApproval::query()->create','GradePartApproval::'] as $x)$this->assertStringNotContainsString($x,$s);}
 #[Test] public function actual_roles_permissions_assignment_and_scope_are_all_required():void{$s=$this->service();foreach(['isProfessor()','isExamOfficer()','effectivePermissions()->contains','assertAssigned(','canMutateProgram('] as $x)$this->assertStringContainsString($x,$s);$this->assertStringNotContainsString('hasPermission(',$s);}
 #[Test] public function lock_order_and_complete_versioned_batch_are_explicit():void{$s=$this->service();$this->assertStringContainsString('period, offering, current assignment, registrations',$s);foreach(['lockForUpdate()','supplementary_grade_batch_incomplete','submission_version + 1','supplementary_grade_stale_submission','supplementary_grade_version_mismatch'] as $x)$this->assertStringContainsString($x,$s);}
 #[Test] public function return_approve_publish_and_audit_are_isolated():void{$s=$this->service();foreach(["\$action==='return'","\$action==='approve'","\$action==='publish'",'SupplementaryExamGradeEvent::query()->create','results_published','official_record_materialized'] as $x)$this->assertStringContainsString($x,$s);}
 #[Test] public function review_queue_is_bounded_to_active_non_terminal_periods():void{$s=$this->service();$this->assertStringContainsString('Governance::REVIEW_QUEUE_PERIOD_STATUSES',$s);$g=file_get_contents(app_path('Support/SupplementaryExamGradingGovernance.php'));$this->assertMatchesRegularExpression("/REVIEW_QUEUE_PERIOD_STATUSES\\s*=\\s*\\[[^;]+/s",$g);preg_match("/REVIEW_QUEUE_PERIOD_STATUSES\\s*=\\s*\\[(.*?)\\];/s",$g,$m);foreach(['registration_closed','grading_open','grading_submitted','results_approved','results_published'] as$x)$this->assertStringContainsString("'{$x}'",$m[1]);$this->assertStringNotContainsString("'results_materialized'",$m[1]);}
 #[Test] public function review_queue_response_preserves_data_array_and_adds_scope_filtered_terminal_catalog():void{$s=$this->service();$this->assertMatchesRegularExpression('~function reviewPeriodCatalog\(User \$actor\): array.*?\$this->exam\(\$actor, Governance::REVIEW\).*?scopeProgramsForMutation\(\$programs, \$actor\).*?orderByDesc\(\'supplementary_exam_period_id\'\).*?limit\(100\).*?->all\(\);~s',$s);$this->assertSame(1,preg_match('~public function reviewPeriodCatalog\(User \$actor\): array.*?^    }~ms',$s,$catalog));foreach(['Governance::REVIEW_QUEUE_PERIOD_STATUSES',"whereIn('status'"]as$x)$this->assertStringNotContainsString($x,$catalog[0]);$c=file_get_contents(app_path('Http/Controllers/Api/SupplementaryExamGradingController.php'));foreach(["'data' => \$materializations->decorateReviewQueue","'periods' => \$service->reviewPeriodCatalog"]as$x)$this->assertStringContainsString($x,$c);$f=file_get_contents(base_path('../frontend/src/features/exam-board/pages/SupplementaryGradesPage.jsx'));foreach(['response?.periods ?? []','payload.periods']as$x)$this->assertStringContainsString($x,$f);$this->assertStringNotContainsString('/v1/supplementary-exam-periods',$f);}
 #[Test] public function opening_grading_rejects_premature_artifacts():void{$s=$this->service();foreach(['assertNoPrematureGradingArtifacts(','SupplementaryExamGradeResult::query()','SupplementaryExamGradeSubmission::query()','SupplementaryExamGradeEvent::query()','supplementary_grading_premature_artifacts']as$x)$this->assertStringContainsString($x,$s);}
 #[Test] public function professor_and_exam_routes_exist():void{$r=file_get_contents(base_path('routes/api.php'));foreach(['professor/supplementary-exams','/grades\'','/submit\'','/resubmit\'','exams/supplementary-grades','/return\'','/approve\'','/publish\'','/grader\'','open-grading'] as $x)$this->assertStringContainsString($x,$r);}
}
