<?php
namespace Tests\Feature;
use Tests\TestCase;
class SupplementaryExamRegistrationSqlContractTest extends TestCase
{
 private function sql($n){return file_get_contents(database_path("sql/supplementary-exam-registration/$n"));}
 public function test_phpmyadmin_policy():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql'] as $n){$s=$this->sql($n);$this->assertDoesNotMatchRegularExpression('/\b(SIGNAL|DELIMITER|CREATE\s+PROCEDURE)\b|DATABASE\s*\(/i',$s);$this->assertMatchesRegularExpression('/SELECT\s.+;\s*$/is',$s);$this->assertStringContainsString("table_schema='alrowad_uni_rust'",$s);}}
 public function test_forward_scripts_share_full_dependency_and_target_contracts():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql'] as $n){$s=$this->sql($n);foreach(['@dependency_tables','@dependency_columns','@dependency_primary_ai','@dependency_types','@dependency_semantic_uniques','@dependency_fks','@dependency_supporting_indexes','@dependency_rbac','@dependency_forbidden_mappings','@period_lifecycle_width_ready','character_maximum_length>=19','@reg_columns','@reg_engine','@reg_indexes','@reg_fks','@reg_signedness','@event_columns','@event_engine','@event_indexes','@event_fks','@event_signedness',"'ABSENT'","'COMPATIBLE'","'CONFLICT'"] as $guard)$this->assertStringContainsString($guard,$s,"$n missing $guard");}}
 public function test_event_compatibility_is_named_typed_and_semantic():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);$this->assertStringContainsString("table_name='supplementary_exam_registration_events'",$s);$this->assertStringContainsString("column_name='supplementary_exam_registration_event_id'",$s);$this->assertStringContainsString("supplementary_exam_registration_id,created_at",$s);$this->assertStringContainsString('@event_fks',$s);}}
 public function test_rbac_collision_and_off_matrix_are_blocking():void{foreach(['00_preflight.sql','01_apply.sql','02_verify.sql']as$n){$s=$this->sql($n);foreach(['@permission_collision','@permission_duplicates','@off_matrix']as$x)$this->assertStringContainsString($x,$s);}$this->assertStringContainsString('RBAC_CONFLICT',$this->sql('00_preflight.sql'));$this->assertStringContainsString('RBAC_CONFLICT',$this->sql('01_apply.sql'));$this->assertStringContainsString('RBAC_INVALID',$this->sql('02_verify.sql'));}
 public function test_verify_checks_duplicates_provenance_null_slot_and_summer_order():void{$v=$this->sql('02_verify.sql');foreach(['@duplicate_identity','@duplicate_current','supplementary_exam_offering_sources','scr.student_id<>r.student_id','current_slot IS NULL OR r.current_slot<>1','semester_order=3','HAVING COUNT(*)>3']as$x)$this->assertStringContainsString($x,$v);$this->assertStringNotContainsString('semester_id=3',$v);}
 public function test_apply_and_rollback_are_conservative():void{$a=$this->sql('01_apply.sql');$this->assertStringNotContainsString('CREATE TABLE IF NOT EXISTS',$a);$this->assertStringContainsString("@reg_state='ABSENT'",$a);$this->assertStringContainsString("@event_state='ABSENT'",$a);$r=$this->sql('03_rollback.sql');foreach(['@reg_exists','@event_exists','@reg_owned','@event_owned','BLOCKED_IN_USE']as$x)$this->assertStringContainsString($x,$r);}
 public function test_no_forbidden_academic_mutations():void{$all=implode("\n",array_map(fn($n)=>$this->sql($n),['00_preflight.sql','01_apply.sql','02_verify.sql','03_rollback.sql']));foreach(['INSERT INTO `alrowad_uni_rust`.`student_course_registrations`','INSERT INTO `alrowad_uni_rust`.`course_offerings`','UPDATE `alrowad_uni_rust`.`supplementary_exam_results`'] as $x)$this->assertStringNotContainsString($x,$all);}
}
