<?php

$contract = static function (string $backendRoot): array {
    $errors=[];
    $expect=static function(bool $condition,string $message)use(&$errors):void{if(!$condition)$errors[]=$message;};
    $read=static fn(string $path):string=>is_file($path)?(string)file_get_contents($path):'';
    $sqlRoot=$backendRoot.'/database/sql/semester-registration-minimum-cancellation-replacement-phase6';
    $files=is_dir($sqlRoot)?array_map('basename',glob($sqlRoot.'/*')?:[]):[];sort($files);
    $expect($files===['00_preflight.sql','01_apply.sql','02_verify.sql'],'Phase 6 SQL package must contain exactly preflight/apply/verify.');
    $preflight=$read($sqlRoot.'/00_preflight.sql');$apply=$read($sqlRoot.'/01_apply.sql');$verify=$read($sqlRoot.'/02_verify.sql');
    foreach([$preflight,$apply,$verify] as $sql){$expect(str_contains($sql,'alrowad_uni_rust'),'Every SQL file must target alrowad_uni_rust.');$expect(!preg_match('/\b(?:PROCEDURE|DELIMITER|SIGNAL|DATABASE\s*\()\b/i',$sql),'SQL must avoid procedures, DELIMITER, SIGNAL, and DATABASE().');$expect(!preg_match('/ON\s+DELETE\s+CASCADE/i',$sql),'Phase 6 foreign keys must be restrictive.');}
    $expect(substr_count(strtoupper($apply),'CREATE TABLE IF NOT EXISTS')===5,'Apply must create exactly five Phase 6 business tables.');
    foreach(['course_offering_minimum_enrollment_reviews','course_offering_minimum_enrollment_events','student_registration_replacement_requests','student_registration_replacement_items','student_registration_replacement_events'] as $table){$expect(str_contains($apply,$table)&&str_contains($verify,$table),"Missing table contract {$table}.");}
    foreach(['uq_srrpi_source_consumed','uq_srrpi_source_in_request','uq_srrpi_target_in_request','chk_srrpi_consumed','chk_srrpr_return','chk_srrpr_snapshot','chk_comer_dean_status'] as $marker)$expect(str_contains($apply,$marker)&&str_contains($verify,$marker),"Missing Phase 6 invariant {$marker}.");
    $expect(str_contains($apply,'`source_student_course_registration_id`,`source_consumed_slot`')&&str_contains($verify,"cols='source_student_course_registration_id,source_consumed_slot'"),'Consumed-source unique column order is incorrect.');
    $expect(!preg_match('/UNIQUE KEY[^\n]+\(`source_student_course_registration_id`\)\s*[,)]/i',$apply),'Source registration must not be globally unique merely for historical reference.');
    foreach(['target_column_types','target_nullability','target_pk','target_checks','target_fks','target_fk_mappings','target_uniques','target_indexes'] as $guard)$expect(str_contains($preflight,$guard),"Preflight partial-schema compatibility is missing {$guard}.");
    foreach(['existing_pk','existing_checks','existing_fks','existing_uniques'] as $guard)$expect(str_contains($apply,$guard),"Apply partial-schema compatibility is missing {$guard}.");
    $expect(str_contains($apply,'course_registration_replacement')&&str_contains($apply,'s.event_type_kind,s.default_is_enforcement,s.is_active'),'Replacement event type must clone canonical behavioral metadata.');
    $expect(str_contains($preflight,'SOURCE_EVENT_METADATA')&&str_contains($preflight,'event_type_kind')&&str_contains($preflight,'default_is_enforcement')&&str_contains($preflight,'is_active'),'Preflight must visibly report cloned source metadata.');
    $expect(str_contains($apply,'cancelled')&&str_contains($apply,'ملغى لعدم اكتمال الحد الأدنى')&&str_contains($verify,"status_code=''cancelled''"),'Cancelled status reference contract is missing.');
    $expect(!preg_match('/(?:permissions|role_permissions|user_roles)[^;]*(?:INSERT|UPDATE|DELETE)|(?:INSERT|UPDATE|DELETE)[^;]*(?:permissions|role_permissions|user_roles)/is',$apply),'Phase 6 must not write RBAC data.');
    $expect(str_contains($preflight,"SELECT 'OVERALL'")&&str_contains($preflight,"'READY','BLOCKED'"),'Preflight terminal result is missing.');
    foreach(['APPLIED','RESUMED','ALREADY_APPLIED'] as $result)$expect(str_contains($apply,$result),"Apply terminal result {$result} is missing.");
    $expect(str_contains($verify,"SELECT 'OVERALL'")&&str_contains($verify,"'PASS','FAIL'"),'Verify terminal result is missing.');

    $policy=$read($backendRoot.'/app/Services/AcademicCalendarPolicyService.php');$calendar=$read($backendRoot.'/app/Services/AcademicCalendarService.php');$minimum=$read($backendRoot.'/app/Services/MinimumEnrollmentReviewService.php');$materializer=$read($backendRoot.'/app/Services/MinimumEnrollmentCancellationMaterializer.php');$closure=$read($backendRoot.'/app/Services/CourseOfferingClosureWorkflowService.php');$replacement=$read($backendRoot.'/app/Services/RegistrationReplacementService.php');$phaseException=$read($backendRoot.'/app/Exceptions/SemesterRegistrationPhase6Exception.php');$registration=$read($backendRoot.'/app/Services/RegistrationService.php');$governance=$read($backendRoot.'/app/Services/SemesterOfferingGovernanceService.php');$routes=$read($backendRoot.'/routes/api.php');
    $expect(str_contains($policy,'courseRegistrationReplacementDeadlines')&&str_contains($policy,'registrationDeadlinesFor(self::COURSE_REGISTRATION_REPLACEMENT_EVENT_TYPE, false'),'Replacement deadlines must reject the original legacy fallback.');
    $expect(str_contains($policy,'courseRegistrationReplacementDeadlinesMissing')||str_contains($policy,'course_registration_replacement_deadlines_missing'),'Stable replacement deadline configuration reason is missing.');
    $expect(str_contains($minimum,"whereNotNull('minimum_enrollment')")&&str_contains($minimum,"\$offering->status === 'closed' ? 'superseded'")&&str_contains($minimum,'superseded_external_closure'),'Closed applicable Offerings must reconcile to terminal superseded history.');
    $expect(str_contains($minimum,'TERMINAL_MINIMUM_STATUSES')&&str_contains($minimum,'replacement_window_not_ready'),'Replacement publication readiness must wait for every minimum decision.');
    $expect(str_contains($calendar,'assertReplacementWindowReady')&&str_contains($calendar,"whereNotNull('first_submitted_at')"),'Calendar publication and post-submission freeze guards are missing.');
    $expect(str_contains($materializer,"transitionRegisteredToCancelled")&&str_contains($materializer,"status'=>'cancelled'")&&str_contains($materializer,'course_offering_closure_request_id'),'Only a linked formal closure may materialize cancellation.');
    $expect(str_contains($closure,"SemesterRegistrationPhase6::schemaReady()) \$relations[] = 'minimumEnrollmentReview'")&&str_contains($materializer,'if (! SemesterRegistrationPhase6::schemaReady()) return'),'Existing closure reads and ordinary closure must remain compatible before manual Phase 6 deployment.');
    $expect(str_contains($registration,'transitionRegisteredToCancelled')&&str_contains($registration,'CANCELLED_STATUS'),'Canonical cancelled transition is missing.');
    $expect(str_contains($replacement,"where('source_consumed_slot',1)")&&str_contains($registration,"'source_consumed_slot'=>1")&&str_contains($phaseException,'replacement_source_already_consumed'),'Replacement source consumption must be rechecked and committed only with materialization.');
    $expect(str_contains($replacement,'materializeAdvisorApprovedReplacementItemWithinTransaction')&&str_contains($registration,'materializeAdvisorApprovedReplacementItemWithinTransaction'),'Trusted replacement materialization boundary is missing.');
    $boundary=substr($registration,strpos($registration,'public function materializeAdvisorApprovedReplacementItemWithinTransaction'),strpos($registration,'public function hoursSnapshot')-strpos($registration,'public function materializeAdvisorApprovedReplacementItemWithinTransaction'));
    $expect(!str_contains(substr($boundary,0,strpos($boundary,'): array')?:300),'peerOfferingIds')&&str_contains($boundary,'where(\'student_registration_replacement_request_id\',$lockedRequest->getKey())'),'Trusted boundary must derive the complete persisted request and accept no caller peer list.');
    $expect(str_contains($boundary,"'registration_replacement_validation_failed'")&&str_contains($boundary,'courseRegistrationReplacementDeadlines')&&str_contains($boundary,'source_minimum_enrollment_review_id'),'Trusted boundary must revalidate aggregate eligibility, deadline, and source provenance.');
    foreach(['uq_srrpi_source_consumed','uq_srrpi_source_in_request','uq_srrpi_target_in_request'] as $unique)$expect(str_contains($replacement,$unique),"Missing domain mapping for {$unique}.");
    $expect(str_contains($replacement,'registration_replacement_stale')||str_contains($phaseException,'registration_replacement_stale'),'Stable replacement stale response is missing.');
    $expect(str_contains($replacement,'EVENT_REPLACEMENT_SOURCE_CHANGED')&&str_contains($replacement,'EVENT_REPLACEMENT_CALENDAR_CHANGED')&&str_contains($replacement,'academic_calendar_event_id'),'Replacement requests must remain bound to their exact event and persist stale provenance.');
    $expect(str_contains($replacement,"['outcome'=>'superseded']")&&str_contains($replacement,"if(\$currentOutcome['outcome']==='current')")&&substr_count($replacement,'DB::transaction(function()use($student,$actor,$yearId,$semesterId,$deadline)')>=2,'Create must commit stale-request supersession before a later no-source failure can be reported.');
    $expect(str_contains($replacement,'replacement_target_already_registered')&&str_contains($replacement,'currentOfferingIds'),'Current registered replacement targets must fail before submission.');
    $expect(str_contains($replacement,"'expired'")&&str_contains($replacement,"'current_slot',1")&&str_contains($replacement,"'expired',null,\$from,'expired'"),'Replacement expiration must release the current slot without consuming historical sources.');
    $expect(str_contains($governance,'assertFinallyApprovedForReplacement')&&str_contains($governance,'assertMinimumEnrollmentApplicability')&&str_contains($minimum,'assertMinimumEnrollmentApplicability'),'Phase 6 must use canonical Phase 1 proofs for targets and minimum applicability.');
    foreach(['official_cgpa','below_recommended_minimum','official_timetable','eligibility_failures','history'] as $field)$expect(str_contains($replacement,$field),"Replacement server presentation is missing {$field}.");
    foreach(['dean/registration-offerings/minimum-enrollment','vice-presidency/scientific/semester-offerings/minimum-enrollment','student/registration/replacement','academic-advising/registration-replacements'] as $route)$expect(str_contains($routes,$route),"Missing Phase 6 route {$route}.");
    $expect(!str_contains($routes,'minimum_enrollment.manage')&&!str_contains($routes,'registration_replacement.manage'),'Phase 6 must add no permission code.');
    $viewGroup=strpos($routes,"RequirePermission::class.':registration_requests.view'");$reviewGroup=strpos($routes,"RequirePermission::class.':registration_requests.review'");$replacementGets=strpos($routes,"Route::get('academic-advising/registration-replacements'");$replacementPosts=strpos($routes,"Route::post('academic-advising/registration-replacements");
    $expect($viewGroup!==false&&$replacementGets!==false&&$reviewGroup!==false&&$replacementPosts!==false&&$viewGroup<$replacementGets&&$replacementGets<$reviewGroup&&$reviewGroup<$replacementPosts,'Advisor replacement GET routes must use view middleware while decisions use review middleware.');
    $expect((glob($backendRoot.'/database/migrations/*replacement*')?:[])===[]&&(glob($backendRoot.'/database/migrations/*minimum*enrollment*')?:[])===[],'Phase 6 must add no migrations.');
    $expect(!str_contains($replacement,'available_seats')&&!str_contains($replacement,'capacity'),'Replacement workflow must not implement seat capacity.');
    foreach(['GradeService.php','RegistrationWithdrawalService.php','AttendanceService.php'] as $unrelated){$source=$read($backendRoot.'/app/Services/'.$unrelated);$expect(!str_contains($source,'RegistrationReplacementService')&&!str_contains($source,'MinimumEnrollmentReviewService'),"{$unrelated} must remain independent.");}
    $behavior=$read($backendRoot.'/tests/Feature/SemesterRegistrationMinimumCancellationReplacementPhase6BehaviorTest.php');
    foreach(['test_closed_before_first_reconciliation_creates_terminal_superseded_without_cancellation_or_replacement_rights','test_expired_and_superseded_history_can_reuse_source_until_one_materialization_consumes_it','test_ordinary_closure_without_a_linked_phase6_review_does_not_cancel_registrations','test_linked_formal_minimum_closure_cancels_current_rows_and_finalizes_review_atomically','test_full_minimum_cancellation_bridge_requires_both_vps_and_cancels_only_on_administrative_materialization','test_minimum_cannot_finalize_before_or_at_the_inclusive_advisor_deadline','test_registered_count_excludes_dropped_withdrawn_cancelled_and_pending_workflow_rows','test_minimum_comparison_handles_above_equal_and_below_and_is_idempotent','test_contradictory_phase1_minimum_fails_closed_without_review','test_trusted_boundary_revalidates_complete_request_and_materializes_nothing_when_aggregate_exceeds_cap','test_multi_target_replacement_rolls_back_first_materialization_when_second_target_fails_inside_trusted_boundary','test_replacement_event_change_supersedes_old_draft_without_rebinding_it','test_create_commits_stale_supersession_before_reporting_that_no_eligible_source_remains','test_stale_source_is_persistently_superseded_before_conflict_is_returned','test_current_registered_target_is_rejected_before_request_submission'] as $name)$expect(str_contains($behavior,$name),"Missing real behavior regression {$name}.");
    $calendarUtils=$read(dirname($backendRoot).'/frontend/src/features/academic-calendar/calendarUtils.js');
    $calendarPage=$read(dirname($backendRoot).'/frontend/src/features/academic-calendar/AcademicCalendarPage.jsx');
    $calendarTests=$read(dirname($backendRoot).'/frontend/tests/academicCalendarUtils.test.mjs');
    $expect(str_contains($calendarUtils,'isRegistrationDeadlineType')&&str_contains($calendarUtils,"'course_registration_replacement'"),'Academic Calendar UI must use one predicate for original and replacement registration deadline types.');
    $expect(str_contains($calendarPage,'usesRegistrationDeadlines')&&str_contains($calendarPage,'student_registration_ends_at')&&str_contains($calendarPage,'advisor_approval_ends_at'),'Both registration event types must share specialized deadline form and payload semantics.');
    $expect(str_contains($calendarTests,'original and replacement registration windows share specialized deadline form and payload semantics'),'Missing replacement Academic Calendar UI regression.');
    foreach(['semester_offering_reviews','semester_offering_events','course_offering_closure_events','student_registration_withdrawal_requests','student_registration_withdrawal_events','course_offering_schedule_slots','academic_requirement_groups','program_courses','course_prerequisites','academic_calendar.manage'] as $dependency)$expect(str_contains($preflight,$dependency)&&str_contains($apply,$dependency)&&str_contains($verify,$dependency),"SQL dependency/RBAC contract is missing {$dependency}.");
    $expect(str_contains($preflight,'@srp6_mappings=8')&&str_contains($apply,'@srp6_mappings=8')&&str_contains($verify,'@srp6v_mappings=8'),'SQL package must verify all eight active role/permission mappings.');
    $expect(str_contains($preflight,'@srp6_target_total_columns=@srp6_expected_target_columns')&&str_contains($apply,'@srp6_existing_total_columns=@srp6_existing_expected_columns')&&str_contains($verify,'@srp6v_total_columns=74'),'Existing Phase 6 tables must have an exact owned column set.');
    $expect(str_contains($preflight,'@srp6_target_column_types=@srp6_expected_target_columns')&&str_contains($apply,'@srp6_existing_column_types=@srp6_existing_expected_columns')&&str_contains($verify,'@srp6v_column_types=74'),'Existing Phase 6 tables must preserve exact owned data types and signedness.');
    $expect(str_contains($preflight,'@srp6_target_nullability=@srp6_expected_target_columns')&&str_contains($apply,'@srp6_existing_not_null=@srp6_existing_expected_not_null')&&str_contains($verify,'@srp6v_not_null=36'),'Existing Phase 6 tables must preserve the owned nullability contract.');
    $expect(str_contains($preflight,'@srp6_target_fk_mappings=@srp6_expected_target_fks')&&str_contains($apply,'@srp6_existing_fk_mappings=@srp6_existing_expected_fks')&&str_contains($verify,'@srp6v_fk_mappings=21'),'Existing Phase 6 foreign keys must map the exact owned child and parent columns.');
    $expect(str_contains($preflight,'@srp6_target_indexes=@srp6_expected_target_indexes')&&str_contains($apply,'@srp6_existing_indexes=@srp6_existing_expected_indexes')&&str_contains($verify,'@srp6v_indexes=12'),'All required non-unique indexes must be verified during preflight, adoption, and verification.');
    return $errors;
};

if(realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){$errors=$contract(dirname(__DIR__,2));if($errors){foreach($errors as $error)fwrite(STDERR,$error.PHP_EOL);exit(1);}fwrite(STDOUT,"Semester Registration Phase 6 contract passed.\n");}
return $contract;
