import { useState } from 'react'
import { coursePayload, editableCourse } from './catalog'
import { Button, CatalogDialog, CatalogLookup, Field, Input, Notice } from './CatalogControls'
import CatalogConflict from './CatalogConflict'
import useCatalogMutation from './useCatalogMutation'

export default function CourseEditor({ baseline, onDirty, onBusy, onBlocked, onSaved, onRestart, onUnauthorized, busy }) {
  const [draft, setDraft] = useState(() => editableCourse(baseline)), [confirm, setConfirm] = useState(null)
  const id = baseline.data?.course_id, caps = baseline.capabilities || { edit_text: true, edit_academic: true, edit_relationships: true, delete: false }
  const mutation = useCatalogMutation({ currentPath: id ? `/courses/${id}` : '/courses', onSaved, onBusy, onBlocked, onUnauthorized })
  const disabled = busy || mutation.blocked
  function change(field, value) { setDraft(d => ({ ...d, [field]: value })); onDirty(true) }
  const lock = caps.origin_lock_reason || caps.academic_lock_reason
  const relationsLock = caps.relationship_lock_reason || lock
  const save = () => { const payload = coursePayload(draft, baseline); if (baseline.impact?.shared) setConfirm('save'); else mutation.write(id ? `/courses/${id}` : '/courses', id ? 'PUT' : 'POST', payload) }
  return <section className="space-y-4" aria-label="محرر أصل المادة"><Notice>هذا أصل المادة في الدليل الجامعي. التصنيف والمستوى والفصل الإرشاديان وميزانية المتطلبات تُدار منفصلة داخل البرنامج. لا يؤدي الحفظ إلى إنشاء طرح أو تسجيل.</Notice>
    {baseline.impact?.shared && <Notice>مادة مشتركة مرتبطة بـ {baseline.impact.linked_program_count} برامج؛ تصحيح أصلها يظهر في جميع تلك الارتباطات.</Notice>}
    <form onSubmit={e => { e.preventDefault(); if (!disabled) save() }} className="space-y-4">
      <fieldset disabled={disabled || !caps.edit_text} className="grid gap-3 md:grid-cols-2"><Field label="اسم المادة" error={mutation.fields.course_name}><Input name="course_name" required maxLength={200} value={draft.course_name} onChange={e => change('course_name', e.target.value)} /></Field><Field label="الوصف" error={mutation.fields.description}><textarea name="description" className="rounded-xl border p-2" value={draft.description} onChange={e => change('description', e.target.value)} /></Field></fieldset>
      {caps.origin_lock_reason && <Notice>{caps.origin_lock_reason}</Notice>}{lock && <Notice>{lock}</Notice>}
      <fieldset disabled={disabled || !caps.edit_academic} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="رمز المادة — فريد جامعيًا" error={mutation.fields.course_code}><Input name="course_code" dir="ltr" required maxLength={50} value={draft.course_code} onChange={e => change('course_code', e.target.value)} /></Field>{[['credit_hours', 'الساعات المعتمدة'], ['theoretical_hours', 'الساعات النظرية'], ['practical_hours', 'الساعات العملية']].map(([field, label]) => <Field key={field} label={label} error={mutation.fields[field]}><Input name={field} dir="ltr" type="number" min={field === 'credit_hours' ? 1 : 0} step="1" required={field === 'credit_hours'} value={draft[field]} onChange={e => change(field, e.target.value)} /></Field>)}<label className="flex items-center gap-2"><input type="checkbox" checked={!!draft.is_active} onChange={e => change('is_active', e.target.checked)} />مادة نشطة</label></fieldset>
      <fieldset disabled={disabled || !caps.edit_relationships} className="space-y-3 rounded-xl border p-3"><legend className="font-bold">الأقسام المالكة لأصل المادة</legend>{relationsLock && <Notice>{relationsLock}</Notice>}{draft.departments.map((d, i) => <div key={d.department_id} className="flex flex-wrap items-center justify-between gap-2"><span>{d.label}</span><label><input type="checkbox" checked={d.is_primary} onChange={e => change('departments', draft.departments.map((r, n) => ({ ...r, is_primary: n === i && e.target.checked })))} /> قسم أساسي</label><Button onClick={() => change('departments', draft.departments.filter((_, n) => n !== i))}>إزالة القسم</Button></div>)}<CatalogLookup label="إضافة قسم مالك" resource="departments" clearLabel="اختر قسمًا" disabled={disabled || !caps.edit_relationships} onChange={o => { if (o && !draft.departments.some(d => d.department_id === o.id)) change('departments', [...draft.departments, { department_id: o.id, is_primary: false, label: o.label }]) }} /></fieldset>
      <fieldset disabled={disabled || !caps.edit_relationships} className="space-y-3 rounded-xl border p-3"><legend className="font-bold">المتطلبات السابقة الحقيقية</legend><p className="text-xs text-text-light">يتحقق الخادم من التكرار والمتطلب الذاتي والدورات قبل أي كتابة.</p>{draft.prerequisites.map((p, i) => <div key={p.prerequisite_course_id} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><span>{p.label}</span><CatalogLookup label={`حد نتيجة ${p.label}`} resource="result_statuses" disabled={disabled || !caps.edit_relationships} clearLabel="دون حد إضافي" value={p.minimum_result_status_id ? { id: p.minimum_result_status_id, label: p.statusLabel || 'حالة النتيجة الحالية' } : null} onChange={o => change('prerequisites', draft.prerequisites.map((r, n) => n === i ? { ...r, minimum_result_status_id: o?.id ?? '', statusLabel: o?.label } : r))} /><Button onClick={() => change('prerequisites', draft.prerequisites.filter((_, n) => n !== i))}>إزالة المتطلب</Button></div>)}<CatalogLookup label="إضافة متطلب سابق" resource="courses" disabled={disabled || !caps.edit_relationships} clearLabel="اختر مادة" onChange={o => { if (o && String(o.id) !== String(id) && !draft.prerequisites.some(p => p.prerequisite_course_id === o.id)) change('prerequisites', [...draft.prerequisites, { prerequisite_course_id: o.id, minimum_result_status_id: '', label: o.label }]) }} /></fieldset>
      <CatalogConflict mutation={mutation} onRestart={onRestart} />
      <div className="flex flex-wrap gap-3">{caps.edit_text && <Button primary type="submit" disabled={disabled}>{busy ? 'جارٍ الحفظ…' : id ? 'حفظ أصل المادة' : 'إضافة المادة إلى الدليل'}</Button>}{id && <Button danger disabled={disabled || !caps.delete} onClick={() => setConfirm('delete')}>حذف المادة غير المستخدمة</Button>}</div>{caps.delete_reasons?.map(reason => <p key={reason} className="text-xs text-text-light">منع الحذف: {reason}</p>)}
    </form>
    {confirm && <CatalogDialog title={confirm === 'delete' ? 'تأكيد حذف أصل المادة' : 'تأكيد تعديل مادة مشتركة'} onClose={() => setConfirm(null)}><p className="mb-4">{draft.course_name} ({draft.course_code}) — {confirm === 'delete' ? 'الحذف مستقل عن فصل ارتباط البرنامج، ولا يسمح به عند وجود أي مرجع مانع.' : 'سيظهر التصحيح في جميع البرامج المرتبطة، ولن تُعدّل ميزانياتها.'}</p><div className="flex gap-2"><Button onClick={() => setConfirm(null)}>إلغاء</Button><Button primary onClick={() => { const action = confirm; setConfirm(null); mutation.write(id ? `/courses/${id}` : '/courses', action === 'delete' ? 'DELETE' : id ? 'PUT' : 'POST', action === 'delete' ? { revision: baseline.revision, confirmed: true } : { ...coursePayload(draft, baseline), impact_confirmed: true }) }}>تأكيد</Button></div></CatalogDialog>}
  </section>
}
