import { useState } from 'react'
import { SCOPES, TYPES } from './catalog'
import { Button, CatalogDialog, CatalogLookup, Field, Input, Notice, Select } from './CatalogControls'
import CatalogConflict from './CatalogConflict'
import useCatalogMutation from './useCatalogMutation'

const scopes = Object.entries(SCOPES).filter(([key]) => key !== 'unclassified')
const types = Object.entries(TYPES).filter(([key]) => key !== 'unclassified')
export function RequirementGroupEditor({ baseline, onDirty, onBusy, onBlocked, onSaved, onRestart, onUnauthorized, busy }) {
  const [groups, setGroups] = useState(() => baseline.groups.map(g => ({ ...g }))), [total, setTotal] = useState(baseline.data.total_credit_hours), [confirm, setConfirm] = useState(false)
  const mutation = useCatalogMutation({ currentPath: `/programs/${baseline.data.academic_program_id}`, onSaved, onBusy, onBlocked, onUnauthorized })
  const disabled = busy || mutation.blocked || !baseline.capabilities.edit_curriculum
  const update = (i, key, value) => { setGroups(rows => rows.map((r, n) => n === i ? { ...r, [key]: value } : r)); onDirty(true) }
  function save() {
    setConfirm(false)
    mutation.write(`/programs/${baseline.data.academic_program_id}/requirement-groups`, 'PUT', { revision: baseline.revision, confirmed: true, total_credit_hours: Number(total), groups: groups.map(g => ({ ...(g.requirement_group_id ? { requirement_group_id: g.requirement_group_id } : {}), group_code: g.group_code, group_name: g.group_name, requirement_scope: g.requirement_scope, requirement_type: g.requirement_type, required_credit_hours: Number(g.required_credit_hours), is_active: !!g.is_active })) })
  }
  return <section aria-label="ميزانيات البرنامج" className="space-y-4"><h3 className="font-black">{baseline.data.program_name}</h3><Notice>قسم مستقل لميزانيات المتطلبات، وليس مجموع ساعات الدليل. المتاح من المواد والميزانية المطلوبة قيمتان مختلفتان من الخادم. لا تُضبط الميزانية تلقائيًا عند ربط مادة.</Notice><Notice>{baseline.capabilities.lock_reason}</Notice>{!baseline.configuration.available && <Notice>تهيئة الخطة غير مكتملة: {baseline.configuration.message}</Notice>}
    <form onSubmit={e => { e.preventDefault(); if (!disabled) setConfirm(true) }} className="space-y-4"><fieldset disabled={disabled} className="space-y-4"><Field label="إجمالي الساعات المطلوبة للبرنامج" error={mutation.fields.total_credit_hours}><Input name="total_credit_hours" type="number" dir="ltr" min="1" step="1" required value={total ?? ''} onChange={e => { setTotal(e.target.value); onDirty(true) }} /></Field>
      {groups.map((g, i) => <div key={g.requirement_group_id || `new-${i}`} className="grid gap-3 rounded-xl border p-3 md:grid-cols-2"><Field label="رمز المجموعة" error={mutation.fields[`groups.${i}.group_code`]}><Input dir="ltr" required maxLength={100} value={g.group_code} onChange={e => update(i, 'group_code', e.target.value)} /></Field><Field label="اسم المجموعة" error={mutation.fields[`groups.${i}.group_name`]}><Input required maxLength={200} value={g.group_name} onChange={e => update(i, 'group_name', e.target.value)} /></Field><Field label="مستوى المتطلب"><Select value={g.requirement_scope} onChange={e => update(i, 'requirement_scope', e.target.value)}>{scopes.map(([k, label]) => <option key={k} value={k}>{label}</option>)}</Select></Field><Field label="نوع المتطلب"><Select value={g.requirement_type} onChange={e => update(i, 'requirement_type', e.target.value)}>{types.map(([k, label]) => <option key={k} value={k}>{label}</option>)}</Select></Field><Field label="ميزانية الساعات المطلوبة" error={mutation.fields[`groups.${i}.required_credit_hours`]}><Input type="number" dir="ltr" min="0" step="1" required value={g.required_credit_hours} onChange={e => update(i, 'required_credit_hours', e.target.value)} /></Field><p className="text-sm">المتاح رسميًا: {g.available_credit_hours ?? 'لم يُحفظ'} ساعة — {g.course_count ?? '—'} مادة<br />فرق المتاح عن الميزانية المحفوظة (معلوماتي): {g.available_minus_required_hours ?? '—'}</p><label><input type="checkbox" checked={!!g.is_active} onChange={e => update(i, 'is_active', e.target.checked)} /> مجموعة نشطة</label>{!g.requirement_group_id && <Button onClick={() => { setGroups(rows => rows.filter((_, n) => i !== n)); onDirty(true) }}>إزالة المجموعة غير المحفوظة</Button>}</div>)}
      {groups.length < 6 && <Button onClick={() => { setGroups(rows => [...rows, { group_code: '', group_name: '', requirement_scope: 'university', requirement_type: 'mandatory', required_credit_hours: 0, is_active: true }]); onDirty(true) }}>إضافة مجموعة متطلبات</Button>}
    </fieldset><CatalogConflict mutation={mutation} onRestart={onRestart} />{baseline.capabilities.edit_curriculum && <Button primary type="submit" disabled={disabled || !groups.length}>حفظ ميزانيات البرنامج</Button>}</form>
    {confirm && <CatalogDialog title="تأكيد ميزانيات البرنامج" onClose={() => setConfirm(false)}><p>سيُحفظ التحديد الصريح للمجموعات وإجمالي البرنامج {total}. يتحقق النظام من اكتمال التهيئة ويعرض تحذيرًا إن كانت غير مكتملة؛ لا يعني النشاط موافقة أكاديمية على الخطة.</p><div className="mt-4 flex gap-2"><Button onClick={() => setConfirm(false)}>إلغاء</Button><Button primary onClick={save}>تأكيد الميزانيات</Button></div></CatalogDialog>}
  </section>
}

export function MembershipEditor({ baseline, course, onDirty, onBusy, onBlocked, onSaved, onRestart, onUnauthorized, busy }) {
  const pc = course.program_courses?.find(p => String(p.academic_program_id) === String(baseline.data.academic_program_id))
  const [draft, setDraft] = useState(() => ({ course_type: pc?.course_type || 'mandatory', requirement_scope: pc?.requirement_classification?.requirement_scope || 'university', requirement_group_id: pc?.requirement_mapping?.requirement_group_id || '', academic_level: pc?.academic_level_id ? { id: pc.academic_level_id, label: pc.academic_level?.level_name || 'المستوى الحالي' } : null, semester: pc?.recommended_semester_id ? { id: pc.recommended_semester_id, label: pc.recommended_semester?.semester_name || 'الفصل الحالي' } : null, is_active: pc?.is_active ?? true }))
  const [confirm, setConfirm] = useState(null)
  const path = `/programs/${baseline.data.academic_program_id}`
  const mutation = useCatalogMutation({ currentPath: path, onSaved, onBusy, onBlocked, onUnauthorized })
  const disabled = busy || mutation.blocked || !baseline.capabilities.edit_curriculum
  function update(key, value) { setDraft(d => ({ ...d, [key]: value, ...(['course_type', 'requirement_scope'].includes(key) ? { requirement_group_id: '' } : {}) })); onDirty(true) }
  function save() {
    const action = confirm; setConfirm(null)
    mutation.write(`${path}/courses/${course.course_id}`, action === 'unlink' ? 'DELETE' : 'PUT', action === 'unlink' ? { revision: baseline.revision, confirmed: true } : { revision: baseline.revision, course_type: draft.course_type, requirement_scope: draft.requirement_scope, requirement_group_id: Number(draft.requirement_group_id), academic_level_id: Number(draft.academic_level?.id), recommended_semester_id: Number(draft.semester?.id), is_active: !!draft.is_active })
  }
  return <section className="space-y-4" aria-label="ارتباط مادة ببرنامج"><h3 className="font-black">{course.course_name} — {baseline.data.program_name}</h3><Notice>التصنيف يخص هذا البرنامج فقط. المستوى والفصل إرشاديان، ولا يغيران الفصل الأكاديمي الفعلي أو أهلية الطرح. تعديل الارتباط لا يغيّر ميزانيات البرنامج.</Notice><Notice>{baseline.capabilities.lock_reason}</Notice>
    <Notice>الاختيار المقترح: {SCOPES[draft.requirement_scope]} — {TYPES[draft.course_type]}، بواقع {course.credit_hours} ساعات معتمدة في هذا البرنامج فقط.</Notice>
    <form onSubmit={e => { e.preventDefault(); if (!disabled) setConfirm('save') }} className="space-y-4"><fieldset disabled={disabled} className="grid gap-3 md:grid-cols-2"><Field label="مستوى المتطلب"><Select value={draft.requirement_scope} onChange={e => update('requirement_scope', e.target.value)}>{scopes.map(([k, label]) => <option key={k} value={k}>{label}</option>)}</Select></Field><Field label="نوع المادة في البرنامج"><Select value={draft.course_type} onChange={e => update('course_type', e.target.value)}>{types.map(([k, label]) => <option key={k} value={k}>{label}</option>)}</Select></Field><Field label="مجموعة المتطلبات" error={mutation.fields.requirement_group_id}><Select required value={draft.requirement_group_id} onChange={e => update('requirement_group_id', e.target.value)}><option value="">اختر مجموعة نشطة مطابقة</option>{baseline.groups.filter(g => g.is_active && g.requirement_scope === draft.requirement_scope && g.requirement_type === draft.course_type).map(g => <option key={g.requirement_group_id} value={g.requirement_group_id}>{g.group_name}</option>)}</Select></Field><CatalogLookup label="المستوى الإرشادي" resource="levels" disabled={disabled} clearLabel="اختر المستوى" value={draft.academic_level} onChange={o => update('academic_level', o)} /><CatalogLookup label="الفصل الإرشادي" resource="semesters" disabled={disabled} clearLabel="اختر الفصل" value={draft.semester} onChange={o => update('semester', o)} /><label><input type="checkbox" checked={!!draft.is_active} onChange={e => update('is_active', e.target.checked)} /> ارتباط نشط ضمن المنهج الحالي</label></fieldset>
      <CatalogConflict mutation={mutation} onRestart={onRestart} />{baseline.capabilities.edit_curriculum && <div className="flex flex-wrap gap-2"><Button primary type="submit" disabled={disabled || !draft.academic_level || !draft.semester || !draft.requirement_group_id}>حفظ ارتباط البرنامج</Button>{pc && <Button danger disabled={disabled} onClick={() => setConfirm('unlink')}>فصل المادة عن البرنامج فقط</Button>}</div>}
    </form>{confirm && <CatalogDialog title={confirm === 'unlink' ? 'فصل الارتباط دون حذف أصل المادة' : 'تأكيد ارتباط المادة'} onClose={() => setConfirm(null)}><p>{course.course_name} — {baseline.data.program_name}. لا يتغير أصل المادة أو ارتباطها بأي برنامج آخر.</p><div className="mt-4 flex gap-2"><Button onClick={() => setConfirm(null)}>إلغاء</Button><Button primary onClick={save}>تأكيد</Button></div></CatalogDialog>}
  </section>
}
