-- Read-only verification. Accept deployment only when OVERALL | PASS.
USE `alrowad_uni_rust`;

SET @srt4_verify_table := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND engine='InnoDB' AND table_comment LIKE 'Owned by semester-registration-timetable-phase4%');
SET @srt4_verify_columns := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots');
SET @srt4_verify_shape := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND (
  (column_name='course_offering_schedule_slot_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND is_nullable='NO' AND extra LIKE '%auto_increment%') OR
  (column_name='course_offering_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND is_nullable='NO') OR
  (column_name='component_type' AND data_type='varchar' AND character_maximum_length=16 AND is_nullable='NO') OR
  (column_name='day_of_week' AND data_type='tinyint' AND column_type NOT LIKE '%unsigned%' AND is_nullable='NO') OR
  (column_name IN ('start_time','end_time') AND data_type='time' AND is_nullable='NO') OR
  (column_name='location_label' AND data_type='varchar' AND character_maximum_length=150 AND is_nullable='YES') OR
  (column_name='created_by_user_id' AND data_type='int' AND column_type NOT LIKE '%unsigned%' AND is_nullable='NO') OR
  (column_name='created_at' AND data_type='timestamp' AND is_nullable='NO' AND LOWER(COALESCE(column_default,'')) LIKE 'current_timestamp%') OR
  (column_name='updated_at' AND data_type='timestamp' AND is_nullable='NO' AND LOWER(COALESCE(column_default,'')) LIKE 'current_timestamp%' AND extra LIKE '%on update%')
));
SET @srt4_verify_pk := (SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND index_name='PRIMARY' AND column_name='course_offering_schedule_slot_id' AND seq_in_index=1);
SET @srt4_verify_indexes := (SELECT COUNT(*) FROM (SELECT index_name,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols,MIN(non_unique) non_unique FROM information_schema.statistics WHERE table_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND index_name IN ('uq_coss_exact_slot','idx_coss_offering_window') GROUP BY index_name) x WHERE (index_name='uq_coss_exact_slot' AND cols='course_offering_id,component_type,day_of_week,start_time,end_time' AND non_unique=0) OR (index_name='idx_coss_offering_window' AND cols='course_offering_id,day_of_week,start_time,end_time' AND non_unique=1));
SET @srt4_verify_fks := (SELECT COUNT(*) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.table_schema AND r.table_name=k.table_name AND r.constraint_name=k.constraint_name WHERE k.table_schema='alrowad_uni_rust' AND k.table_name='course_offering_schedule_slots' AND r.update_rule='RESTRICT' AND r.delete_rule='RESTRICT' AND ((k.constraint_name='fk_coss_offering' AND k.column_name='course_offering_id' AND k.referenced_table_name='course_offerings' AND k.referenced_column_name='course_offering_id') OR (k.constraint_name='fk_coss_created_by' AND k.column_name='created_by_user_id' AND k.referenced_table_name='users' AND k.referenced_column_name='user_id')));
SET @srt4_verify_fk_total := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND constraint_type='FOREIGN KEY');
SET @srt4_verify_checks := (SELECT COUNT(*) FROM information_schema.table_constraints tc JOIN information_schema.check_constraints cc ON cc.constraint_schema=tc.constraint_schema AND cc.constraint_name=tc.constraint_name WHERE tc.constraint_schema='alrowad_uni_rust' AND tc.table_name='course_offering_schedule_slots' AND tc.constraint_type='CHECK' AND (
  (tc.constraint_name='chk_coss_component' AND LOWER(cc.check_clause) LIKE '%component_type%' AND LOWER(cc.check_clause) LIKE '%theoretical%' AND LOWER(cc.check_clause) LIKE '%practical%') OR
  (tc.constraint_name='chk_coss_day' AND LOWER(cc.check_clause) LIKE '%day_of_week%' AND LOWER(cc.check_clause) LIKE '%between%') OR
  (tc.constraint_name='chk_coss_interval' AND LOWER(cc.check_clause) LIKE '%start_time%' AND LOWER(cc.check_clause) LIKE '%end_time%' AND LOCATE('<',cc.check_clause)>0)
));
SET @srt4_verify_check_total := (SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema='alrowad_uni_rust' AND table_name='course_offering_schedule_slots' AND constraint_type='CHECK');
SET @srt4_verify_phase12 := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema='alrowad_uni_rust' AND ((table_name='semester_offering_requests' AND column_name='materialized_at') OR (table_name='academic_calendar_event_versions' AND column_name IN ('student_registration_ends_at','advisor_approval_ends_at')) OR (table_name='student_registration_requests' AND column_name='expired_at')));
SET @srt4_verify_rbac := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`permissions` WHERE permission_code='course_offerings.semester_governance.manage' AND is_active=1);
SET @srt4_verify_dean_role := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`roles` WHERE role_code='dean' AND is_active=1);
SET @srt4_verify_dean_mapping := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`roles` r JOIN `alrowad_uni_rust`.`role_permissions` rp ON rp.role_id=r.role_id JOIN `alrowad_uni_rust`.`permissions` p ON p.permission_id=rp.permission_id WHERE r.role_code='dean' AND r.is_active=1 AND p.permission_code='course_offerings.semester_governance.manage' AND p.is_active=1);
SET @srt4_verify_registered_status := (SELECT COUNT(*) FROM `alrowad_uni_rust`.`registration_statuses` WHERE status_code='registered');
SET @srt4_verify_pass := (@srt4_verify_table=1 AND @srt4_verify_columns=10 AND @srt4_verify_shape=10 AND @srt4_verify_pk=1 AND @srt4_verify_indexes=2 AND @srt4_verify_fks=2 AND @srt4_verify_fk_total=2 AND @srt4_verify_checks=3 AND @srt4_verify_check_total=3 AND @srt4_verify_phase12=4 AND @srt4_verify_rbac=1 AND @srt4_verify_dean_role=1 AND @srt4_verify_dean_mapping=1 AND @srt4_verify_registered_status=1);

SELECT 'TABLE_AND_COLUMNS' report_section,IF(@srt4_verify_table=1 AND @srt4_verify_columns=10 AND @srt4_verify_shape=10,'PASS','FAIL') result,CONCAT('table=',@srt4_verify_table,'/1; total_columns=',@srt4_verify_columns,'/10; compatible_columns=',@srt4_verify_shape,'/10') detail;
SELECT 'KEYS_INDEXES_CHECKS' report_section,IF(@srt4_verify_pk=1 AND @srt4_verify_indexes=2 AND @srt4_verify_fks=2 AND @srt4_verify_fk_total=2 AND @srt4_verify_checks=3 AND @srt4_verify_check_total=3,'PASS','FAIL') result,CONCAT('pk=',@srt4_verify_pk,'; indexes=',@srt4_verify_indexes,'/2; fks=',@srt4_verify_fks,'/',@srt4_verify_fk_total,'; checks=',@srt4_verify_checks,'/',@srt4_verify_check_total) detail;
SELECT 'PHASE1_PHASE2_AND_RBAC' report_section,IF(@srt4_verify_phase12=4 AND @srt4_verify_rbac=1 AND @srt4_verify_dean_role=1 AND @srt4_verify_dean_mapping=1 AND @srt4_verify_registered_status=1,'PASS','FAIL') result,CONCAT('phase_columns=',@srt4_verify_phase12,'/4; manage_permission=',@srt4_verify_rbac,'; dean_role=',@srt4_verify_dean_role,'; dean_mapping=',@srt4_verify_dean_mapping,'; registered_status=',@srt4_verify_registered_status) detail;
SELECT 'INFORMATIONAL_DATA' report_section,(SELECT COUNT(*) FROM `alrowad_uni_rust`.`course_offering_schedule_slots`) schedule_slot_count;
SELECT 'OVERALL' report_section,IF(@srt4_verify_pass,'PASS','FAIL') result;
